// Code generated by go-swagger; DO NOT EDIT.

package image

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/dockerctl/models"
)

// ImageGetAllReader is a Reader for the ImageGetAll structure.
type ImageGetAllReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ImageGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewImageGetAllOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewImageGetAllInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /images/get] ImageGetAll", response, response.Code())
	}
}

// NewImageGetAllOK creates a ImageGetAllOK with default headers values
func NewImageGetAllOK(writer io.Writer) *ImageGetAllOK {
	return &ImageGetAllOK{

		Payload: writer,
	}
}

/*
ImageGetAllOK describes a response with status code 200, with default header values.

no error
*/
type ImageGetAllOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this image get all o k response has a 2xx status code
func (o *ImageGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this image get all o k response has a 3xx status code
func (o *ImageGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this image get all o k response has a 4xx status code
func (o *ImageGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this image get all o k response has a 5xx status code
func (o *ImageGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this image get all o k response a status code equal to that given
func (o *ImageGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the image get all o k response
func (o *ImageGetAllOK) Code() int {
	return 200
}

func (o *ImageGetAllOK) Error() string {
	return fmt.Sprintf("[GET /images/get][%d] imageGetAllOK", 200)
}

func (o *ImageGetAllOK) String() string {
	return fmt.Sprintf("[GET /images/get][%d] imageGetAllOK", 200)
}

func (o *ImageGetAllOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ImageGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewImageGetAllInternalServerError creates a ImageGetAllInternalServerError with default headers values
func NewImageGetAllInternalServerError() *ImageGetAllInternalServerError {
	return &ImageGetAllInternalServerError{}
}

/*
ImageGetAllInternalServerError describes a response with status code 500, with default header values.

server error
*/
type ImageGetAllInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this image get all internal server error response has a 2xx status code
func (o *ImageGetAllInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this image get all internal server error response has a 3xx status code
func (o *ImageGetAllInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this image get all internal server error response has a 4xx status code
func (o *ImageGetAllInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this image get all internal server error response has a 5xx status code
func (o *ImageGetAllInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this image get all internal server error response a status code equal to that given
func (o *ImageGetAllInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the image get all internal server error response
func (o *ImageGetAllInternalServerError) Code() int {
	return 500
}

func (o *ImageGetAllInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /images/get][%d] imageGetAllInternalServerError %s", 500, payload)
}

func (o *ImageGetAllInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /images/get][%d] imageGetAllInternalServerError %s", 500, payload)
}

func (o *ImageGetAllInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ImageGetAllInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
