// Code generated by go-swagger; DO NOT EDIT.

package container

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/dockerctl/models"
)

// ContainerAttachWebsocketReader is a Reader for the ContainerAttachWebsocket structure.
type ContainerAttachWebsocketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerAttachWebsocketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 101:
		result := NewContainerAttachWebsocketSwitchingProtocols()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 200:
		result := NewContainerAttachWebsocketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewContainerAttachWebsocketBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewContainerAttachWebsocketNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerAttachWebsocketInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /containers/{id}/attach/ws] ContainerAttachWebsocket", response, response.Code())
	}
}

// NewContainerAttachWebsocketSwitchingProtocols creates a ContainerAttachWebsocketSwitchingProtocols with default headers values
func NewContainerAttachWebsocketSwitchingProtocols() *ContainerAttachWebsocketSwitchingProtocols {
	return &ContainerAttachWebsocketSwitchingProtocols{}
}

/*
ContainerAttachWebsocketSwitchingProtocols describes a response with status code 101, with default header values.

no error, hints proxy about hijacking
*/
type ContainerAttachWebsocketSwitchingProtocols struct {
}

// IsSuccess returns true when this container attach websocket switching protocols response has a 2xx status code
func (o *ContainerAttachWebsocketSwitchingProtocols) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this container attach websocket switching protocols response has a 3xx status code
func (o *ContainerAttachWebsocketSwitchingProtocols) IsRedirect() bool {
	return false
}

// IsClientError returns true when this container attach websocket switching protocols response has a 4xx status code
func (o *ContainerAttachWebsocketSwitchingProtocols) IsClientError() bool {
	return false
}

// IsServerError returns true when this container attach websocket switching protocols response has a 5xx status code
func (o *ContainerAttachWebsocketSwitchingProtocols) IsServerError() bool {
	return false
}

// IsCode returns true when this container attach websocket switching protocols response a status code equal to that given
func (o *ContainerAttachWebsocketSwitchingProtocols) IsCode(code int) bool {
	return code == 101
}

// Code gets the status code for the container attach websocket switching protocols response
func (o *ContainerAttachWebsocketSwitchingProtocols) Code() int {
	return 101
}

func (o *ContainerAttachWebsocketSwitchingProtocols) Error() string {
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketSwitchingProtocols", 101)
}

func (o *ContainerAttachWebsocketSwitchingProtocols) String() string {
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketSwitchingProtocols", 101)
}

func (o *ContainerAttachWebsocketSwitchingProtocols) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerAttachWebsocketOK creates a ContainerAttachWebsocketOK with default headers values
func NewContainerAttachWebsocketOK() *ContainerAttachWebsocketOK {
	return &ContainerAttachWebsocketOK{}
}

/*
ContainerAttachWebsocketOK describes a response with status code 200, with default header values.

no error, no upgrade header found
*/
type ContainerAttachWebsocketOK struct {
}

// IsSuccess returns true when this container attach websocket o k response has a 2xx status code
func (o *ContainerAttachWebsocketOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this container attach websocket o k response has a 3xx status code
func (o *ContainerAttachWebsocketOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this container attach websocket o k response has a 4xx status code
func (o *ContainerAttachWebsocketOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this container attach websocket o k response has a 5xx status code
func (o *ContainerAttachWebsocketOK) IsServerError() bool {
	return false
}

// IsCode returns true when this container attach websocket o k response a status code equal to that given
func (o *ContainerAttachWebsocketOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the container attach websocket o k response
func (o *ContainerAttachWebsocketOK) Code() int {
	return 200
}

func (o *ContainerAttachWebsocketOK) Error() string {
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketOK", 200)
}

func (o *ContainerAttachWebsocketOK) String() string {
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketOK", 200)
}

func (o *ContainerAttachWebsocketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerAttachWebsocketBadRequest creates a ContainerAttachWebsocketBadRequest with default headers values
func NewContainerAttachWebsocketBadRequest() *ContainerAttachWebsocketBadRequest {
	return &ContainerAttachWebsocketBadRequest{}
}

/*
ContainerAttachWebsocketBadRequest describes a response with status code 400, with default header values.

bad parameter
*/
type ContainerAttachWebsocketBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this container attach websocket bad request response has a 2xx status code
func (o *ContainerAttachWebsocketBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this container attach websocket bad request response has a 3xx status code
func (o *ContainerAttachWebsocketBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this container attach websocket bad request response has a 4xx status code
func (o *ContainerAttachWebsocketBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this container attach websocket bad request response has a 5xx status code
func (o *ContainerAttachWebsocketBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this container attach websocket bad request response a status code equal to that given
func (o *ContainerAttachWebsocketBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the container attach websocket bad request response
func (o *ContainerAttachWebsocketBadRequest) Code() int {
	return 400
}

func (o *ContainerAttachWebsocketBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketBadRequest %s", 400, payload)
}

func (o *ContainerAttachWebsocketBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketBadRequest %s", 400, payload)
}

func (o *ContainerAttachWebsocketBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ContainerAttachWebsocketBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewContainerAttachWebsocketNotFound creates a ContainerAttachWebsocketNotFound with default headers values
func NewContainerAttachWebsocketNotFound() *ContainerAttachWebsocketNotFound {
	return &ContainerAttachWebsocketNotFound{}
}

/*
ContainerAttachWebsocketNotFound describes a response with status code 404, with default header values.

no such container
*/
type ContainerAttachWebsocketNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this container attach websocket not found response has a 2xx status code
func (o *ContainerAttachWebsocketNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this container attach websocket not found response has a 3xx status code
func (o *ContainerAttachWebsocketNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this container attach websocket not found response has a 4xx status code
func (o *ContainerAttachWebsocketNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this container attach websocket not found response has a 5xx status code
func (o *ContainerAttachWebsocketNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this container attach websocket not found response a status code equal to that given
func (o *ContainerAttachWebsocketNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the container attach websocket not found response
func (o *ContainerAttachWebsocketNotFound) Code() int {
	return 404
}

func (o *ContainerAttachWebsocketNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketNotFound %s", 404, payload)
}

func (o *ContainerAttachWebsocketNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketNotFound %s", 404, payload)
}

func (o *ContainerAttachWebsocketNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ContainerAttachWebsocketNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewContainerAttachWebsocketInternalServerError creates a ContainerAttachWebsocketInternalServerError with default headers values
func NewContainerAttachWebsocketInternalServerError() *ContainerAttachWebsocketInternalServerError {
	return &ContainerAttachWebsocketInternalServerError{}
}

/*
ContainerAttachWebsocketInternalServerError describes a response with status code 500, with default header values.

server error
*/
type ContainerAttachWebsocketInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this container attach websocket internal server error response has a 2xx status code
func (o *ContainerAttachWebsocketInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this container attach websocket internal server error response has a 3xx status code
func (o *ContainerAttachWebsocketInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this container attach websocket internal server error response has a 4xx status code
func (o *ContainerAttachWebsocketInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this container attach websocket internal server error response has a 5xx status code
func (o *ContainerAttachWebsocketInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this container attach websocket internal server error response a status code equal to that given
func (o *ContainerAttachWebsocketInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the container attach websocket internal server error response
func (o *ContainerAttachWebsocketInternalServerError) Code() int {
	return 500
}

func (o *ContainerAttachWebsocketInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketInternalServerError %s", 500, payload)
}

func (o *ContainerAttachWebsocketInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /containers/{id}/attach/ws][%d] containerAttachWebsocketInternalServerError %s", 500, payload)
}

func (o *ContainerAttachWebsocketInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ContainerAttachWebsocketInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
