// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"
	"log"
	"os"
	"path"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-swagger/dockerctl/client"
)

var (
	// debug flag indicating that cli should output debug logs
	debug bool

	// config file location
	configFile string

	// dry run flag
	dryRun bool

	// name of the executable
	exeName = filepath.Base(os.Args[0])
)

// logDebugf writes debug log to stdout
func logDebugf(format string, v ...any) {
	if !debug {
		return
	}
	log.Printf(format, v...)
}

// depth of recursion to construct model flags
var maxDepth int = 5

// makeClient constructs a client object
func makeClient(cmd *cobra.Command, _ []string) (*client.DockerEngineAPI, error) {
	hostname := viper.GetString("hostname")
	viper.SetDefault("base_path", client.DefaultBasePath)
	basePath := viper.GetString("base_path")
	scheme := viper.GetString("scheme")

	r := httptransport.New(hostname, basePath, []string{scheme})
	r.SetDebug(debug)
	// set custom producer and consumer to use the default ones

	// warning: consumes application/octet-stream is not supported by go-swagger cli yet

	r.Consumers["application/json"] = runtime.JSONConsumer()

	// warning: consumes application/x-tar is not supported by go-swagger cli yet

	// warning: consumes text/plain is not supported by go-swagger cli yet

	// warning: produces application/octet-stream is not supported by go-swagger cli yet
	// warning: produces application/vnd.docker.raw-stream is not supported by go-swagger cli yet
	r.Producers["application/json"] = runtime.JSONProducer()
	// warning: produces application/x-tar is not supported by go-swagger cli yet
	// warning: produces text/plain is not supported by go-swagger cli yet

	appCli := client.New(r, strfmt.Default)
	logDebugf("Server url: %v://%v", scheme, hostname)

	return appCli, nil
}

// MakeRootCmd returns the root cmd
func MakeRootCmd() (*cobra.Command, error) {
	cobra.OnInitialize(initViperConfigs)

	// Use executable name as the command name
	rootCmd := &cobra.Command{
		Use: exeName,
	}

	// register basic flags
	rootCmd.PersistentFlags().String("hostname", client.DefaultHost, "hostname of the service")
	if err := viper.BindPFlag("hostname", rootCmd.PersistentFlags().Lookup("hostname")); err != nil {
		return nil, err
	}
	rootCmd.PersistentFlags().String("scheme", client.DefaultSchemes[0], fmt.Sprintf("Choose from: %v", client.DefaultSchemes))
	if err := viper.BindPFlag("scheme", rootCmd.PersistentFlags().Lookup("scheme")); err != nil {
		return nil, err
	}
	rootCmd.PersistentFlags().String("base-path", client.DefaultBasePath, fmt.Sprintf("For example: %v", client.DefaultBasePath))
	if err := viper.BindPFlag("base_path", rootCmd.PersistentFlags().Lookup("base-path")); err != nil {
		return nil, err
	}

	// configure debug flag
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "output debug logs")
	// configure config location
	rootCmd.PersistentFlags().StringVar(&configFile, "config", "", "config file path")
	// configure dry run flag
	rootCmd.PersistentFlags().BoolVar(&dryRun, "dry-run", false, "do not send the request to server")

	// register security flags

	// add all operation groups
	c0, err := makeGroupOfOperationsConfigCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c0)
	c1, err := makeGroupOfOperationsContainerCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c1)
	c2, err := makeGroupOfOperationsDistributionCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c2)
	c3, err := makeGroupOfOperationsExecCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c3)
	c4, err := makeGroupOfOperationsImageCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c4)
	c5, err := makeGroupOfOperationsNetworkCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c5)
	c6, err := makeGroupOfOperationsNodeCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c6)
	c7, err := makeGroupOfOperationsPluginCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c7)
	c8, err := makeGroupOfOperationsSecretCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c8)
	c9, err := makeGroupOfOperationsServiceCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c9)
	c10, err := makeGroupOfOperationsSessionCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c10)
	c11, err := makeGroupOfOperationsSwarmCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c11)
	c12, err := makeGroupOfOperationsSystemCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c12)
	c13, err := makeGroupOfOperationsTaskCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c13)
	c14, err := makeGroupOfOperationsVolumeCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(c14)

	// add cobra completion
	rootCmd.AddCommand(makeGenCompletionCmd())

	// add cobra markdown
	markdownCmd := makeMarkdownDocumentationCmd()
	rootCmd.AddCommand(markdownCmd)
	markdownCmd.Flags().String("dir", "./markdown/", "The destination directory to save docs in")
	_ = viper.BindPFlag("markdown_dir", markdownCmd.Flags().Lookup("dir"))

	return rootCmd, nil
}

// initViperConfigs initialize viper config using config file in '$HOME/.config/<cli name>/config.<json|yaml...>'
// currently hostname, scheme and auth tokens can be specified in this config file.
func initViperConfigs() {
	if configFile != "" {
		// use user specified config file location
		viper.SetConfigFile(configFile)
	} else {
		var (
			configDir string
			err       error
		)

		// look for default config (OS-specific, e.g. ".config" on linux)
		configDir, err = os.UserConfigDir()
		if err != nil {
			// fallback and try finding the home directory.
			home, err := os.UserHomeDir()
			cobra.CheckErr(err)
			configDir = path.Join(home, ".config")
		}

		// Search config in the config directory with name of the CLI binary (without extension).
		configDir = path.Join(configDir, exeName)
		viper.AddConfigPath(configDir)
		viper.SetConfigName("config")
	}

	if err := viper.ReadInConfig(); err != nil {
		logDebugf("Error: loading config file: %v", err)
		return
	}
	logDebugf("Using config file: %v", viper.ConfigFileUsed())
} // makeGroupOfOperationsConfigCmd returns a parent command to handle all operations with tag "config"
func makeGroupOfOperationsConfigCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "config",
		Long: ``,
	}

	sub0, err := makeOperationConfigConfigCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationConfigConfigDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationConfigConfigInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationConfigConfigListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationConfigConfigUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	return parent, nil
} // makeGroupOfOperationsContainerCmd returns a parent command to handle all operations with tag "container"
func makeGroupOfOperationsContainerCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "container",
		Long: ``,
	}

	sub0, err := makeOperationContainerContainerArchiveCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationContainerContainerArchiveInfoCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationContainerContainerAttachCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationContainerContainerAttachWebsocketCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationContainerContainerChangesCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationContainerContainerCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationContainerContainerDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationContainerContainerExportCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationContainerContainerInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationContainerContainerKillCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationContainerContainerListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	sub11, err := makeOperationContainerContainerLogsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub11)

	sub12, err := makeOperationContainerContainerPauseCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub12)

	sub13, err := makeOperationContainerContainerPruneCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub13)

	sub14, err := makeOperationContainerContainerRenameCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub14)

	sub15, err := makeOperationContainerContainerResizeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub15)

	sub16, err := makeOperationContainerContainerRestartCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub16)

	sub17, err := makeOperationContainerContainerStartCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub17)

	sub18, err := makeOperationContainerContainerStatsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub18)

	sub19, err := makeOperationContainerContainerStopCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub19)

	sub20, err := makeOperationContainerContainerTopCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub20)

	sub21, err := makeOperationContainerContainerUnpauseCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub21)

	sub22, err := makeOperationContainerContainerUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub22)

	sub23, err := makeOperationContainerContainerWaitCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub23)

	sub24, err := makeOperationContainerPutContainerArchiveCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub24)

	return parent, nil
} // makeGroupOfOperationsDistributionCmd returns a parent command to handle all operations with tag "distribution"
func makeGroupOfOperationsDistributionCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "distribution",
		Long: ``,
	}

	sub0, err := makeOperationDistributionDistributionInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	return parent, nil
} // makeGroupOfOperationsExecCmd returns a parent command to handle all operations with tag "exec"
func makeGroupOfOperationsExecCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "exec",
		Long: ``,
	}

	sub0, err := makeOperationExecContainerExecCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationExecExecInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationExecExecResizeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationExecExecStartCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	return parent, nil
} // makeGroupOfOperationsImageCmd returns a parent command to handle all operations with tag "image"
func makeGroupOfOperationsImageCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "image",
		Long: ``,
	}

	sub0, err := makeOperationImageBuildPruneCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationImageImageBuildCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationImageImageCommitCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationImageImageCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationImageImageDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationImageImageGetCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationImageImageGetAllCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationImageImageHistoryCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationImageImageInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationImageImageListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationImageImageLoadCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	sub11, err := makeOperationImageImagePruneCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub11)

	sub12, err := makeOperationImageImagePushCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub12)

	sub13, err := makeOperationImageImageSearchCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub13)

	sub14, err := makeOperationImageImageTagCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub14)

	return parent, nil
} // makeGroupOfOperationsNetworkCmd returns a parent command to handle all operations with tag "network"
func makeGroupOfOperationsNetworkCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "network",
		Long: ``,
	}

	sub0, err := makeOperationNetworkNetworkConnectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationNetworkNetworkCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationNetworkNetworkDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationNetworkNetworkDisconnectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationNetworkNetworkInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationNetworkNetworkListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationNetworkNetworkPruneCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	return parent, nil
} // makeGroupOfOperationsNodeCmd returns a parent command to handle all operations with tag "node"
func makeGroupOfOperationsNodeCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "node",
		Long: ``,
	}

	sub0, err := makeOperationNodeNodeDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationNodeNodeInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationNodeNodeListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationNodeNodeUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	return parent, nil
} // makeGroupOfOperationsPluginCmd returns a parent command to handle all operations with tag "plugin"
func makeGroupOfOperationsPluginCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "plugin",
		Long: ``,
	}

	sub0, err := makeOperationPluginGetPluginPrivilegesCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationPluginPluginCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationPluginPluginDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationPluginPluginDisableCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationPluginPluginEnableCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationPluginPluginInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationPluginPluginListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	sub7, err := makeOperationPluginPluginPullCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub7)

	sub8, err := makeOperationPluginPluginPushCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub8)

	sub9, err := makeOperationPluginPluginSetCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub9)

	sub10, err := makeOperationPluginPluginUpgradeCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub10)

	return parent, nil
} // makeGroupOfOperationsSecretCmd returns a parent command to handle all operations with tag "secret"
func makeGroupOfOperationsSecretCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "secret",
		Long: ``,
	}

	sub0, err := makeOperationSecretSecretCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationSecretSecretDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationSecretSecretInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationSecretSecretListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationSecretSecretUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	return parent, nil
} // makeGroupOfOperationsServiceCmd returns a parent command to handle all operations with tag "service"
func makeGroupOfOperationsServiceCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "service",
		Long: ``,
	}

	sub0, err := makeOperationServiceServiceCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationServiceServiceDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationServiceServiceInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationServiceServiceListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationServiceServiceLogsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationServiceServiceUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	return parent, nil
} // makeGroupOfOperationsSessionCmd returns a parent command to handle all operations with tag "session"
func makeGroupOfOperationsSessionCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "session",
		Long: ``,
	}

	sub0, err := makeOperationSessionSessionCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	return parent, nil
} // makeGroupOfOperationsSwarmCmd returns a parent command to handle all operations with tag "swarm"
func makeGroupOfOperationsSwarmCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "swarm",
		Long: ``,
	}

	sub0, err := makeOperationSwarmSwarmInitCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationSwarmSwarmInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationSwarmSwarmJoinCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationSwarmSwarmLeaveCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationSwarmSwarmUnlockCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationSwarmSwarmUnlockkeyCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationSwarmSwarmUpdateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	return parent, nil
} // makeGroupOfOperationsSystemCmd returns a parent command to handle all operations with tag "system"
func makeGroupOfOperationsSystemCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "system",
		Long: ``,
	}

	sub0, err := makeOperationSystemSystemAuthCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationSystemSystemDataUsageCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationSystemSystemEventsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationSystemSystemInfoCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationSystemSystemPingCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	sub5, err := makeOperationSystemSystemPingHeadCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub5)

	sub6, err := makeOperationSystemSystemVersionCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub6)

	return parent, nil
} // makeGroupOfOperationsTaskCmd returns a parent command to handle all operations with tag "task"
func makeGroupOfOperationsTaskCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "task",
		Long: ``,
	}

	sub0, err := makeOperationTaskTaskInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationTaskTaskListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationTaskTaskLogsCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	return parent, nil
} // makeGroupOfOperationsVolumeCmd returns a parent command to handle all operations with tag "volume"
func makeGroupOfOperationsVolumeCmd() (*cobra.Command, error) {
	parent := &cobra.Command{
		Use:  "volume",
		Long: ``,
	}

	sub0, err := makeOperationVolumeVolumeCreateCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub0)

	sub1, err := makeOperationVolumeVolumeDeleteCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub1)

	sub2, err := makeOperationVolumeVolumeInspectCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub2)

	sub3, err := makeOperationVolumeVolumeListCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub3)

	sub4, err := makeOperationVolumeVolumePruneCmd()
	if err != nil {
		return nil, err
	}
	parent.AddCommand(sub4)

	return parent, nil
}
