// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationContainerContainerPauseCmd returns a command to handle operation containerPause
func makeOperationContainerContainerPauseCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "ContainerPause",
		Short: `Use the freezer cgroup to suspend all processes in a container.

Traditionally, when suspending a process the ` + "`" + `SIGSTOP` + "`" + ` signal is used, which is observable by the process being suspended. With the freezer cgroup the process is unaware, and unable to capture, that it is being suspended, and subsequently resumed.
`,
		RunE: runOperationContainerContainerPause,
	}

	if err := registerOperationContainerContainerPauseParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerPause uses cmd flags to call endpoint api
func runOperationContainerContainerPause(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerPauseParams()
	if err, _ = retrieveOperationContainerContainerPauseIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerPauseResult(appCli.Container.ContainerPause(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationContainerContainerPauseParamFlags registers all flags needed to fill params
func registerOperationContainerContainerPauseParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerPauseIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerPauseIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. ID or name of the container`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func retrieveOperationContainerContainerPauseIDFlag(m *container.ContainerPauseParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

// parseOperationContainerContainerPauseResult parses request result and return the string content
func parseOperationContainerContainerPauseResult(resp0 *container.ContainerPauseNoContent, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning containerPauseNoContent is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*container.ContainerPauseNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*container.ContainerPauseInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response containerPauseNoContent is not supported by go-swagger cli yet.
	return "", nil
}
