// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationContainerContainerPruneCmd returns a command to handle operation containerPrune
func makeOperationContainerContainerPruneCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerPrune",
		Short: ``,
		RunE:  runOperationContainerContainerPrune,
	}

	if err := registerOperationContainerContainerPruneParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerPrune uses cmd flags to call endpoint api
func runOperationContainerContainerPrune(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerPruneParams()
	if err, _ = retrieveOperationContainerContainerPruneFiltersFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerPruneResult(appCli.Container.ContainerPrune(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationContainerContainerPruneParamFlags registers all flags needed to fill params
func registerOperationContainerContainerPruneParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerPruneFiltersParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerPruneFiltersParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagFiltersDescription := `Filters to process on the prune list, encoded as JSON (a ` + "`" + `map[string][]string` + "`" + `).

Available filters:
- ` + "`" + `until=<timestamp>` + "`" + ` Prune containers created before this timestamp. The ` + "`" + `<timestamp>` + "`" + ` can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. ` + "`" + `10m` + "`" + `, ` + "`" + `1h30m` + "`" + `) computed relative to the daemon machine’s time.
- ` + "`" + `label` + "`" + ` (` + "`" + `label=<key>` + "`" + `, ` + "`" + `label=<key>=<value>` + "`" + `, ` + "`" + `label!=<key>` + "`" + `, or ` + "`" + `label!=<key>=<value>` + "`" + `) Prune containers with (or without, in case ` + "`" + `label!=...` + "`" + ` is used) the specified labels.
`

	var flagFiltersName string
	if cmdPrefix == "" {
		flagFiltersName = "filters"
	} else {
		flagFiltersName = fmt.Sprintf("%v.filters", cmdPrefix)
	}

	var flagFiltersDefault string

	_ = cmd.PersistentFlags().String(flagFiltersName, flagFiltersDefault, flagFiltersDescription)

	return nil
}

func retrieveOperationContainerContainerPruneFiltersFlag(m *container.ContainerPruneParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("filters") {

		var flagFiltersName string
		if cmdPrefix == "" {
			flagFiltersName = "filters"
		} else {
			flagFiltersName = fmt.Sprintf("%v.filters", cmdPrefix)
		}

		flagFiltersValue, err := cmd.Flags().GetString(flagFiltersName)
		if err != nil {
			return err, false
		}
		m.Filters = &flagFiltersValue

	}

	return nil, retAdded
}

// parseOperationContainerContainerPruneResult parses request result and return the string content
func parseOperationContainerContainerPruneResult(resp0 *container.ContainerPruneOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*container.ContainerPruneOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*container.ContainerPruneInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}

// register flags to command
func registerModelContainerPruneOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerPruneOKBodyPropContainersDeleted(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerPruneOKBodyPropSpaceReclaimed(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerPruneOKBodyPropContainersDeleted(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: ContainersDeleted []string array type is not supported by go-swagger cli yet

	return nil
}

func registerContainerPruneOKBodyPropSpaceReclaimed(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSpaceReclaimedDescription := `Disk space reclaimed in bytes`

	var flagSpaceReclaimedName string
	if cmdPrefix == "" {
		flagSpaceReclaimedName = "SpaceReclaimed"
	} else {
		flagSpaceReclaimedName = fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
	}

	var flagSpaceReclaimedDefault int64

	_ = cmd.PersistentFlags().Int64(flagSpaceReclaimedName, flagSpaceReclaimedDefault, flagSpaceReclaimedDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerPruneOKBodyFlags(depth int, m *container.ContainerPruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ContainersDeletedAdded := retrieveContainerPruneOKBodyPropContainersDeletedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ContainersDeletedAdded

	err, SpaceReclaimedAdded := retrieveContainerPruneOKBodyPropSpaceReclaimedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SpaceReclaimedAdded

	return nil, retAdded
}

func retrieveContainerPruneOKBodyPropContainersDeletedFlags(depth int, m *container.ContainerPruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagContainersDeletedName := fmt.Sprintf("%v.ContainersDeleted", cmdPrefix)
	if cmd.Flags().Changed(flagContainersDeletedName) {
		// warning: ContainersDeleted array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveContainerPruneOKBodyPropSpaceReclaimedFlags(depth int, m *container.ContainerPruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSpaceReclaimedName := fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
	if cmd.Flags().Changed(flagSpaceReclaimedName) {

		var flagSpaceReclaimedName string
		if cmdPrefix == "" {
			flagSpaceReclaimedName = "SpaceReclaimed"
		} else {
			flagSpaceReclaimedName = fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
		}

		flagSpaceReclaimedValue, err := cmd.Flags().GetInt64(flagSpaceReclaimedName)
		if err != nil {
			return err, false
		}
		m.SpaceReclaimed = flagSpaceReclaimedValue

		retAdded = true
	}

	return nil, retAdded
}
