// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationContainerContainerRenameCmd returns a command to handle operation containerRename
func makeOperationContainerContainerRenameCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerRename",
		Short: ``,
		RunE:  runOperationContainerContainerRename,
	}

	if err := registerOperationContainerContainerRenameParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerRename uses cmd flags to call endpoint api
func runOperationContainerContainerRename(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerRenameParams()
	if err, _ = retrieveOperationContainerContainerRenameIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationContainerContainerRenameNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerRenameResult(appCli.Container.ContainerRename(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationContainerContainerRenameParamFlags registers all flags needed to fill params
func registerOperationContainerContainerRenameParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerRenameIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerRenameNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerRenameIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. ID or name of the container`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerOperationContainerContainerRenameNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. New name for the container`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func retrieveOperationContainerContainerRenameIDFlag(m *container.ContainerRenameParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

func retrieveOperationContainerContainerRenameNameFlag(m *container.ContainerRenameParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

// parseOperationContainerContainerRenameResult parses request result and return the string content
func parseOperationContainerContainerRenameResult(resp0 *container.ContainerRenameNoContent, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning containerRenameNoContent is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*container.ContainerRenameNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*container.ContainerRenameConflict)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp3 any = respErr
		eresp3, ok := iResp3.(*container.ContainerRenameInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp3) && !swag.IsZero(eresp3.Payload) {
				msgStr, err := json.Marshal(eresp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response containerRenameNoContent is not supported by go-swagger cli yet.
	return "", nil
}
