// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"
	"github.com/go-swagger/dockerctl/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationContainerContainerCreateCmd returns a command to handle operation containerCreate
func makeOperationContainerContainerCreateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerCreate",
		Short: ``,
		RunE:  runOperationContainerContainerCreate,
	}

	if err := registerOperationContainerContainerCreateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerCreate uses cmd flags to call endpoint api
func runOperationContainerContainerCreate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerCreateParams()
	if err, _ = retrieveOperationContainerContainerCreateBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationContainerContainerCreateNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerCreateResult(appCli.Container.ContainerCreate(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationContainerContainerCreateParamFlags registers all flags needed to fill params
func registerOperationContainerContainerCreateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerCreateBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerCreateNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerCreateBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. Container to create`)

	// add flags for body
	if err := registerModelContainerCreateBodyFlags(0, "containerCreateBody", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationContainerContainerCreateNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Assign the specified name to the container. Must match ` + "`" + `/?[a-zA-Z0-9][a-zA-Z0-9_.-]+` + "`" + `.`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func retrieveOperationContainerContainerCreateBodyFlag(m *container.ContainerCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := container.ContainerCreateBody{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in ContainerCreateBody: %w", err), false
		}
		m.Body = flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = container.ContainerCreateBody{}
	}
	err, added := retrieveModelContainerCreateBodyFlags(0, &flagBodyModel, "containerCreateBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationContainerContainerCreateNameFlag(m *container.ContainerCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = &flagNameValue

	}

	return nil, retAdded
}

// parseOperationContainerContainerCreateResult parses request result and return the string content
func parseOperationContainerContainerCreateResult(resp0 *container.ContainerCreateCreated, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*container.ContainerCreateCreated)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*container.ContainerCreateBadRequest)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*container.ContainerCreateNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp3 any = respErr
		eresp3, ok := iResp3.(*container.ContainerCreateConflict)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp3) && !swag.IsZero(eresp3.Payload) {
				msgStr, err := json.Marshal(eresp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp4 any = respErr
		eresp4, ok := iResp4.(*container.ContainerCreateInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp4) && !swag.IsZero(eresp4.Payload) {
				msgStr, err := json.Marshal(eresp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}

// register flags to command
func registerModelContainerCreateBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.ContainerConfig flags

	if err := registerModelContainerConfigFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for ContainerCreateParamsBodyAO1

	if err := registerContainerCreateBodyPropAnonContainerCreateParamsBodyAO1HostConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerCreateBodyPropAnonContainerCreateParamsBodyAO1NetworkingConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name ContainerCreateParamsBodyAO1, type

func registerContainerCreateBodyPropAnonContainerCreateParamsBodyAO1HostConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagHostConfigName string
	if cmdPrefix == "" {
		flagHostConfigName = "HostConfig"
	} else {
		flagHostConfigName = fmt.Sprintf("%v.HostConfig", cmdPrefix)
	}

	if err := registerModelHostConfigFlags(depth+1, flagHostConfigName, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerCreateBodyPropAnonContainerCreateParamsBodyAO1NetworkingConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagNetworkingConfigName string
	if cmdPrefix == "" {
		flagNetworkingConfigName = "NetworkingConfig"
	} else {
		flagNetworkingConfigName = fmt.Sprintf("%v.NetworkingConfig", cmdPrefix)
	}

	if err := registerModelContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigFlags(depth+1, flagNetworkingConfigName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerCreateBodyFlags(depth int, m *container.ContainerCreateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.ContainerConfig
	err, ContainerCreateParamsBodyAO0Added := retrieveModelContainerConfigFlags(depth, &m.ContainerConfig, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ContainerCreateParamsBodyAO0Added

	// retrieve allOf ContainerCreateParamsBodyAO1 fields

	err, HostConfigAdded := retrieveContainerCreateBodyPropAnonContainerCreateParamsBodyAO1HostConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostConfigAdded

	err, NetworkingConfigAdded := retrieveContainerCreateBodyPropAnonContainerCreateParamsBodyAO1NetworkingConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NetworkingConfigAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name ContainerCreateParamsBodyAO1

func retrieveContainerCreateBodyPropAnonContainerCreateParamsBodyAO1HostConfigFlags(depth int, m *container.ContainerCreateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHostConfigName := fmt.Sprintf("%v.HostConfig", cmdPrefix)
	if cmd.Flags().Changed(flagHostConfigName) {
		// info: complex object HostConfig models.HostConfig is retrieved outside this Changed() block
	}
	flagHostConfigValue := m.HostConfig
	if swag.IsZero(flagHostConfigValue) {
		flagHostConfigValue = &models.HostConfig{}
	}

	err, HostConfigAdded := retrieveModelHostConfigFlags(depth+1, flagHostConfigValue, flagHostConfigName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostConfigAdded
	if HostConfigAdded {
		m.HostConfig = flagHostConfigValue
	}

	return nil, retAdded
}

func retrieveContainerCreateBodyPropAnonContainerCreateParamsBodyAO1NetworkingConfigFlags(depth int, m *container.ContainerCreateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNetworkingConfigName := fmt.Sprintf("%v.NetworkingConfig", cmdPrefix)
	if cmd.Flags().Changed(flagNetworkingConfigName) {
		// info: complex object NetworkingConfig ContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfig is retrieved outside this Changed() block
	}
	flagNetworkingConfigValue := m.NetworkingConfig
	if swag.IsZero(flagNetworkingConfigValue) {
		flagNetworkingConfigValue = &container.ContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfig{}
	}

	err, NetworkingConfigAdded := retrieveModelContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigFlags(depth+1, flagNetworkingConfigValue, flagNetworkingConfigName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NetworkingConfigAdded
	if NetworkingConfigAdded {
		m.NetworkingConfig = flagNetworkingConfigValue
	}

	return nil, retAdded
}

// register flags to command
func registerModelContainerCreateCreatedBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerCreateCreatedBodyPropID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerCreateCreatedBodyPropWarnings(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerCreateCreatedBodyPropID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIDDescription := `Required. The ID of the created container`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "Id"
	} else {
		flagIDName = fmt.Sprintf("%v.Id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerContainerCreateCreatedBodyPropWarnings(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Warnings []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerCreateCreatedBodyFlags(depth int, m *container.ContainerCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IDAdded := retrieveContainerCreateCreatedBodyPropIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IDAdded

	err, WarningsAdded := retrieveContainerCreateCreatedBodyPropWarningsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || WarningsAdded

	return nil, retAdded
}

func retrieveContainerCreateCreatedBodyPropIDFlags(depth int, m *container.ContainerCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIDName := fmt.Sprintf("%v.Id", cmdPrefix)
	if cmd.Flags().Changed(flagIDName) {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "Id"
		} else {
			flagIDName = fmt.Sprintf("%v.Id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerCreateCreatedBodyPropWarningsFlags(depth int, m *container.ContainerCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagWarningsName := fmt.Sprintf("%v.Warnings", cmdPrefix)
	if cmd.Flags().Changed(flagWarningsName) {
		// warning: Warnings array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

// register flags to command
func registerModelContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigPropEndpointsConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigPropEndpointsConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: EndpointsConfig map[string]models.EndpointSettings map type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigFlags(depth int, m *container.ContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, EndpointsConfigAdded := retrieveContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigPropEndpointsConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EndpointsConfigAdded

	return nil, retAdded
}

func retrieveContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfigPropEndpointsConfigFlags(depth int, m *container.ContainerCreateParamsBodyContainerCreateParamsBodyAO1NetworkingConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEndpointsConfigName := fmt.Sprintf("%v.EndpointsConfig", cmdPrefix)
	if cmd.Flags().Changed(flagEndpointsConfigName) {
		// warning: EndpointsConfig map type map[string]models.EndpointSettings is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
