// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"
	"github.com/go-swagger/dockerctl/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationContainerContainerInspectCmd returns a command to handle operation containerInspect
func makeOperationContainerContainerInspectCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerInspect",
		Short: `Return low-level information about a container.`,
		RunE:  runOperationContainerContainerInspect,
	}

	if err := registerOperationContainerContainerInspectParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerInspect uses cmd flags to call endpoint api
func runOperationContainerContainerInspect(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerInspectParams()
	if err, _ = retrieveOperationContainerContainerInspectIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationContainerContainerInspectSizeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerInspectResult(appCli.Container.ContainerInspect(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationContainerContainerInspectParamFlags registers all flags needed to fill params
func registerOperationContainerContainerInspectParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerInspectIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerInspectSizeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerInspectIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. ID or name of the container`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerOperationContainerContainerInspectSizeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagSizeDescription := `Return the size of container as fields ` + "`" + `SizeRw` + "`" + ` and ` + "`" + `SizeRootFs` + "`" + ``

	var flagSizeName string
	if cmdPrefix == "" {
		flagSizeName = "size"
	} else {
		flagSizeName = fmt.Sprintf("%v.size", cmdPrefix)
	}

	var flagSizeDefault bool

	_ = cmd.PersistentFlags().Bool(flagSizeName, flagSizeDefault, flagSizeDescription)

	return nil
}

func retrieveOperationContainerContainerInspectIDFlag(m *container.ContainerInspectParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

func retrieveOperationContainerContainerInspectSizeFlag(m *container.ContainerInspectParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("size") {

		var flagSizeName string
		if cmdPrefix == "" {
			flagSizeName = "size"
		} else {
			flagSizeName = fmt.Sprintf("%v.size", cmdPrefix)
		}

		flagSizeValue, err := cmd.Flags().GetBool(flagSizeName)
		if err != nil {
			return err, false
		}
		m.Size = &flagSizeValue

	}

	return nil, retAdded
}

// parseOperationContainerContainerInspectResult parses request result and return the string content
func parseOperationContainerContainerInspectResult(resp0 *container.ContainerInspectOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*container.ContainerInspectOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*container.ContainerInspectNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*container.ContainerInspectInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}

// register flags to command
func registerModelContainerInspectOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerInspectOKBodyPropAppArmorProfile(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropArgs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropCreated(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropDriver(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropExecIDs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropGraphDriver(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropHostConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropHostnamePath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropHostsPath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropImage(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropLogPath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropMountLabel(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropMounts(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropNetworkSettings(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropNode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropPath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropPlatform(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropProcessLabel(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropResolvConfPath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropRestartCount(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropSizeRootFs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropSizeRw(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyPropState(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyPropAppArmorProfile(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAppArmorProfileDescription := ``

	var flagAppArmorProfileName string
	if cmdPrefix == "" {
		flagAppArmorProfileName = "AppArmorProfile"
	} else {
		flagAppArmorProfileName = fmt.Sprintf("%v.AppArmorProfile", cmdPrefix)
	}

	var flagAppArmorProfileDefault string

	_ = cmd.PersistentFlags().String(flagAppArmorProfileName, flagAppArmorProfileDefault, flagAppArmorProfileDescription)

	return nil
}

func registerContainerInspectOKBodyPropArgs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Args []string array type is not supported by go-swagger cli yet

	return nil
}

func registerContainerInspectOKBodyPropConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagConfigName string
	if cmdPrefix == "" {
		flagConfigName = "Config"
	} else {
		flagConfigName = fmt.Sprintf("%v.Config", cmdPrefix)
	}

	if err := registerModelContainerConfigFlags(depth+1, flagConfigName, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyPropCreated(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCreatedDescription := `The time the container was created`

	var flagCreatedName string
	if cmdPrefix == "" {
		flagCreatedName = "Created"
	} else {
		flagCreatedName = fmt.Sprintf("%v.Created", cmdPrefix)
	}

	var flagCreatedDefault string

	_ = cmd.PersistentFlags().String(flagCreatedName, flagCreatedDefault, flagCreatedDescription)

	return nil
}

func registerContainerInspectOKBodyPropDriver(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDriverDescription := ``

	var flagDriverName string
	if cmdPrefix == "" {
		flagDriverName = "Driver"
	} else {
		flagDriverName = fmt.Sprintf("%v.Driver", cmdPrefix)
	}

	var flagDriverDefault string

	_ = cmd.PersistentFlags().String(flagDriverName, flagDriverDefault, flagDriverDescription)

	return nil
}

func registerContainerInspectOKBodyPropExecIDs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: ExecIDs []string array type is not supported by go-swagger cli yet

	return nil
}

func registerContainerInspectOKBodyPropGraphDriver(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagGraphDriverName string
	if cmdPrefix == "" {
		flagGraphDriverName = "GraphDriver"
	} else {
		flagGraphDriverName = fmt.Sprintf("%v.GraphDriver", cmdPrefix)
	}

	if err := registerModelGraphDriverDataFlags(depth+1, flagGraphDriverName, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyPropHostConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagHostConfigName string
	if cmdPrefix == "" {
		flagHostConfigName = "HostConfig"
	} else {
		flagHostConfigName = fmt.Sprintf("%v.HostConfig", cmdPrefix)
	}

	if err := registerModelHostConfigFlags(depth+1, flagHostConfigName, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyPropHostnamePath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagHostnamePathDescription := ``

	var flagHostnamePathName string
	if cmdPrefix == "" {
		flagHostnamePathName = "HostnamePath"
	} else {
		flagHostnamePathName = fmt.Sprintf("%v.HostnamePath", cmdPrefix)
	}

	var flagHostnamePathDefault string

	_ = cmd.PersistentFlags().String(flagHostnamePathName, flagHostnamePathDefault, flagHostnamePathDescription)

	return nil
}

func registerContainerInspectOKBodyPropHostsPath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagHostsPathDescription := ``

	var flagHostsPathName string
	if cmdPrefix == "" {
		flagHostsPathName = "HostsPath"
	} else {
		flagHostsPathName = fmt.Sprintf("%v.HostsPath", cmdPrefix)
	}

	var flagHostsPathDefault string

	_ = cmd.PersistentFlags().String(flagHostsPathName, flagHostsPathDefault, flagHostsPathDescription)

	return nil
}

func registerContainerInspectOKBodyPropID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIDDescription := `The ID of the container`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "Id"
	} else {
		flagIDName = fmt.Sprintf("%v.Id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerContainerInspectOKBodyPropImage(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagImageDescription := `The container's image`

	var flagImageName string
	if cmdPrefix == "" {
		flagImageName = "Image"
	} else {
		flagImageName = fmt.Sprintf("%v.Image", cmdPrefix)
	}

	var flagImageDefault string

	_ = cmd.PersistentFlags().String(flagImageName, flagImageDefault, flagImageDescription)

	return nil
}

func registerContainerInspectOKBodyPropLogPath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLogPathDescription := ``

	var flagLogPathName string
	if cmdPrefix == "" {
		flagLogPathName = "LogPath"
	} else {
		flagLogPathName = fmt.Sprintf("%v.LogPath", cmdPrefix)
	}

	var flagLogPathDefault string

	_ = cmd.PersistentFlags().String(flagLogPathName, flagLogPathDefault, flagLogPathDescription)

	return nil
}

func registerContainerInspectOKBodyPropMountLabel(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMountLabelDescription := ``

	var flagMountLabelName string
	if cmdPrefix == "" {
		flagMountLabelName = "MountLabel"
	} else {
		flagMountLabelName = fmt.Sprintf("%v.MountLabel", cmdPrefix)
	}

	var flagMountLabelDefault string

	_ = cmd.PersistentFlags().String(flagMountLabelName, flagMountLabelDefault, flagMountLabelDescription)

	return nil
}

func registerContainerInspectOKBodyPropMounts(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Mounts []*models.MountPoint array type is not supported by go-swagger cli yet

	return nil
}

func registerContainerInspectOKBodyPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := ``

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "Name"
	} else {
		flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerContainerInspectOKBodyPropNetworkSettings(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagNetworkSettingsName string
	if cmdPrefix == "" {
		flagNetworkSettingsName = "NetworkSettings"
	} else {
		flagNetworkSettingsName = fmt.Sprintf("%v.NetworkSettings", cmdPrefix)
	}

	if err := registerModelNetworkSettingsFlags(depth+1, flagNetworkSettingsName, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyPropNode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Node any map type is not supported by go-swagger cli yet

	return nil
}

func registerContainerInspectOKBodyPropPath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPathDescription := `The path to the command being run`

	var flagPathName string
	if cmdPrefix == "" {
		flagPathName = "Path"
	} else {
		flagPathName = fmt.Sprintf("%v.Path", cmdPrefix)
	}

	var flagPathDefault string

	_ = cmd.PersistentFlags().String(flagPathName, flagPathDefault, flagPathDescription)

	return nil
}

func registerContainerInspectOKBodyPropPlatform(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPlatformDescription := ``

	var flagPlatformName string
	if cmdPrefix == "" {
		flagPlatformName = "Platform"
	} else {
		flagPlatformName = fmt.Sprintf("%v.Platform", cmdPrefix)
	}

	var flagPlatformDefault string

	_ = cmd.PersistentFlags().String(flagPlatformName, flagPlatformDefault, flagPlatformDescription)

	return nil
}

func registerContainerInspectOKBodyPropProcessLabel(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagProcessLabelDescription := ``

	var flagProcessLabelName string
	if cmdPrefix == "" {
		flagProcessLabelName = "ProcessLabel"
	} else {
		flagProcessLabelName = fmt.Sprintf("%v.ProcessLabel", cmdPrefix)
	}

	var flagProcessLabelDefault string

	_ = cmd.PersistentFlags().String(flagProcessLabelName, flagProcessLabelDefault, flagProcessLabelDescription)

	return nil
}

func registerContainerInspectOKBodyPropResolvConfPath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagResolvConfPathDescription := ``

	var flagResolvConfPathName string
	if cmdPrefix == "" {
		flagResolvConfPathName = "ResolvConfPath"
	} else {
		flagResolvConfPathName = fmt.Sprintf("%v.ResolvConfPath", cmdPrefix)
	}

	var flagResolvConfPathDefault string

	_ = cmd.PersistentFlags().String(flagResolvConfPathName, flagResolvConfPathDefault, flagResolvConfPathDescription)

	return nil
}

func registerContainerInspectOKBodyPropRestartCount(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRestartCountDescription := ``

	var flagRestartCountName string
	if cmdPrefix == "" {
		flagRestartCountName = "RestartCount"
	} else {
		flagRestartCountName = fmt.Sprintf("%v.RestartCount", cmdPrefix)
	}

	var flagRestartCountDefault int64

	_ = cmd.PersistentFlags().Int64(flagRestartCountName, flagRestartCountDefault, flagRestartCountDescription)

	return nil
}

func registerContainerInspectOKBodyPropSizeRootFs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSizeRootFsDescription := `The total size of all the files in this container.`

	var flagSizeRootFsName string
	if cmdPrefix == "" {
		flagSizeRootFsName = "SizeRootFs"
	} else {
		flagSizeRootFsName = fmt.Sprintf("%v.SizeRootFs", cmdPrefix)
	}

	var flagSizeRootFsDefault int64

	_ = cmd.PersistentFlags().Int64(flagSizeRootFsName, flagSizeRootFsDefault, flagSizeRootFsDescription)

	return nil
}

func registerContainerInspectOKBodyPropSizeRw(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSizeRwDescription := `The size of files that have been created or changed by this container.`

	var flagSizeRwName string
	if cmdPrefix == "" {
		flagSizeRwName = "SizeRw"
	} else {
		flagSizeRwName = fmt.Sprintf("%v.SizeRw", cmdPrefix)
	}

	var flagSizeRwDefault int64

	_ = cmd.PersistentFlags().Int64(flagSizeRwName, flagSizeRwDefault, flagSizeRwDescription)

	return nil
}

func registerContainerInspectOKBodyPropState(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagStateName string
	if cmdPrefix == "" {
		flagStateName = "State"
	} else {
		flagStateName = fmt.Sprintf("%v.State", cmdPrefix)
	}

	if err := registerModelContainerInspectOKBodyStateFlags(depth+1, flagStateName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerInspectOKBodyFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AppArmorProfileAdded := retrieveContainerInspectOKBodyPropAppArmorProfileFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AppArmorProfileAdded

	err, ArgsAdded := retrieveContainerInspectOKBodyPropArgsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ArgsAdded

	err, ConfigAdded := retrieveContainerInspectOKBodyPropConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ConfigAdded

	err, CreatedAdded := retrieveContainerInspectOKBodyPropCreatedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CreatedAdded

	err, DriverAdded := retrieveContainerInspectOKBodyPropDriverFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DriverAdded

	err, ExecIDsAdded := retrieveContainerInspectOKBodyPropExecIDsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExecIDsAdded

	err, GraphDriverAdded := retrieveContainerInspectOKBodyPropGraphDriverFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GraphDriverAdded

	err, HostConfigAdded := retrieveContainerInspectOKBodyPropHostConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostConfigAdded

	err, HostnamePathAdded := retrieveContainerInspectOKBodyPropHostnamePathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostnamePathAdded

	err, HostsPathAdded := retrieveContainerInspectOKBodyPropHostsPathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostsPathAdded

	err, IDAdded := retrieveContainerInspectOKBodyPropIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IDAdded

	err, ImageAdded := retrieveContainerInspectOKBodyPropImageFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ImageAdded

	err, LogPathAdded := retrieveContainerInspectOKBodyPropLogPathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LogPathAdded

	err, MountLabelAdded := retrieveContainerInspectOKBodyPropMountLabelFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MountLabelAdded

	err, MountsAdded := retrieveContainerInspectOKBodyPropMountsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MountsAdded

	err, NameAdded := retrieveContainerInspectOKBodyPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, NetworkSettingsAdded := retrieveContainerInspectOKBodyPropNetworkSettingsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NetworkSettingsAdded

	err, NodeAdded := retrieveContainerInspectOKBodyPropNodeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NodeAdded

	err, PathAdded := retrieveContainerInspectOKBodyPropPathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PathAdded

	err, PlatformAdded := retrieveContainerInspectOKBodyPropPlatformFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PlatformAdded

	err, ProcessLabelAdded := retrieveContainerInspectOKBodyPropProcessLabelFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ProcessLabelAdded

	err, ResolvConfPathAdded := retrieveContainerInspectOKBodyPropResolvConfPathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ResolvConfPathAdded

	err, RestartCountAdded := retrieveContainerInspectOKBodyPropRestartCountFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RestartCountAdded

	err, SizeRootFsAdded := retrieveContainerInspectOKBodyPropSizeRootFsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SizeRootFsAdded

	err, SizeRwAdded := retrieveContainerInspectOKBodyPropSizeRwFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SizeRwAdded

	err, StateAdded := retrieveContainerInspectOKBodyPropStateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StateAdded

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropAppArmorProfileFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAppArmorProfileName := fmt.Sprintf("%v.AppArmorProfile", cmdPrefix)
	if cmd.Flags().Changed(flagAppArmorProfileName) {

		var flagAppArmorProfileName string
		if cmdPrefix == "" {
			flagAppArmorProfileName = "AppArmorProfile"
		} else {
			flagAppArmorProfileName = fmt.Sprintf("%v.AppArmorProfile", cmdPrefix)
		}

		flagAppArmorProfileValue, err := cmd.Flags().GetString(flagAppArmorProfileName)
		if err != nil {
			return err, false
		}
		m.AppArmorProfile = flagAppArmorProfileValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropArgsFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagArgsName := fmt.Sprintf("%v.Args", cmdPrefix)
	if cmd.Flags().Changed(flagArgsName) {
		// warning: Args array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropConfigFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagConfigName := fmt.Sprintf("%v.Config", cmdPrefix)
	if cmd.Flags().Changed(flagConfigName) {
		// info: complex object Config models.ContainerConfig is retrieved outside this Changed() block
	}
	flagConfigValue := m.Config
	if swag.IsZero(flagConfigValue) {
		flagConfigValue = &models.ContainerConfig{}
	}

	err, ConfigAdded := retrieveModelContainerConfigFlags(depth+1, flagConfigValue, flagConfigName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ConfigAdded
	if ConfigAdded {
		m.Config = flagConfigValue
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropCreatedFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCreatedName := fmt.Sprintf("%v.Created", cmdPrefix)
	if cmd.Flags().Changed(flagCreatedName) {

		var flagCreatedName string
		if cmdPrefix == "" {
			flagCreatedName = "Created"
		} else {
			flagCreatedName = fmt.Sprintf("%v.Created", cmdPrefix)
		}

		flagCreatedValue, err := cmd.Flags().GetString(flagCreatedName)
		if err != nil {
			return err, false
		}
		m.Created = flagCreatedValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropDriverFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDriverName := fmt.Sprintf("%v.Driver", cmdPrefix)
	if cmd.Flags().Changed(flagDriverName) {

		var flagDriverName string
		if cmdPrefix == "" {
			flagDriverName = "Driver"
		} else {
			flagDriverName = fmt.Sprintf("%v.Driver", cmdPrefix)
		}

		flagDriverValue, err := cmd.Flags().GetString(flagDriverName)
		if err != nil {
			return err, false
		}
		m.Driver = flagDriverValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropExecIDsFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExecIDsName := fmt.Sprintf("%v.ExecIDs", cmdPrefix)
	if cmd.Flags().Changed(flagExecIDsName) {
		// warning: ExecIDs array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropGraphDriverFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagGraphDriverName := fmt.Sprintf("%v.GraphDriver", cmdPrefix)
	if cmd.Flags().Changed(flagGraphDriverName) {
		// info: complex object GraphDriver models.GraphDriverData is retrieved outside this Changed() block
	}
	flagGraphDriverValue := m.GraphDriver
	if swag.IsZero(flagGraphDriverValue) {
		flagGraphDriverValue = &models.GraphDriverData{}
	}

	err, GraphDriverAdded := retrieveModelGraphDriverDataFlags(depth+1, flagGraphDriverValue, flagGraphDriverName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GraphDriverAdded
	if GraphDriverAdded {
		m.GraphDriver = flagGraphDriverValue
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropHostConfigFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHostConfigName := fmt.Sprintf("%v.HostConfig", cmdPrefix)
	if cmd.Flags().Changed(flagHostConfigName) {
		// info: complex object HostConfig models.HostConfig is retrieved outside this Changed() block
	}
	flagHostConfigValue := m.HostConfig
	if swag.IsZero(flagHostConfigValue) {
		flagHostConfigValue = &models.HostConfig{}
	}

	err, HostConfigAdded := retrieveModelHostConfigFlags(depth+1, flagHostConfigValue, flagHostConfigName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HostConfigAdded
	if HostConfigAdded {
		m.HostConfig = flagHostConfigValue
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropHostnamePathFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHostnamePathName := fmt.Sprintf("%v.HostnamePath", cmdPrefix)
	if cmd.Flags().Changed(flagHostnamePathName) {

		var flagHostnamePathName string
		if cmdPrefix == "" {
			flagHostnamePathName = "HostnamePath"
		} else {
			flagHostnamePathName = fmt.Sprintf("%v.HostnamePath", cmdPrefix)
		}

		flagHostnamePathValue, err := cmd.Flags().GetString(flagHostnamePathName)
		if err != nil {
			return err, false
		}
		m.HostnamePath = flagHostnamePathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropHostsPathFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHostsPathName := fmt.Sprintf("%v.HostsPath", cmdPrefix)
	if cmd.Flags().Changed(flagHostsPathName) {

		var flagHostsPathName string
		if cmdPrefix == "" {
			flagHostsPathName = "HostsPath"
		} else {
			flagHostsPathName = fmt.Sprintf("%v.HostsPath", cmdPrefix)
		}

		flagHostsPathValue, err := cmd.Flags().GetString(flagHostsPathName)
		if err != nil {
			return err, false
		}
		m.HostsPath = flagHostsPathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropIDFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIDName := fmt.Sprintf("%v.Id", cmdPrefix)
	if cmd.Flags().Changed(flagIDName) {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "Id"
		} else {
			flagIDName = fmt.Sprintf("%v.Id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropImageFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagImageName := fmt.Sprintf("%v.Image", cmdPrefix)
	if cmd.Flags().Changed(flagImageName) {

		var flagImageName string
		if cmdPrefix == "" {
			flagImageName = "Image"
		} else {
			flagImageName = fmt.Sprintf("%v.Image", cmdPrefix)
		}

		flagImageValue, err := cmd.Flags().GetString(flagImageName)
		if err != nil {
			return err, false
		}
		m.Image = flagImageValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropLogPathFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLogPathName := fmt.Sprintf("%v.LogPath", cmdPrefix)
	if cmd.Flags().Changed(flagLogPathName) {

		var flagLogPathName string
		if cmdPrefix == "" {
			flagLogPathName = "LogPath"
		} else {
			flagLogPathName = fmt.Sprintf("%v.LogPath", cmdPrefix)
		}

		flagLogPathValue, err := cmd.Flags().GetString(flagLogPathName)
		if err != nil {
			return err, false
		}
		m.LogPath = flagLogPathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropMountLabelFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMountLabelName := fmt.Sprintf("%v.MountLabel", cmdPrefix)
	if cmd.Flags().Changed(flagMountLabelName) {

		var flagMountLabelName string
		if cmdPrefix == "" {
			flagMountLabelName = "MountLabel"
		} else {
			flagMountLabelName = fmt.Sprintf("%v.MountLabel", cmdPrefix)
		}

		flagMountLabelValue, err := cmd.Flags().GetString(flagMountLabelName)
		if err != nil {
			return err, false
		}
		m.MountLabel = flagMountLabelValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropMountsFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMountsName := fmt.Sprintf("%v.Mounts", cmdPrefix)
	if cmd.Flags().Changed(flagMountsName) {
		// warning: Mounts array type []*models.MountPoint is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropNameFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.Name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "Name"
		} else {
			flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropNetworkSettingsFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNetworkSettingsName := fmt.Sprintf("%v.NetworkSettings", cmdPrefix)
	if cmd.Flags().Changed(flagNetworkSettingsName) {
		// info: complex object NetworkSettings models.NetworkSettings is retrieved outside this Changed() block
	}
	flagNetworkSettingsValue := m.NetworkSettings
	if swag.IsZero(flagNetworkSettingsValue) {
		flagNetworkSettingsValue = &models.NetworkSettings{}
	}

	err, NetworkSettingsAdded := retrieveModelNetworkSettingsFlags(depth+1, flagNetworkSettingsValue, flagNetworkSettingsName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NetworkSettingsAdded
	if NetworkSettingsAdded {
		m.NetworkSettings = flagNetworkSettingsValue
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropNodeFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNodeName := fmt.Sprintf("%v.Node", cmdPrefix)
	if cmd.Flags().Changed(flagNodeName) {
		// warning: Node map type any is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropPathFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPathName := fmt.Sprintf("%v.Path", cmdPrefix)
	if cmd.Flags().Changed(flagPathName) {

		var flagPathName string
		if cmdPrefix == "" {
			flagPathName = "Path"
		} else {
			flagPathName = fmt.Sprintf("%v.Path", cmdPrefix)
		}

		flagPathValue, err := cmd.Flags().GetString(flagPathName)
		if err != nil {
			return err, false
		}
		m.Path = flagPathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropPlatformFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPlatformName := fmt.Sprintf("%v.Platform", cmdPrefix)
	if cmd.Flags().Changed(flagPlatformName) {

		var flagPlatformName string
		if cmdPrefix == "" {
			flagPlatformName = "Platform"
		} else {
			flagPlatformName = fmt.Sprintf("%v.Platform", cmdPrefix)
		}

		flagPlatformValue, err := cmd.Flags().GetString(flagPlatformName)
		if err != nil {
			return err, false
		}
		m.Platform = flagPlatformValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropProcessLabelFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagProcessLabelName := fmt.Sprintf("%v.ProcessLabel", cmdPrefix)
	if cmd.Flags().Changed(flagProcessLabelName) {

		var flagProcessLabelName string
		if cmdPrefix == "" {
			flagProcessLabelName = "ProcessLabel"
		} else {
			flagProcessLabelName = fmt.Sprintf("%v.ProcessLabel", cmdPrefix)
		}

		flagProcessLabelValue, err := cmd.Flags().GetString(flagProcessLabelName)
		if err != nil {
			return err, false
		}
		m.ProcessLabel = flagProcessLabelValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropResolvConfPathFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagResolvConfPathName := fmt.Sprintf("%v.ResolvConfPath", cmdPrefix)
	if cmd.Flags().Changed(flagResolvConfPathName) {

		var flagResolvConfPathName string
		if cmdPrefix == "" {
			flagResolvConfPathName = "ResolvConfPath"
		} else {
			flagResolvConfPathName = fmt.Sprintf("%v.ResolvConfPath", cmdPrefix)
		}

		flagResolvConfPathValue, err := cmd.Flags().GetString(flagResolvConfPathName)
		if err != nil {
			return err, false
		}
		m.ResolvConfPath = flagResolvConfPathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropRestartCountFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRestartCountName := fmt.Sprintf("%v.RestartCount", cmdPrefix)
	if cmd.Flags().Changed(flagRestartCountName) {

		var flagRestartCountName string
		if cmdPrefix == "" {
			flagRestartCountName = "RestartCount"
		} else {
			flagRestartCountName = fmt.Sprintf("%v.RestartCount", cmdPrefix)
		}

		flagRestartCountValue, err := cmd.Flags().GetInt64(flagRestartCountName)
		if err != nil {
			return err, false
		}
		m.RestartCount = flagRestartCountValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropSizeRootFsFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSizeRootFsName := fmt.Sprintf("%v.SizeRootFs", cmdPrefix)
	if cmd.Flags().Changed(flagSizeRootFsName) {

		var flagSizeRootFsName string
		if cmdPrefix == "" {
			flagSizeRootFsName = "SizeRootFs"
		} else {
			flagSizeRootFsName = fmt.Sprintf("%v.SizeRootFs", cmdPrefix)
		}

		flagSizeRootFsValue, err := cmd.Flags().GetInt64(flagSizeRootFsName)
		if err != nil {
			return err, false
		}
		m.SizeRootFs = flagSizeRootFsValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropSizeRwFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSizeRwName := fmt.Sprintf("%v.SizeRw", cmdPrefix)
	if cmd.Flags().Changed(flagSizeRwName) {

		var flagSizeRwName string
		if cmdPrefix == "" {
			flagSizeRwName = "SizeRw"
		} else {
			flagSizeRwName = fmt.Sprintf("%v.SizeRw", cmdPrefix)
		}

		flagSizeRwValue, err := cmd.Flags().GetInt64(flagSizeRwName)
		if err != nil {
			return err, false
		}
		m.SizeRw = flagSizeRwValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyPropStateFlags(depth int, m *container.ContainerInspectOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStateName := fmt.Sprintf("%v.State", cmdPrefix)
	if cmd.Flags().Changed(flagStateName) {
		// info: complex object State ContainerInspectOKBodyState is retrieved outside this Changed() block
	}
	flagStateValue := m.State
	if swag.IsZero(flagStateValue) {
		flagStateValue = &container.ContainerInspectOKBodyState{}
	}

	err, StateAdded := retrieveModelContainerInspectOKBodyStateFlags(depth+1, flagStateValue, flagStateName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StateAdded
	if StateAdded {
		m.State = flagStateValue
	}

	return nil, retAdded
}

// register flags to command
func registerModelContainerInspectOKBodyStateFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerInspectOKBodyStatePropDead(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropError(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropExitCode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropFinishedAt(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropOOMKilled(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropPaused(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropPid(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropRestarting(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropRunning(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropStartedAt(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerContainerInspectOKBodyStatePropStatus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerInspectOKBodyStatePropDead(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDeadDescription := ``

	var flagDeadName string
	if cmdPrefix == "" {
		flagDeadName = "Dead"
	} else {
		flagDeadName = fmt.Sprintf("%v.Dead", cmdPrefix)
	}

	var flagDeadDefault bool

	_ = cmd.PersistentFlags().Bool(flagDeadName, flagDeadDefault, flagDeadDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropError(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagErrorDescription := ``

	var flagErrorName string
	if cmdPrefix == "" {
		flagErrorName = "Error"
	} else {
		flagErrorName = fmt.Sprintf("%v.Error", cmdPrefix)
	}

	var flagErrorDefault string

	_ = cmd.PersistentFlags().String(flagErrorName, flagErrorDefault, flagErrorDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropExitCode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagExitCodeDescription := `The last exit code of this container`

	var flagExitCodeName string
	if cmdPrefix == "" {
		flagExitCodeName = "ExitCode"
	} else {
		flagExitCodeName = fmt.Sprintf("%v.ExitCode", cmdPrefix)
	}

	var flagExitCodeDefault int64

	_ = cmd.PersistentFlags().Int64(flagExitCodeName, flagExitCodeDefault, flagExitCodeDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropFinishedAt(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFinishedAtDescription := `The time when this container last exited.`

	var flagFinishedAtName string
	if cmdPrefix == "" {
		flagFinishedAtName = "FinishedAt"
	} else {
		flagFinishedAtName = fmt.Sprintf("%v.FinishedAt", cmdPrefix)
	}

	var flagFinishedAtDefault string

	_ = cmd.PersistentFlags().String(flagFinishedAtName, flagFinishedAtDefault, flagFinishedAtDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropOOMKilled(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagOOMKilledDescription := `Whether this container has been killed because it ran out of memory.`

	var flagOOMKilledName string
	if cmdPrefix == "" {
		flagOOMKilledName = "OOMKilled"
	} else {
		flagOOMKilledName = fmt.Sprintf("%v.OOMKilled", cmdPrefix)
	}

	var flagOOMKilledDefault bool

	_ = cmd.PersistentFlags().Bool(flagOOMKilledName, flagOOMKilledDefault, flagOOMKilledDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropPaused(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPausedDescription := `Whether this container is paused.`

	var flagPausedName string
	if cmdPrefix == "" {
		flagPausedName = "Paused"
	} else {
		flagPausedName = fmt.Sprintf("%v.Paused", cmdPrefix)
	}

	var flagPausedDefault bool

	_ = cmd.PersistentFlags().Bool(flagPausedName, flagPausedDefault, flagPausedDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropPid(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPidDescription := `The process ID of this container`

	var flagPidName string
	if cmdPrefix == "" {
		flagPidName = "Pid"
	} else {
		flagPidName = fmt.Sprintf("%v.Pid", cmdPrefix)
	}

	var flagPidDefault int64

	_ = cmd.PersistentFlags().Int64(flagPidName, flagPidDefault, flagPidDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropRestarting(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRestartingDescription := `Whether this container is restarting.`

	var flagRestartingName string
	if cmdPrefix == "" {
		flagRestartingName = "Restarting"
	} else {
		flagRestartingName = fmt.Sprintf("%v.Restarting", cmdPrefix)
	}

	var flagRestartingDefault bool

	_ = cmd.PersistentFlags().Bool(flagRestartingName, flagRestartingDefault, flagRestartingDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropRunning(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRunningDescription := `Whether this container is running.

Note that a running container can be _paused_. The ` + "`" + `Running` + "`" + ` and ` + "`" + `Paused` + "`" + `
booleans are not mutually exclusive:

When pausing a container (on Linux), the freezer cgroup is used to suspend
all processes in the container. Freezing the process requires the process to
be running. As a result, paused containers are both ` + "`" + `Running` + "`" + ` _and_ ` + "`" + `Paused` + "`" + `.

Use the ` + "`" + `Status` + "`" + ` field instead to determine if a container's state is "running".
`

	var flagRunningName string
	if cmdPrefix == "" {
		flagRunningName = "Running"
	} else {
		flagRunningName = fmt.Sprintf("%v.Running", cmdPrefix)
	}

	var flagRunningDefault bool

	_ = cmd.PersistentFlags().Bool(flagRunningName, flagRunningDefault, flagRunningDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropStartedAt(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStartedAtDescription := `The time when this container was last started.`

	var flagStartedAtName string
	if cmdPrefix == "" {
		flagStartedAtName = "StartedAt"
	} else {
		flagStartedAtName = fmt.Sprintf("%v.StartedAt", cmdPrefix)
	}

	var flagStartedAtDefault string

	_ = cmd.PersistentFlags().String(flagStartedAtName, flagStartedAtDefault, flagStartedAtDescription)

	return nil
}

func registerContainerInspectOKBodyStatePropStatus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStatusDescription := `Enum: ["created","running","paused","restarting","removing","exited","dead"]. The status of the container. For example, ` + "`" + `"running"` + "`" + ` or ` + "`" + `"exited"` + "`" + `.
`

	var flagStatusName string
	if cmdPrefix == "" {
		flagStatusName = "Status"
	} else {
		flagStatusName = fmt.Sprintf("%v.Status", cmdPrefix)
	}

	var flagStatusDefault string

	_ = cmd.PersistentFlags().String(flagStatusName, flagStatusDefault, flagStatusDescription)

	if err := cmd.RegisterFlagCompletionFunc(flagStatusName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["created","running","paused","restarting","removing","exited","dead"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerInspectOKBodyStateFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, DeadAdded := retrieveContainerInspectOKBodyStatePropDeadFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DeadAdded

	err, ErrorAdded := retrieveContainerInspectOKBodyStatePropErrorFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ErrorAdded

	err, ExitCodeAdded := retrieveContainerInspectOKBodyStatePropExitCodeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ExitCodeAdded

	err, FinishedAtAdded := retrieveContainerInspectOKBodyStatePropFinishedAtFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FinishedAtAdded

	err, OOMKilledAdded := retrieveContainerInspectOKBodyStatePropOOMKilledFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || OOMKilledAdded

	err, PausedAdded := retrieveContainerInspectOKBodyStatePropPausedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PausedAdded

	err, PidAdded := retrieveContainerInspectOKBodyStatePropPidFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PidAdded

	err, RestartingAdded := retrieveContainerInspectOKBodyStatePropRestartingFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RestartingAdded

	err, RunningAdded := retrieveContainerInspectOKBodyStatePropRunningFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RunningAdded

	err, StartedAtAdded := retrieveContainerInspectOKBodyStatePropStartedAtFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StartedAtAdded

	err, StatusAdded := retrieveContainerInspectOKBodyStatePropStatusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StatusAdded

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropDeadFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDeadName := fmt.Sprintf("%v.Dead", cmdPrefix)
	if cmd.Flags().Changed(flagDeadName) {

		var flagDeadName string
		if cmdPrefix == "" {
			flagDeadName = "Dead"
		} else {
			flagDeadName = fmt.Sprintf("%v.Dead", cmdPrefix)
		}

		flagDeadValue, err := cmd.Flags().GetBool(flagDeadName)
		if err != nil {
			return err, false
		}
		m.Dead = flagDeadValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropErrorFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagErrorName := fmt.Sprintf("%v.Error", cmdPrefix)
	if cmd.Flags().Changed(flagErrorName) {

		var flagErrorName string
		if cmdPrefix == "" {
			flagErrorName = "Error"
		} else {
			flagErrorName = fmt.Sprintf("%v.Error", cmdPrefix)
		}

		flagErrorValue, err := cmd.Flags().GetString(flagErrorName)
		if err != nil {
			return err, false
		}
		m.Error = flagErrorValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropExitCodeFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagExitCodeName := fmt.Sprintf("%v.ExitCode", cmdPrefix)
	if cmd.Flags().Changed(flagExitCodeName) {

		var flagExitCodeName string
		if cmdPrefix == "" {
			flagExitCodeName = "ExitCode"
		} else {
			flagExitCodeName = fmt.Sprintf("%v.ExitCode", cmdPrefix)
		}

		flagExitCodeValue, err := cmd.Flags().GetInt64(flagExitCodeName)
		if err != nil {
			return err, false
		}
		m.ExitCode = flagExitCodeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropFinishedAtFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFinishedAtName := fmt.Sprintf("%v.FinishedAt", cmdPrefix)
	if cmd.Flags().Changed(flagFinishedAtName) {

		var flagFinishedAtName string
		if cmdPrefix == "" {
			flagFinishedAtName = "FinishedAt"
		} else {
			flagFinishedAtName = fmt.Sprintf("%v.FinishedAt", cmdPrefix)
		}

		flagFinishedAtValue, err := cmd.Flags().GetString(flagFinishedAtName)
		if err != nil {
			return err, false
		}
		m.FinishedAt = flagFinishedAtValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropOOMKilledFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagOOMKilledName := fmt.Sprintf("%v.OOMKilled", cmdPrefix)
	if cmd.Flags().Changed(flagOOMKilledName) {

		var flagOOMKilledName string
		if cmdPrefix == "" {
			flagOOMKilledName = "OOMKilled"
		} else {
			flagOOMKilledName = fmt.Sprintf("%v.OOMKilled", cmdPrefix)
		}

		flagOOMKilledValue, err := cmd.Flags().GetBool(flagOOMKilledName)
		if err != nil {
			return err, false
		}
		m.OOMKilled = flagOOMKilledValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropPausedFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPausedName := fmt.Sprintf("%v.Paused", cmdPrefix)
	if cmd.Flags().Changed(flagPausedName) {

		var flagPausedName string
		if cmdPrefix == "" {
			flagPausedName = "Paused"
		} else {
			flagPausedName = fmt.Sprintf("%v.Paused", cmdPrefix)
		}

		flagPausedValue, err := cmd.Flags().GetBool(flagPausedName)
		if err != nil {
			return err, false
		}
		m.Paused = flagPausedValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropPidFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPidName := fmt.Sprintf("%v.Pid", cmdPrefix)
	if cmd.Flags().Changed(flagPidName) {

		var flagPidName string
		if cmdPrefix == "" {
			flagPidName = "Pid"
		} else {
			flagPidName = fmt.Sprintf("%v.Pid", cmdPrefix)
		}

		flagPidValue, err := cmd.Flags().GetInt64(flagPidName)
		if err != nil {
			return err, false
		}
		m.Pid = flagPidValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropRestartingFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRestartingName := fmt.Sprintf("%v.Restarting", cmdPrefix)
	if cmd.Flags().Changed(flagRestartingName) {

		var flagRestartingName string
		if cmdPrefix == "" {
			flagRestartingName = "Restarting"
		} else {
			flagRestartingName = fmt.Sprintf("%v.Restarting", cmdPrefix)
		}

		flagRestartingValue, err := cmd.Flags().GetBool(flagRestartingName)
		if err != nil {
			return err, false
		}
		m.Restarting = flagRestartingValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropRunningFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRunningName := fmt.Sprintf("%v.Running", cmdPrefix)
	if cmd.Flags().Changed(flagRunningName) {

		var flagRunningName string
		if cmdPrefix == "" {
			flagRunningName = "Running"
		} else {
			flagRunningName = fmt.Sprintf("%v.Running", cmdPrefix)
		}

		flagRunningValue, err := cmd.Flags().GetBool(flagRunningName)
		if err != nil {
			return err, false
		}
		m.Running = flagRunningValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropStartedAtFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStartedAtName := fmt.Sprintf("%v.StartedAt", cmdPrefix)
	if cmd.Flags().Changed(flagStartedAtName) {

		var flagStartedAtName string
		if cmdPrefix == "" {
			flagStartedAtName = "StartedAt"
		} else {
			flagStartedAtName = fmt.Sprintf("%v.StartedAt", cmdPrefix)
		}

		flagStartedAtValue, err := cmd.Flags().GetString(flagStartedAtName)
		if err != nil {
			return err, false
		}
		m.StartedAt = flagStartedAtValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveContainerInspectOKBodyStatePropStatusFlags(depth int, m *container.ContainerInspectOKBodyState, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStatusName := fmt.Sprintf("%v.Status", cmdPrefix)
	if cmd.Flags().Changed(flagStatusName) {

		var flagStatusName string
		if cmdPrefix == "" {
			flagStatusName = "Status"
		} else {
			flagStatusName = fmt.Sprintf("%v.Status", cmdPrefix)
		}

		flagStatusValue, err := cmd.Flags().GetString(flagStatusName)
		if err != nil {
			return err, false
		}
		m.Status = flagStatusValue

		retAdded = true
	}

	return nil, retAdded
}
