// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for DeviceRequest

// register flags to command
func registerModelDeviceRequestFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerDeviceRequestPropCapabilities(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDeviceRequestPropCount(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDeviceRequestPropDeviceIDs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDeviceRequestPropDriver(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDeviceRequestPropOptions(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerDeviceRequestPropCapabilities(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Capabilities [][]string array type is not supported by go-swagger cli yet

	return nil
}

func registerDeviceRequestPropCount(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCountDescription := ``

	var flagCountName string
	if cmdPrefix == "" {
		flagCountName = "Count"
	} else {
		flagCountName = fmt.Sprintf("%v.Count", cmdPrefix)
	}

	var flagCountDefault int64

	_ = cmd.PersistentFlags().Int64(flagCountName, flagCountDefault, flagCountDescription)

	return nil
}

func registerDeviceRequestPropDeviceIDs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: DeviceIDs []string array type is not supported by go-swagger cli yet

	return nil
}

func registerDeviceRequestPropDriver(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDriverDescription := ``

	var flagDriverName string
	if cmdPrefix == "" {
		flagDriverName = "Driver"
	} else {
		flagDriverName = fmt.Sprintf("%v.Driver", cmdPrefix)
	}

	var flagDriverDefault string

	_ = cmd.PersistentFlags().String(flagDriverName, flagDriverDefault, flagDriverDescription)

	return nil
}

func registerDeviceRequestPropOptions(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Options map[string]string map type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelDeviceRequestFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CapabilitiesAdded := retrieveDeviceRequestPropCapabilitiesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CapabilitiesAdded

	err, CountAdded := retrieveDeviceRequestPropCountFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CountAdded

	err, DeviceIDsAdded := retrieveDeviceRequestPropDeviceIDsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DeviceIDsAdded

	err, DriverAdded := retrieveDeviceRequestPropDriverFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DriverAdded

	err, OptionsAdded := retrieveDeviceRequestPropOptionsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || OptionsAdded

	return nil, retAdded
}

func retrieveDeviceRequestPropCapabilitiesFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCapabilitiesName := fmt.Sprintf("%v.Capabilities", cmdPrefix)
	if cmd.Flags().Changed(flagCapabilitiesName) {
		// warning: Capabilities array type [][]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDeviceRequestPropCountFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCountName := fmt.Sprintf("%v.Count", cmdPrefix)
	if cmd.Flags().Changed(flagCountName) {

		var flagCountName string
		if cmdPrefix == "" {
			flagCountName = "Count"
		} else {
			flagCountName = fmt.Sprintf("%v.Count", cmdPrefix)
		}

		flagCountValue, err := cmd.Flags().GetInt64(flagCountName)
		if err != nil {
			return err, false
		}
		m.Count = flagCountValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDeviceRequestPropDeviceIDsFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDeviceIDsName := fmt.Sprintf("%v.DeviceIDs", cmdPrefix)
	if cmd.Flags().Changed(flagDeviceIDsName) {
		// warning: DeviceIDs array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDeviceRequestPropDriverFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDriverName := fmt.Sprintf("%v.Driver", cmdPrefix)
	if cmd.Flags().Changed(flagDriverName) {

		var flagDriverName string
		if cmdPrefix == "" {
			flagDriverName = "Driver"
		} else {
			flagDriverName = fmt.Sprintf("%v.Driver", cmdPrefix)
		}

		flagDriverValue, err := cmd.Flags().GetString(flagDriverName)
		if err != nil {
			return err, false
		}
		m.Driver = flagDriverValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDeviceRequestPropOptionsFlags(depth int, m *models.DeviceRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagOptionsName := fmt.Sprintf("%v.Options", cmdPrefix)
	if cmd.Flags().Changed(flagOptionsName) {
		// warning: Options map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
