// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for EndpointSettings

// register flags to command
func registerModelEndpointSettingsFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerEndpointSettingsPropAliases(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropDriverOpts(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropEndpointID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropGateway(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropGlobalIPV6Address(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropGlobalIPV6PrefixLen(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropIPAMConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropIPAddress(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropIPPrefixLen(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropIPV6Gateway(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropLinks(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropMacAddress(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEndpointSettingsPropNetworkID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerEndpointSettingsPropAliases(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Aliases []string array type is not supported by go-swagger cli yet

	return nil
}

func registerEndpointSettingsPropDriverOpts(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: DriverOpts map[string]string map type is not supported by go-swagger cli yet

	return nil
}

func registerEndpointSettingsPropEndpointID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEndpointIDDescription := `Unique ID for the service endpoint in a Sandbox.
`

	var flagEndpointIDName string
	if cmdPrefix == "" {
		flagEndpointIDName = "EndpointID"
	} else {
		flagEndpointIDName = fmt.Sprintf("%v.EndpointID", cmdPrefix)
	}

	var flagEndpointIDDefault string

	_ = cmd.PersistentFlags().String(flagEndpointIDName, flagEndpointIDDefault, flagEndpointIDDescription)

	return nil
}

func registerEndpointSettingsPropGateway(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagGatewayDescription := `Gateway address for this network.
`

	var flagGatewayName string
	if cmdPrefix == "" {
		flagGatewayName = "Gateway"
	} else {
		flagGatewayName = fmt.Sprintf("%v.Gateway", cmdPrefix)
	}

	var flagGatewayDefault string

	_ = cmd.PersistentFlags().String(flagGatewayName, flagGatewayDefault, flagGatewayDescription)

	return nil
}

func registerEndpointSettingsPropGlobalIPV6Address(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagGlobalIPV6AddressDescription := `Global IPv6 address.
`

	var flagGlobalIPV6AddressName string
	if cmdPrefix == "" {
		flagGlobalIPV6AddressName = "GlobalIPv6Address"
	} else {
		flagGlobalIPV6AddressName = fmt.Sprintf("%v.GlobalIPv6Address", cmdPrefix)
	}

	var flagGlobalIPV6AddressDefault string

	_ = cmd.PersistentFlags().String(flagGlobalIPV6AddressName, flagGlobalIPV6AddressDefault, flagGlobalIPV6AddressDescription)

	return nil
}

func registerEndpointSettingsPropGlobalIPV6PrefixLen(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagGlobalIPV6PrefixLenDescription := `Mask length of the global IPv6 address.
`

	var flagGlobalIPV6PrefixLenName string
	if cmdPrefix == "" {
		flagGlobalIPV6PrefixLenName = "GlobalIPv6PrefixLen"
	} else {
		flagGlobalIPV6PrefixLenName = fmt.Sprintf("%v.GlobalIPv6PrefixLen", cmdPrefix)
	}

	var flagGlobalIPV6PrefixLenDefault int64

	_ = cmd.PersistentFlags().Int64(flagGlobalIPV6PrefixLenName, flagGlobalIPV6PrefixLenDefault, flagGlobalIPV6PrefixLenDescription)

	return nil
}

func registerEndpointSettingsPropIPAMConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagIPAMConfigName string
	if cmdPrefix == "" {
		flagIPAMConfigName = "IPAMConfig"
	} else {
		flagIPAMConfigName = fmt.Sprintf("%v.IPAMConfig", cmdPrefix)
	}

	if err := registerModelEndpointIPAMConfigFlags(depth+1, flagIPAMConfigName, cmd); err != nil {
		return err
	}

	return nil
}

func registerEndpointSettingsPropIPAddress(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIPAddressDescription := `IPv4 address.
`

	var flagIPAddressName string
	if cmdPrefix == "" {
		flagIPAddressName = "IPAddress"
	} else {
		flagIPAddressName = fmt.Sprintf("%v.IPAddress", cmdPrefix)
	}

	var flagIPAddressDefault string

	_ = cmd.PersistentFlags().String(flagIPAddressName, flagIPAddressDefault, flagIPAddressDescription)

	return nil
}

func registerEndpointSettingsPropIPPrefixLen(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIPPrefixLenDescription := `Mask length of the IPv4 address.
`

	var flagIPPrefixLenName string
	if cmdPrefix == "" {
		flagIPPrefixLenName = "IPPrefixLen"
	} else {
		flagIPPrefixLenName = fmt.Sprintf("%v.IPPrefixLen", cmdPrefix)
	}

	var flagIPPrefixLenDefault int64

	_ = cmd.PersistentFlags().Int64(flagIPPrefixLenName, flagIPPrefixLenDefault, flagIPPrefixLenDescription)

	return nil
}

func registerEndpointSettingsPropIPV6Gateway(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIPV6GatewayDescription := `IPv6 gateway address.
`

	var flagIPV6GatewayName string
	if cmdPrefix == "" {
		flagIPV6GatewayName = "IPv6Gateway"
	} else {
		flagIPV6GatewayName = fmt.Sprintf("%v.IPv6Gateway", cmdPrefix)
	}

	var flagIPV6GatewayDefault string

	_ = cmd.PersistentFlags().String(flagIPV6GatewayName, flagIPV6GatewayDefault, flagIPV6GatewayDescription)

	return nil
}

func registerEndpointSettingsPropLinks(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Links []string array type is not supported by go-swagger cli yet

	return nil
}

func registerEndpointSettingsPropMacAddress(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMacAddressDescription := `MAC address for the endpoint on this network.
`

	var flagMacAddressName string
	if cmdPrefix == "" {
		flagMacAddressName = "MacAddress"
	} else {
		flagMacAddressName = fmt.Sprintf("%v.MacAddress", cmdPrefix)
	}

	var flagMacAddressDefault string

	_ = cmd.PersistentFlags().String(flagMacAddressName, flagMacAddressDefault, flagMacAddressDescription)

	return nil
}

func registerEndpointSettingsPropNetworkID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNetworkIDDescription := `Unique ID of the network.
`

	var flagNetworkIDName string
	if cmdPrefix == "" {
		flagNetworkIDName = "NetworkID"
	} else {
		flagNetworkIDName = fmt.Sprintf("%v.NetworkID", cmdPrefix)
	}

	var flagNetworkIDDefault string

	_ = cmd.PersistentFlags().String(flagNetworkIDName, flagNetworkIDDefault, flagNetworkIDDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelEndpointSettingsFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AliasesAdded := retrieveEndpointSettingsPropAliasesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AliasesAdded

	err, DriverOptsAdded := retrieveEndpointSettingsPropDriverOptsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DriverOptsAdded

	err, EndpointIDAdded := retrieveEndpointSettingsPropEndpointIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EndpointIDAdded

	err, GatewayAdded := retrieveEndpointSettingsPropGatewayFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GatewayAdded

	err, GlobalIPV6AddressAdded := retrieveEndpointSettingsPropGlobalIPV6AddressFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GlobalIPV6AddressAdded

	err, GlobalIPV6PrefixLenAdded := retrieveEndpointSettingsPropGlobalIPV6PrefixLenFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GlobalIPV6PrefixLenAdded

	err, IPAMConfigAdded := retrieveEndpointSettingsPropIPAMConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPAMConfigAdded

	err, IPAddressAdded := retrieveEndpointSettingsPropIPAddressFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPAddressAdded

	err, IPPrefixLenAdded := retrieveEndpointSettingsPropIPPrefixLenFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPPrefixLenAdded

	err, IPV6GatewayAdded := retrieveEndpointSettingsPropIPV6GatewayFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPV6GatewayAdded

	err, LinksAdded := retrieveEndpointSettingsPropLinksFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LinksAdded

	err, MacAddressAdded := retrieveEndpointSettingsPropMacAddressFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MacAddressAdded

	err, NetworkIDAdded := retrieveEndpointSettingsPropNetworkIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NetworkIDAdded

	return nil, retAdded
}

func retrieveEndpointSettingsPropAliasesFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAliasesName := fmt.Sprintf("%v.Aliases", cmdPrefix)
	if cmd.Flags().Changed(flagAliasesName) {
		// warning: Aliases array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropDriverOptsFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDriverOptsName := fmt.Sprintf("%v.DriverOpts", cmdPrefix)
	if cmd.Flags().Changed(flagDriverOptsName) {
		// warning: DriverOpts map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropEndpointIDFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEndpointIDName := fmt.Sprintf("%v.EndpointID", cmdPrefix)
	if cmd.Flags().Changed(flagEndpointIDName) {

		var flagEndpointIDName string
		if cmdPrefix == "" {
			flagEndpointIDName = "EndpointID"
		} else {
			flagEndpointIDName = fmt.Sprintf("%v.EndpointID", cmdPrefix)
		}

		flagEndpointIDValue, err := cmd.Flags().GetString(flagEndpointIDName)
		if err != nil {
			return err, false
		}
		m.EndpointID = flagEndpointIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropGatewayFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagGatewayName := fmt.Sprintf("%v.Gateway", cmdPrefix)
	if cmd.Flags().Changed(flagGatewayName) {

		var flagGatewayName string
		if cmdPrefix == "" {
			flagGatewayName = "Gateway"
		} else {
			flagGatewayName = fmt.Sprintf("%v.Gateway", cmdPrefix)
		}

		flagGatewayValue, err := cmd.Flags().GetString(flagGatewayName)
		if err != nil {
			return err, false
		}
		m.Gateway = flagGatewayValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropGlobalIPV6AddressFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagGlobalIPV6AddressName := fmt.Sprintf("%v.GlobalIPv6Address", cmdPrefix)
	if cmd.Flags().Changed(flagGlobalIPV6AddressName) {

		var flagGlobalIPV6AddressName string
		if cmdPrefix == "" {
			flagGlobalIPV6AddressName = "GlobalIPv6Address"
		} else {
			flagGlobalIPV6AddressName = fmt.Sprintf("%v.GlobalIPv6Address", cmdPrefix)
		}

		flagGlobalIPV6AddressValue, err := cmd.Flags().GetString(flagGlobalIPV6AddressName)
		if err != nil {
			return err, false
		}
		m.GlobalIPV6Address = flagGlobalIPV6AddressValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropGlobalIPV6PrefixLenFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagGlobalIPV6PrefixLenName := fmt.Sprintf("%v.GlobalIPv6PrefixLen", cmdPrefix)
	if cmd.Flags().Changed(flagGlobalIPV6PrefixLenName) {

		var flagGlobalIPV6PrefixLenName string
		if cmdPrefix == "" {
			flagGlobalIPV6PrefixLenName = "GlobalIPv6PrefixLen"
		} else {
			flagGlobalIPV6PrefixLenName = fmt.Sprintf("%v.GlobalIPv6PrefixLen", cmdPrefix)
		}

		flagGlobalIPV6PrefixLenValue, err := cmd.Flags().GetInt64(flagGlobalIPV6PrefixLenName)
		if err != nil {
			return err, false
		}
		m.GlobalIPV6PrefixLen = flagGlobalIPV6PrefixLenValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropIPAMConfigFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIPAMConfigName := fmt.Sprintf("%v.IPAMConfig", cmdPrefix)
	if cmd.Flags().Changed(flagIPAMConfigName) {
		// info: complex object IPAMConfig EndpointIPAMConfig is retrieved outside this Changed() block
	}
	flagIPAMConfigValue := m.IPAMConfig
	if swag.IsZero(flagIPAMConfigValue) {
		flagIPAMConfigValue = &models.EndpointIPAMConfig{}
	}

	err, IPAMConfigAdded := retrieveModelEndpointIPAMConfigFlags(depth+1, flagIPAMConfigValue, flagIPAMConfigName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPAMConfigAdded
	if IPAMConfigAdded {
		m.IPAMConfig = flagIPAMConfigValue
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropIPAddressFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIPAddressName := fmt.Sprintf("%v.IPAddress", cmdPrefix)
	if cmd.Flags().Changed(flagIPAddressName) {

		var flagIPAddressName string
		if cmdPrefix == "" {
			flagIPAddressName = "IPAddress"
		} else {
			flagIPAddressName = fmt.Sprintf("%v.IPAddress", cmdPrefix)
		}

		flagIPAddressValue, err := cmd.Flags().GetString(flagIPAddressName)
		if err != nil {
			return err, false
		}
		m.IPAddress = flagIPAddressValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropIPPrefixLenFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIPPrefixLenName := fmt.Sprintf("%v.IPPrefixLen", cmdPrefix)
	if cmd.Flags().Changed(flagIPPrefixLenName) {

		var flagIPPrefixLenName string
		if cmdPrefix == "" {
			flagIPPrefixLenName = "IPPrefixLen"
		} else {
			flagIPPrefixLenName = fmt.Sprintf("%v.IPPrefixLen", cmdPrefix)
		}

		flagIPPrefixLenValue, err := cmd.Flags().GetInt64(flagIPPrefixLenName)
		if err != nil {
			return err, false
		}
		m.IPPrefixLen = flagIPPrefixLenValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropIPV6GatewayFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIPV6GatewayName := fmt.Sprintf("%v.IPv6Gateway", cmdPrefix)
	if cmd.Flags().Changed(flagIPV6GatewayName) {

		var flagIPV6GatewayName string
		if cmdPrefix == "" {
			flagIPV6GatewayName = "IPv6Gateway"
		} else {
			flagIPV6GatewayName = fmt.Sprintf("%v.IPv6Gateway", cmdPrefix)
		}

		flagIPV6GatewayValue, err := cmd.Flags().GetString(flagIPV6GatewayName)
		if err != nil {
			return err, false
		}
		m.IPV6Gateway = flagIPV6GatewayValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropLinksFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLinksName := fmt.Sprintf("%v.Links", cmdPrefix)
	if cmd.Flags().Changed(flagLinksName) {
		// warning: Links array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropMacAddressFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMacAddressName := fmt.Sprintf("%v.MacAddress", cmdPrefix)
	if cmd.Flags().Changed(flagMacAddressName) {

		var flagMacAddressName string
		if cmdPrefix == "" {
			flagMacAddressName = "MacAddress"
		} else {
			flagMacAddressName = fmt.Sprintf("%v.MacAddress", cmdPrefix)
		}

		flagMacAddressValue, err := cmd.Flags().GetString(flagMacAddressName)
		if err != nil {
			return err, false
		}
		m.MacAddress = flagMacAddressValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEndpointSettingsPropNetworkIDFlags(depth int, m *models.EndpointSettings, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNetworkIDName := fmt.Sprintf("%v.NetworkID", cmdPrefix)
	if cmd.Flags().Changed(flagNetworkIDName) {

		var flagNetworkIDName string
		if cmdPrefix == "" {
			flagNetworkIDName = "NetworkID"
		} else {
			flagNetworkIDName = fmt.Sprintf("%v.NetworkID", cmdPrefix)
		}

		flagNetworkIDValue, err := cmd.Flags().GetString(flagNetworkIDName)
		if err != nil {
			return err, false
		}
		m.NetworkID = flagNetworkIDValue

		retAdded = true
	}

	return nil, retAdded
}
