// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for EngineDescription

// register flags to command
func registerModelEngineDescriptionFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerEngineDescriptionPropEngineVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEngineDescriptionPropLabels(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEngineDescriptionPropPlugins(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerEngineDescriptionPropEngineVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagEngineVersionDescription := ``

	var flagEngineVersionName string
	if cmdPrefix == "" {
		flagEngineVersionName = "EngineVersion"
	} else {
		flagEngineVersionName = fmt.Sprintf("%v.EngineVersion", cmdPrefix)
	}

	var flagEngineVersionDefault string

	_ = cmd.PersistentFlags().String(flagEngineVersionName, flagEngineVersionDefault, flagEngineVersionDescription)

	return nil
}

func registerEngineDescriptionPropLabels(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Labels map[string]string map type is not supported by go-swagger cli yet

	return nil
}

func registerEngineDescriptionPropPlugins(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Plugins []*EngineDescriptionPluginsItems0 array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelEngineDescriptionFlags(depth int, m *models.EngineDescription, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, EngineVersionAdded := retrieveEngineDescriptionPropEngineVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || EngineVersionAdded

	err, LabelsAdded := retrieveEngineDescriptionPropLabelsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LabelsAdded

	err, PluginsAdded := retrieveEngineDescriptionPropPluginsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PluginsAdded

	return nil, retAdded
}

func retrieveEngineDescriptionPropEngineVersionFlags(depth int, m *models.EngineDescription, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagEngineVersionName := fmt.Sprintf("%v.EngineVersion", cmdPrefix)
	if cmd.Flags().Changed(flagEngineVersionName) {

		var flagEngineVersionName string
		if cmdPrefix == "" {
			flagEngineVersionName = "EngineVersion"
		} else {
			flagEngineVersionName = fmt.Sprintf("%v.EngineVersion", cmdPrefix)
		}

		flagEngineVersionValue, err := cmd.Flags().GetString(flagEngineVersionName)
		if err != nil {
			return err, false
		}
		m.EngineVersion = flagEngineVersionValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEngineDescriptionPropLabelsFlags(depth int, m *models.EngineDescription, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLabelsName := fmt.Sprintf("%v.Labels", cmdPrefix)
	if cmd.Flags().Changed(flagLabelsName) {
		// warning: Labels map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveEngineDescriptionPropPluginsFlags(depth int, m *models.EngineDescription, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPluginsName := fmt.Sprintf("%v.Plugins", cmdPrefix)
	if cmd.Flags().Changed(flagPluginsName) {
		// warning: Plugins array type []*EngineDescriptionPluginsItems0 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

// Extra schema cli for EngineDescriptionPluginsItems0

// register flags to command
func registerModelEngineDescriptionPluginsItems0Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerEngineDescriptionPluginsItems0PropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerEngineDescriptionPluginsItems0PropType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerEngineDescriptionPluginsItems0PropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := ``

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "Name"
	} else {
		flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerEngineDescriptionPluginsItems0PropType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTypeDescription := ``

	var flagTypeName string
	if cmdPrefix == "" {
		flagTypeName = "Type"
	} else {
		flagTypeName = fmt.Sprintf("%v.Type", cmdPrefix)
	}

	var flagTypeDefault string

	_ = cmd.PersistentFlags().String(flagTypeName, flagTypeDefault, flagTypeDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelEngineDescriptionPluginsItems0Flags(depth int, m *models.EngineDescriptionPluginsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, NameAdded := retrieveEngineDescriptionPluginsItems0PropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, TypeAdded := retrieveEngineDescriptionPluginsItems0PropTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TypeAdded

	return nil, retAdded
}

func retrieveEngineDescriptionPluginsItems0PropNameFlags(depth int, m *models.EngineDescriptionPluginsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.Name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "Name"
		} else {
			flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveEngineDescriptionPluginsItems0PropTypeFlags(depth int, m *models.EngineDescriptionPluginsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTypeName := fmt.Sprintf("%v.Type", cmdPrefix)
	if cmd.Flags().Changed(flagTypeName) {

		var flagTypeName string
		if cmdPrefix == "" {
			flagTypeName = "Type"
		} else {
			flagTypeName = fmt.Sprintf("%v.Type", cmdPrefix)
		}

		flagTypeValue, err := cmd.Flags().GetString(flagTypeName)
		if err != nil {
			return err, false
		}
		m.Type = flagTypeValue

		retAdded = true
	}

	return nil, retAdded
}
