// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for []*GenericResourcesItems0

// Name: [GenericResources], Type:[[]*GenericResourcesItems0], register and retrieve functions are not rendered by go-swagger cli

// Extra schema cli for GenericResourcesItems0

// register flags to command
func registerModelGenericResourcesItems0Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGenericResourcesItems0PropDiscreteResourceSpec(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGenericResourcesItems0PropNamedResourceSpec(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGenericResourcesItems0PropDiscreteResourceSpec(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagDiscreteResourceSpecName string
	if cmdPrefix == "" {
		flagDiscreteResourceSpecName = "DiscreteResourceSpec"
	} else {
		flagDiscreteResourceSpecName = fmt.Sprintf("%v.DiscreteResourceSpec", cmdPrefix)
	}

	if err := registerModelGenericResourcesItems0DiscreteResourceSpecFlags(depth+1, flagDiscreteResourceSpecName, cmd); err != nil {
		return err
	}

	return nil
}

func registerGenericResourcesItems0PropNamedResourceSpec(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagNamedResourceSpecName string
	if cmdPrefix == "" {
		flagNamedResourceSpecName = "NamedResourceSpec"
	} else {
		flagNamedResourceSpecName = fmt.Sprintf("%v.NamedResourceSpec", cmdPrefix)
	}

	if err := registerModelGenericResourcesItems0NamedResourceSpecFlags(depth+1, flagNamedResourceSpecName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGenericResourcesItems0Flags(depth int, m *models.GenericResourcesItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, DiscreteResourceSpecAdded := retrieveGenericResourcesItems0PropDiscreteResourceSpecFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DiscreteResourceSpecAdded

	err, NamedResourceSpecAdded := retrieveGenericResourcesItems0PropNamedResourceSpecFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NamedResourceSpecAdded

	return nil, retAdded
}

func retrieveGenericResourcesItems0PropDiscreteResourceSpecFlags(depth int, m *models.GenericResourcesItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDiscreteResourceSpecName := fmt.Sprintf("%v.DiscreteResourceSpec", cmdPrefix)
	if cmd.Flags().Changed(flagDiscreteResourceSpecName) {
		// info: complex object DiscreteResourceSpec GenericResourcesItems0DiscreteResourceSpec is retrieved outside this Changed() block
	}
	flagDiscreteResourceSpecValue := m.DiscreteResourceSpec
	if swag.IsZero(flagDiscreteResourceSpecValue) {
		flagDiscreteResourceSpecValue = &models.GenericResourcesItems0DiscreteResourceSpec{}
	}

	err, DiscreteResourceSpecAdded := retrieveModelGenericResourcesItems0DiscreteResourceSpecFlags(depth+1, flagDiscreteResourceSpecValue, flagDiscreteResourceSpecName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DiscreteResourceSpecAdded
	if DiscreteResourceSpecAdded {
		m.DiscreteResourceSpec = flagDiscreteResourceSpecValue
	}

	return nil, retAdded
}

func retrieveGenericResourcesItems0PropNamedResourceSpecFlags(depth int, m *models.GenericResourcesItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNamedResourceSpecName := fmt.Sprintf("%v.NamedResourceSpec", cmdPrefix)
	if cmd.Flags().Changed(flagNamedResourceSpecName) {
		// info: complex object NamedResourceSpec GenericResourcesItems0NamedResourceSpec is retrieved outside this Changed() block
	}
	flagNamedResourceSpecValue := m.NamedResourceSpec
	if swag.IsZero(flagNamedResourceSpecValue) {
		flagNamedResourceSpecValue = &models.GenericResourcesItems0NamedResourceSpec{}
	}

	err, NamedResourceSpecAdded := retrieveModelGenericResourcesItems0NamedResourceSpecFlags(depth+1, flagNamedResourceSpecValue, flagNamedResourceSpecName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NamedResourceSpecAdded
	if NamedResourceSpecAdded {
		m.NamedResourceSpec = flagNamedResourceSpecValue
	}

	return nil, retAdded
}

// Extra schema cli for GenericResourcesItems0DiscreteResourceSpec

// register flags to command
func registerModelGenericResourcesItems0DiscreteResourceSpecFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGenericResourcesItems0DiscreteResourceSpecPropKind(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGenericResourcesItems0DiscreteResourceSpecPropValue(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGenericResourcesItems0DiscreteResourceSpecPropKind(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagKindDescription := ``

	var flagKindName string
	if cmdPrefix == "" {
		flagKindName = "Kind"
	} else {
		flagKindName = fmt.Sprintf("%v.Kind", cmdPrefix)
	}

	var flagKindDefault string

	_ = cmd.PersistentFlags().String(flagKindName, flagKindDefault, flagKindDescription)

	return nil
}

func registerGenericResourcesItems0DiscreteResourceSpecPropValue(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagValueDescription := ``

	var flagValueName string
	if cmdPrefix == "" {
		flagValueName = "Value"
	} else {
		flagValueName = fmt.Sprintf("%v.Value", cmdPrefix)
	}

	var flagValueDefault int64

	_ = cmd.PersistentFlags().Int64(flagValueName, flagValueDefault, flagValueDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGenericResourcesItems0DiscreteResourceSpecFlags(depth int, m *models.GenericResourcesItems0DiscreteResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, KindAdded := retrieveGenericResourcesItems0DiscreteResourceSpecPropKindFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || KindAdded

	err, ValueAdded := retrieveGenericResourcesItems0DiscreteResourceSpecPropValueFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ValueAdded

	return nil, retAdded
}

func retrieveGenericResourcesItems0DiscreteResourceSpecPropKindFlags(depth int, m *models.GenericResourcesItems0DiscreteResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagKindName := fmt.Sprintf("%v.Kind", cmdPrefix)
	if cmd.Flags().Changed(flagKindName) {

		var flagKindName string
		if cmdPrefix == "" {
			flagKindName = "Kind"
		} else {
			flagKindName = fmt.Sprintf("%v.Kind", cmdPrefix)
		}

		flagKindValue, err := cmd.Flags().GetString(flagKindName)
		if err != nil {
			return err, false
		}
		m.Kind = flagKindValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveGenericResourcesItems0DiscreteResourceSpecPropValueFlags(depth int, m *models.GenericResourcesItems0DiscreteResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagValueName := fmt.Sprintf("%v.Value", cmdPrefix)
	if cmd.Flags().Changed(flagValueName) {

		var flagValueName string
		if cmdPrefix == "" {
			flagValueName = "Value"
		} else {
			flagValueName = fmt.Sprintf("%v.Value", cmdPrefix)
		}

		flagValueValue, err := cmd.Flags().GetInt64(flagValueName)
		if err != nil {
			return err, false
		}
		m.Value = flagValueValue

		retAdded = true
	}

	return nil, retAdded
}

// Extra schema cli for GenericResourcesItems0NamedResourceSpec

// register flags to command
func registerModelGenericResourcesItems0NamedResourceSpecFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerGenericResourcesItems0NamedResourceSpecPropKind(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGenericResourcesItems0NamedResourceSpecPropValue(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerGenericResourcesItems0NamedResourceSpecPropKind(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagKindDescription := ``

	var flagKindName string
	if cmdPrefix == "" {
		flagKindName = "Kind"
	} else {
		flagKindName = fmt.Sprintf("%v.Kind", cmdPrefix)
	}

	var flagKindDefault string

	_ = cmd.PersistentFlags().String(flagKindName, flagKindDefault, flagKindDescription)

	return nil
}

func registerGenericResourcesItems0NamedResourceSpecPropValue(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagValueDescription := ``

	var flagValueName string
	if cmdPrefix == "" {
		flagValueName = "Value"
	} else {
		flagValueName = fmt.Sprintf("%v.Value", cmdPrefix)
	}

	var flagValueDefault string

	_ = cmd.PersistentFlags().String(flagValueName, flagValueDefault, flagValueDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGenericResourcesItems0NamedResourceSpecFlags(depth int, m *models.GenericResourcesItems0NamedResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, KindAdded := retrieveGenericResourcesItems0NamedResourceSpecPropKindFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || KindAdded

	err, ValueAdded := retrieveGenericResourcesItems0NamedResourceSpecPropValueFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ValueAdded

	return nil, retAdded
}

func retrieveGenericResourcesItems0NamedResourceSpecPropKindFlags(depth int, m *models.GenericResourcesItems0NamedResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagKindName := fmt.Sprintf("%v.Kind", cmdPrefix)
	if cmd.Flags().Changed(flagKindName) {

		var flagKindName string
		if cmdPrefix == "" {
			flagKindName = "Kind"
		} else {
			flagKindName = fmt.Sprintf("%v.Kind", cmdPrefix)
		}

		flagKindValue, err := cmd.Flags().GetString(flagKindName)
		if err != nil {
			return err, false
		}
		m.Kind = flagKindValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveGenericResourcesItems0NamedResourceSpecPropValueFlags(depth int, m *models.GenericResourcesItems0NamedResourceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagValueName := fmt.Sprintf("%v.Value", cmdPrefix)
	if cmd.Flags().Changed(flagValueName) {

		var flagValueName string
		if cmdPrefix == "" {
			flagValueName = "Value"
		} else {
			flagValueName = fmt.Sprintf("%v.Value", cmdPrefix)
		}

		flagValueValue, err := cmd.Flags().GetString(flagValueName)
		if err != nil {
			return err, false
		}
		m.Value = flagValueValue

		retAdded = true
	}

	return nil, retAdded
}
