// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for HealthConfig

// register flags to command
func registerModelHealthConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerHealthConfigPropInterval(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerHealthConfigPropRetries(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerHealthConfigPropStartPeriod(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerHealthConfigPropTest(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerHealthConfigPropTimeout(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerHealthConfigPropInterval(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIntervalDescription := `The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.`

	var flagIntervalName string
	if cmdPrefix == "" {
		flagIntervalName = "Interval"
	} else {
		flagIntervalName = fmt.Sprintf("%v.Interval", cmdPrefix)
	}

	var flagIntervalDefault int64

	_ = cmd.PersistentFlags().Int64(flagIntervalName, flagIntervalDefault, flagIntervalDescription)

	return nil
}

func registerHealthConfigPropRetries(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRetriesDescription := `The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.`

	var flagRetriesName string
	if cmdPrefix == "" {
		flagRetriesName = "Retries"
	} else {
		flagRetriesName = fmt.Sprintf("%v.Retries", cmdPrefix)
	}

	var flagRetriesDefault int64

	_ = cmd.PersistentFlags().Int64(flagRetriesName, flagRetriesDefault, flagRetriesDescription)

	return nil
}

func registerHealthConfigPropStartPeriod(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStartPeriodDescription := `Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.`

	var flagStartPeriodName string
	if cmdPrefix == "" {
		flagStartPeriodName = "StartPeriod"
	} else {
		flagStartPeriodName = fmt.Sprintf("%v.StartPeriod", cmdPrefix)
	}

	var flagStartPeriodDefault int64

	_ = cmd.PersistentFlags().Int64(flagStartPeriodName, flagStartPeriodDefault, flagStartPeriodDescription)

	return nil
}

func registerHealthConfigPropTest(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Test []string array type is not supported by go-swagger cli yet

	return nil
}

func registerHealthConfigPropTimeout(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTimeoutDescription := `The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.`

	var flagTimeoutName string
	if cmdPrefix == "" {
		flagTimeoutName = "Timeout"
	} else {
		flagTimeoutName = fmt.Sprintf("%v.Timeout", cmdPrefix)
	}

	var flagTimeoutDefault int64

	_ = cmd.PersistentFlags().Int64(flagTimeoutName, flagTimeoutDefault, flagTimeoutDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelHealthConfigFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IntervalAdded := retrieveHealthConfigPropIntervalFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IntervalAdded

	err, RetriesAdded := retrieveHealthConfigPropRetriesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RetriesAdded

	err, StartPeriodAdded := retrieveHealthConfigPropStartPeriodFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StartPeriodAdded

	err, TestAdded := retrieveHealthConfigPropTestFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TestAdded

	err, TimeoutAdded := retrieveHealthConfigPropTimeoutFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TimeoutAdded

	return nil, retAdded
}

func retrieveHealthConfigPropIntervalFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIntervalName := fmt.Sprintf("%v.Interval", cmdPrefix)
	if cmd.Flags().Changed(flagIntervalName) {

		var flagIntervalName string
		if cmdPrefix == "" {
			flagIntervalName = "Interval"
		} else {
			flagIntervalName = fmt.Sprintf("%v.Interval", cmdPrefix)
		}

		flagIntervalValue, err := cmd.Flags().GetInt64(flagIntervalName)
		if err != nil {
			return err, false
		}
		m.Interval = flagIntervalValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveHealthConfigPropRetriesFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRetriesName := fmt.Sprintf("%v.Retries", cmdPrefix)
	if cmd.Flags().Changed(flagRetriesName) {

		var flagRetriesName string
		if cmdPrefix == "" {
			flagRetriesName = "Retries"
		} else {
			flagRetriesName = fmt.Sprintf("%v.Retries", cmdPrefix)
		}

		flagRetriesValue, err := cmd.Flags().GetInt64(flagRetriesName)
		if err != nil {
			return err, false
		}
		m.Retries = flagRetriesValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveHealthConfigPropStartPeriodFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStartPeriodName := fmt.Sprintf("%v.StartPeriod", cmdPrefix)
	if cmd.Flags().Changed(flagStartPeriodName) {

		var flagStartPeriodName string
		if cmdPrefix == "" {
			flagStartPeriodName = "StartPeriod"
		} else {
			flagStartPeriodName = fmt.Sprintf("%v.StartPeriod", cmdPrefix)
		}

		flagStartPeriodValue, err := cmd.Flags().GetInt64(flagStartPeriodName)
		if err != nil {
			return err, false
		}
		m.StartPeriod = flagStartPeriodValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveHealthConfigPropTestFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTestName := fmt.Sprintf("%v.Test", cmdPrefix)
	if cmd.Flags().Changed(flagTestName) {
		// warning: Test array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveHealthConfigPropTimeoutFlags(depth int, m *models.HealthConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTimeoutName := fmt.Sprintf("%v.Timeout", cmdPrefix)
	if cmd.Flags().Changed(flagTimeoutName) {

		var flagTimeoutName string
		if cmdPrefix == "" {
			flagTimeoutName = "Timeout"
		} else {
			flagTimeoutName = fmt.Sprintf("%v.Timeout", cmdPrefix)
		}

		flagTimeoutValue, err := cmd.Flags().GetInt64(flagTimeoutName)
		if err != nil {
			return err, false
		}
		m.Timeout = flagTimeoutValue

		retAdded = true
	}

	return nil, retAdded
}
