// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/image"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationImageImagePushCmd returns a command to handle operation imagePush
func makeOperationImageImagePushCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "ImagePush",
		Short: `Push an image to a registry.

If you wish to push an image on to a private registry, that image must already have a tag which references the registry. For example, ` + "`" + `registry.example.com/myimage:latest` + "`" + `.

The push is cancelled if the HTTP connection is closed.
`,
		RunE: runOperationImageImagePush,
	}

	if err := registerOperationImageImagePushParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationImageImagePush uses cmd flags to call endpoint api
func runOperationImageImagePush(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := image.NewImagePushParams()
	if err, _ = retrieveOperationImageImagePushXRegistryAuthFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImagePushNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImagePushTagFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationImageImagePushResult(appCli.Image.ImagePush(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationImageImagePushParamFlags registers all flags needed to fill params
func registerOperationImageImagePushParamFlags(cmd *cobra.Command) error {
	if err := registerOperationImageImagePushXRegistryAuthParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImagePushNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImagePushTagParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationImageImagePushXRegistryAuthParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagXRegistryAuthDescription := `Required. A base64-encoded auth configuration. [See the authentication section for details.](#section/Authentication)`

	var flagXRegistryAuthName string
	if cmdPrefix == "" {
		flagXRegistryAuthName = "X-Registry-Auth"
	} else {
		flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
	}

	var flagXRegistryAuthDefault string

	_ = cmd.PersistentFlags().String(flagXRegistryAuthName, flagXRegistryAuthDefault, flagXRegistryAuthDescription)

	return nil
}

func registerOperationImageImagePushNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. Image name or ID.`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerOperationImageImagePushTagParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagTagDescription := `The tag to associate with the image on the registry.`

	var flagTagName string
	if cmdPrefix == "" {
		flagTagName = "tag"
	} else {
		flagTagName = fmt.Sprintf("%v.tag", cmdPrefix)
	}

	var flagTagDefault string

	_ = cmd.PersistentFlags().String(flagTagName, flagTagDefault, flagTagDescription)

	return nil
}

func retrieveOperationImageImagePushXRegistryAuthFlag(m *image.ImagePushParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Registry-Auth") {

		var flagXRegistryAuthName string
		if cmdPrefix == "" {
			flagXRegistryAuthName = "X-Registry-Auth"
		} else {
			flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
		}

		flagXRegistryAuthValue, err := cmd.Flags().GetString(flagXRegistryAuthName)
		if err != nil {
			return err, false
		}
		m.XRegistryAuth = flagXRegistryAuthValue

	}

	return nil, retAdded
}

func retrieveOperationImageImagePushNameFlag(m *image.ImagePushParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

func retrieveOperationImageImagePushTagFlag(m *image.ImagePushParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tag") {

		var flagTagName string
		if cmdPrefix == "" {
			flagTagName = "tag"
		} else {
			flagTagName = fmt.Sprintf("%v.tag", cmdPrefix)
		}

		flagTagValue, err := cmd.Flags().GetString(flagTagName)
		if err != nil {
			return err, false
		}
		m.Tag = &flagTagValue

	}

	return nil, retAdded
}

// parseOperationImageImagePushResult parses request result and return the string content
func parseOperationImageImagePushResult(resp0 *image.ImagePushOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning imagePushOK is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*image.ImagePushNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*image.ImagePushInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response imagePushOK is not supported by go-swagger cli yet.
	return "", nil
}
