// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/image"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationImageImageCreateCmd returns a command to handle operation imageCreate
func makeOperationImageImageCreateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ImageCreate",
		Short: `Create an image by either pulling it from a registry or importing it.`,
		RunE:  runOperationImageImageCreate,
	}

	if err := registerOperationImageImageCreateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationImageImageCreate uses cmd flags to call endpoint api
func runOperationImageImageCreate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := image.NewImageCreateParams()
	if err, _ = retrieveOperationImageImageCreateXRegistryAuthFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreateFromImageFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreateFromSrcFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreateInputImageFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreatePlatformFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreateRepoFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationImageImageCreateTagFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationImageImageCreateResult(appCli.Image.ImageCreate(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationImageImageCreateParamFlags registers all flags needed to fill params
func registerOperationImageImageCreateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationImageImageCreateXRegistryAuthParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreateFromImageParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreateFromSrcParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreateInputImageParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreatePlatformParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreateRepoParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImageImageCreateTagParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationImageImageCreateXRegistryAuthParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagXRegistryAuthDescription := `A base64-encoded auth configuration. [See the authentication section for details.](#section/Authentication)`

	var flagXRegistryAuthName string
	if cmdPrefix == "" {
		flagXRegistryAuthName = "X-Registry-Auth"
	} else {
		flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
	}

	var flagXRegistryAuthDefault string

	_ = cmd.PersistentFlags().String(flagXRegistryAuthName, flagXRegistryAuthDefault, flagXRegistryAuthDescription)

	return nil
}

func registerOperationImageImageCreateFromImageParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagFromImageDescription := `Name of the image to pull. The name may include a tag or digest. This parameter may only be used when pulling an image. The pull is cancelled if the HTTP connection is closed.`

	var flagFromImageName string
	if cmdPrefix == "" {
		flagFromImageName = "fromImage"
	} else {
		flagFromImageName = fmt.Sprintf("%v.fromImage", cmdPrefix)
	}

	var flagFromImageDefault string

	_ = cmd.PersistentFlags().String(flagFromImageName, flagFromImageDefault, flagFromImageDescription)

	return nil
}

func registerOperationImageImageCreateFromSrcParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagFromSrcDescription := `Source to import. The value may be a URL from which the image can be retrieved or ` + "`" + `-` + "`" + ` to read the image from the request body. This parameter may only be used when importing an image.`

	var flagFromSrcName string
	if cmdPrefix == "" {
		flagFromSrcName = "fromSrc"
	} else {
		flagFromSrcName = fmt.Sprintf("%v.fromSrc", cmdPrefix)
	}

	var flagFromSrcDefault string

	_ = cmd.PersistentFlags().String(flagFromSrcName, flagFromSrcDefault, flagFromSrcDescription)

	return nil
}

func registerOperationImageImageCreateInputImageParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagInputImageDescription := `Image content if the value ` + "`" + `-` + "`" + ` has been specified in fromSrc query parameter`

	var flagInputImageName string
	if cmdPrefix == "" {
		flagInputImageName = "inputImage"
	} else {
		flagInputImageName = fmt.Sprintf("%v.inputImage", cmdPrefix)
	}

	var flagInputImageDefault string

	_ = cmd.PersistentFlags().String(flagInputImageName, flagInputImageDefault, flagInputImageDescription)

	return nil
}

func registerOperationImageImageCreatePlatformParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagPlatformDescription := `Platform in the format os[/arch[/variant]]`

	var flagPlatformName string
	if cmdPrefix == "" {
		flagPlatformName = "platform"
	} else {
		flagPlatformName = fmt.Sprintf("%v.platform", cmdPrefix)
	}

	var flagPlatformDefault string

	_ = cmd.PersistentFlags().String(flagPlatformName, flagPlatformDefault, flagPlatformDescription)

	return nil
}

func registerOperationImageImageCreateRepoParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagRepoDescription := `Repository name given to an image when it is imported. The repo may include a tag. This parameter may only be used when importing an image.`

	var flagRepoName string
	if cmdPrefix == "" {
		flagRepoName = "repo"
	} else {
		flagRepoName = fmt.Sprintf("%v.repo", cmdPrefix)
	}

	var flagRepoDefault string

	_ = cmd.PersistentFlags().String(flagRepoName, flagRepoDefault, flagRepoDescription)

	return nil
}

func registerOperationImageImageCreateTagParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagTagDescription := `Tag or digest. If empty when pulling an image, this causes all tags for the given image to be pulled.`

	var flagTagName string
	if cmdPrefix == "" {
		flagTagName = "tag"
	} else {
		flagTagName = fmt.Sprintf("%v.tag", cmdPrefix)
	}

	var flagTagDefault string

	_ = cmd.PersistentFlags().String(flagTagName, flagTagDefault, flagTagDescription)

	return nil
}

func retrieveOperationImageImageCreateXRegistryAuthFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Registry-Auth") {

		var flagXRegistryAuthName string
		if cmdPrefix == "" {
			flagXRegistryAuthName = "X-Registry-Auth"
		} else {
			flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
		}

		flagXRegistryAuthValue, err := cmd.Flags().GetString(flagXRegistryAuthName)
		if err != nil {
			return err, false
		}
		m.XRegistryAuth = &flagXRegistryAuthValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreateFromImageFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("fromImage") {

		var flagFromImageName string
		if cmdPrefix == "" {
			flagFromImageName = "fromImage"
		} else {
			flagFromImageName = fmt.Sprintf("%v.fromImage", cmdPrefix)
		}

		flagFromImageValue, err := cmd.Flags().GetString(flagFromImageName)
		if err != nil {
			return err, false
		}
		m.FromImage = &flagFromImageValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreateFromSrcFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("fromSrc") {

		var flagFromSrcName string
		if cmdPrefix == "" {
			flagFromSrcName = "fromSrc"
		} else {
			flagFromSrcName = fmt.Sprintf("%v.fromSrc", cmdPrefix)
		}

		flagFromSrcValue, err := cmd.Flags().GetString(flagFromSrcName)
		if err != nil {
			return err, false
		}
		m.FromSrc = &flagFromSrcValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreateInputImageFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("inputImage") {

		var flagInputImageName string
		if cmdPrefix == "" {
			flagInputImageName = "inputImage"
		} else {
			flagInputImageName = fmt.Sprintf("%v.inputImage", cmdPrefix)
		}

		flagInputImageValue, err := cmd.Flags().GetString(flagInputImageName)
		if err != nil {
			return err, false
		}
		m.InputImage = flagInputImageValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreatePlatformFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("platform") {

		var flagPlatformName string
		if cmdPrefix == "" {
			flagPlatformName = "platform"
		} else {
			flagPlatformName = fmt.Sprintf("%v.platform", cmdPrefix)
		}

		flagPlatformValue, err := cmd.Flags().GetString(flagPlatformName)
		if err != nil {
			return err, false
		}
		m.Platform = &flagPlatformValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreateRepoFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("repo") {

		var flagRepoName string
		if cmdPrefix == "" {
			flagRepoName = "repo"
		} else {
			flagRepoName = fmt.Sprintf("%v.repo", cmdPrefix)
		}

		flagRepoValue, err := cmd.Flags().GetString(flagRepoName)
		if err != nil {
			return err, false
		}
		m.Repo = &flagRepoValue

	}

	return nil, retAdded
}

func retrieveOperationImageImageCreateTagFlag(m *image.ImageCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tag") {

		var flagTagName string
		if cmdPrefix == "" {
			flagTagName = "tag"
		} else {
			flagTagName = fmt.Sprintf("%v.tag", cmdPrefix)
		}

		flagTagValue, err := cmd.Flags().GetString(flagTagName)
		if err != nil {
			return err, false
		}
		m.Tag = &flagTagValue

	}

	return nil, retAdded
}

// parseOperationImageImageCreateResult parses request result and return the string content
func parseOperationImageImageCreateResult(resp0 *image.ImageCreateOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning imageCreateOK is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*image.ImageCreateNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*image.ImageCreateInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response imageCreateOK is not supported by go-swagger cli yet.
	return "", nil
}
