// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/image"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationImageImageInspectCmd returns a command to handle operation imageInspect
func makeOperationImageImageInspectCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ImageInspect",
		Short: `Return low-level information about an image.`,
		RunE:  runOperationImageImageInspect,
	}

	if err := registerOperationImageImageInspectParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationImageImageInspect uses cmd flags to call endpoint api
func runOperationImageImageInspect(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := image.NewImageInspectParams()
	if err, _ = retrieveOperationImageImageInspectNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationImageImageInspectResult(appCli.Image.ImageInspect(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationImageImageInspectParamFlags registers all flags needed to fill params
func registerOperationImageImageInspectParamFlags(cmd *cobra.Command) error {
	if err := registerOperationImageImageInspectNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationImageImageInspectNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. Image name or id`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func retrieveOperationImageImageInspectNameFlag(m *image.ImageInspectParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

// parseOperationImageImageInspectResult parses request result and return the string content
func parseOperationImageImageInspectResult(resp0 *image.ImageInspectOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*image.ImageInspectOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*image.ImageInspectNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*image.ImageInspectInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
