// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for ManagerStatus

// register flags to command
func registerModelManagerStatusFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerManagerStatusPropAddr(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerManagerStatusPropLeader(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerManagerStatusPropReachability(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerManagerStatusPropAddr(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagAddrDescription := `The IP address and port at which the manager is reachable.
`

	var flagAddrName string
	if cmdPrefix == "" {
		flagAddrName = "Addr"
	} else {
		flagAddrName = fmt.Sprintf("%v.Addr", cmdPrefix)
	}

	var flagAddrDefault string

	_ = cmd.PersistentFlags().String(flagAddrName, flagAddrDefault, flagAddrDescription)

	return nil
}

func registerManagerStatusPropLeader(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLeaderDescription := ``

	var flagLeaderName string
	if cmdPrefix == "" {
		flagLeaderName = "Leader"
	} else {
		flagLeaderName = fmt.Sprintf("%v.Leader", cmdPrefix)
	}

	var flagLeaderDefault bool

	_ = cmd.PersistentFlags().Bool(flagLeaderName, flagLeaderDefault, flagLeaderDescription)

	return nil
}

func registerManagerStatusPropReachability(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive Reachability Reachability is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelManagerStatusFlags(depth int, m *models.ManagerStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AddrAdded := retrieveManagerStatusPropAddrFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AddrAdded

	err, LeaderAdded := retrieveManagerStatusPropLeaderFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LeaderAdded

	err, ReachabilityAdded := retrieveManagerStatusPropReachabilityFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ReachabilityAdded

	return nil, retAdded
}

func retrieveManagerStatusPropAddrFlags(depth int, m *models.ManagerStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAddrName := fmt.Sprintf("%v.Addr", cmdPrefix)
	if cmd.Flags().Changed(flagAddrName) {

		var flagAddrName string
		if cmdPrefix == "" {
			flagAddrName = "Addr"
		} else {
			flagAddrName = fmt.Sprintf("%v.Addr", cmdPrefix)
		}

		flagAddrValue, err := cmd.Flags().GetString(flagAddrName)
		if err != nil {
			return err, false
		}
		m.Addr = flagAddrValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveManagerStatusPropLeaderFlags(depth int, m *models.ManagerStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLeaderName := fmt.Sprintf("%v.Leader", cmdPrefix)
	if cmd.Flags().Changed(flagLeaderName) {

		var flagLeaderName string
		if cmdPrefix == "" {
			flagLeaderName = "Leader"
		} else {
			flagLeaderName = fmt.Sprintf("%v.Leader", cmdPrefix)
		}

		flagLeaderValue, err := cmd.Flags().GetBool(flagLeaderName)
		if err != nil {
			return err, false
		}
		m.Leader = &flagLeaderValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveManagerStatusPropReachabilityFlags(depth int, m *models.ManagerStatus, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagReachabilityName := fmt.Sprintf("%v.Reachability", cmdPrefix)
	if cmd.Flags().Changed(flagReachabilityName) {

		// warning: primitive Reachability Reachability is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}
