// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for ObjectVersion

// register flags to command
func registerModelObjectVersionFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerObjectVersionPropIndex(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerObjectVersionPropIndex(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive Index uint64 is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelObjectVersionFlags(depth int, m *models.ObjectVersion, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IndexAdded := retrieveObjectVersionPropIndexFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IndexAdded

	return nil, retAdded
}

func retrieveObjectVersionPropIndexFlags(depth int, m *models.ObjectVersion, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIndexName := fmt.Sprintf("%v.Index", cmdPrefix)
	if cmd.Flags().Changed(flagIndexName) {

		// warning: primitive Index uint64 is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}
