// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/plugin"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationPluginPluginUpgradeCmd returns a command to handle operation pluginUpgrade
func makeOperationPluginPluginUpgradeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PluginUpgrade",
		Short: ``,
		RunE:  runOperationPluginPluginUpgrade,
	}

	if err := registerOperationPluginPluginUpgradeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPluginPluginUpgrade uses cmd flags to call endpoint api
func runOperationPluginPluginUpgrade(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := plugin.NewPluginUpgradeParams()
	if err, _ = retrieveOperationPluginPluginUpgradeXRegistryAuthFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationPluginPluginUpgradeBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationPluginPluginUpgradeNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationPluginPluginUpgradeRemoteFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPluginPluginUpgradeResult(appCli.Plugin.PluginUpgrade(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationPluginPluginUpgradeParamFlags registers all flags needed to fill params
func registerOperationPluginPluginUpgradeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPluginPluginUpgradeXRegistryAuthParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPluginPluginUpgradeBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPluginPluginUpgradeNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPluginPluginUpgradeRemoteParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPluginPluginUpgradeXRegistryAuthParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagXRegistryAuthDescription := `A base64-encoded auth configuration to use when pulling a plugin from a registry. [See the authentication section for details.](#section/Authentication)`

	var flagXRegistryAuthName string
	if cmdPrefix == "" {
		flagXRegistryAuthName = "X-Registry-Auth"
	} else {
		flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
	}

	var flagXRegistryAuthDefault string

	_ = cmd.PersistentFlags().String(flagXRegistryAuthName, flagXRegistryAuthDefault, flagXRegistryAuthDescription)

	return nil
}

func registerOperationPluginPluginUpgradeBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	// warning: array body []*PluginUpgradeParamsBodyItems0 is not supported by go-swagger cli yet

	return nil
}

func registerOperationPluginPluginUpgradeNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. The name of the plugin. The ` + "`" + `:latest` + "`" + ` tag is optional, and is the default if omitted.`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerOperationPluginPluginUpgradeRemoteParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagRemoteDescription := `Required. Remote reference to upgrade to.

The ` + "`" + `:latest` + "`" + ` tag is optional, and is used as the default if omitted.
`

	var flagRemoteName string
	if cmdPrefix == "" {
		flagRemoteName = "remote"
	} else {
		flagRemoteName = fmt.Sprintf("%v.remote", cmdPrefix)
	}

	var flagRemoteDefault string

	_ = cmd.PersistentFlags().String(flagRemoteName, flagRemoteDefault, flagRemoteDescription)

	return nil
}

func retrieveOperationPluginPluginUpgradeXRegistryAuthFlag(m *plugin.PluginUpgradeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Registry-Auth") {

		var flagXRegistryAuthName string
		if cmdPrefix == "" {
			flagXRegistryAuthName = "X-Registry-Auth"
		} else {
			flagXRegistryAuthName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
		}

		flagXRegistryAuthValue, err := cmd.Flags().GetString(flagXRegistryAuthName)
		if err != nil {
			return err, false
		}
		m.XRegistryAuth = &flagXRegistryAuthValue

	}

	return nil, retAdded
}

func retrieveOperationPluginPluginUpgradeBodyFlag(m *plugin.PluginUpgradeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {

		// warning: array body []*PluginUpgradeParamsBodyItems0 is not supported by go-swagger cli yet

	}

	return nil, retAdded
}

func retrieveOperationPluginPluginUpgradeNameFlag(m *plugin.PluginUpgradeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

func retrieveOperationPluginPluginUpgradeRemoteFlag(m *plugin.PluginUpgradeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("remote") {

		var flagRemoteName string
		if cmdPrefix == "" {
			flagRemoteName = "remote"
		} else {
			flagRemoteName = fmt.Sprintf("%v.remote", cmdPrefix)
		}

		flagRemoteValue, err := cmd.Flags().GetString(flagRemoteName)
		if err != nil {
			return err, false
		}
		m.Remote = flagRemoteValue

	}

	return nil, retAdded
}

// parseOperationPluginPluginUpgradeResult parses request result and return the string content
func parseOperationPluginPluginUpgradeResult(resp0 *plugin.PluginUpgradeNoContent, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning pluginUpgradeNoContent is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*plugin.PluginUpgradeNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*plugin.PluginUpgradeInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response pluginUpgradeNoContent is not supported by go-swagger cli yet.
	return "", nil
}

// register flags to command
func registerModelPluginUpgradeParamsBodyItems0Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPluginUpgradeParamsBodyItems0PropDescription(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPluginUpgradeParamsBodyItems0PropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPluginUpgradeParamsBodyItems0PropValue(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPluginUpgradeParamsBodyItems0PropDescription(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDescriptionDescription := ``

	var flagDescriptionName string
	if cmdPrefix == "" {
		flagDescriptionName = "Description"
	} else {
		flagDescriptionName = fmt.Sprintf("%v.Description", cmdPrefix)
	}

	var flagDescriptionDefault string

	_ = cmd.PersistentFlags().String(flagDescriptionName, flagDescriptionDefault, flagDescriptionDescription)

	return nil
}

func registerPluginUpgradeParamsBodyItems0PropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := ``

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "Name"
	} else {
		flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerPluginUpgradeParamsBodyItems0PropValue(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Value []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPluginUpgradeParamsBodyItems0Flags(depth int, m *plugin.PluginUpgradeParamsBodyItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, DescriptionAdded := retrievePluginUpgradeParamsBodyItems0PropDescriptionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DescriptionAdded

	err, NameAdded := retrievePluginUpgradeParamsBodyItems0PropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, ValueAdded := retrievePluginUpgradeParamsBodyItems0PropValueFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ValueAdded

	return nil, retAdded
}

func retrievePluginUpgradeParamsBodyItems0PropDescriptionFlags(depth int, m *plugin.PluginUpgradeParamsBodyItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDescriptionName := fmt.Sprintf("%v.Description", cmdPrefix)
	if cmd.Flags().Changed(flagDescriptionName) {

		var flagDescriptionName string
		if cmdPrefix == "" {
			flagDescriptionName = "Description"
		} else {
			flagDescriptionName = fmt.Sprintf("%v.Description", cmdPrefix)
		}

		flagDescriptionValue, err := cmd.Flags().GetString(flagDescriptionName)
		if err != nil {
			return err, false
		}
		m.Description = flagDescriptionValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePluginUpgradeParamsBodyItems0PropNameFlags(depth int, m *plugin.PluginUpgradeParamsBodyItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.Name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "Name"
		} else {
			flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePluginUpgradeParamsBodyItems0PropValueFlags(depth int, m *plugin.PluginUpgradeParamsBodyItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagValueName := fmt.Sprintf("%v.Value", cmdPrefix)
	if cmd.Flags().Changed(flagValueName) {
		// warning: Value array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
