// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/plugin"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationPluginPluginDeleteCmd returns a command to handle operation pluginDelete
func makeOperationPluginPluginDeleteCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PluginDelete",
		Short: ``,
		RunE:  runOperationPluginPluginDelete,
	}

	if err := registerOperationPluginPluginDeleteParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPluginPluginDelete uses cmd flags to call endpoint api
func runOperationPluginPluginDelete(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := plugin.NewPluginDeleteParams()
	if err, _ = retrieveOperationPluginPluginDeleteForceFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationPluginPluginDeleteNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPluginPluginDeleteResult(appCli.Plugin.PluginDelete(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationPluginPluginDeleteParamFlags registers all flags needed to fill params
func registerOperationPluginPluginDeleteParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPluginPluginDeleteForceParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPluginPluginDeleteNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPluginPluginDeleteForceParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagForceDescription := `Disable the plugin before removing. This may result in issues if the plugin is in use by a container.`

	var flagForceName string
	if cmdPrefix == "" {
		flagForceName = "force"
	} else {
		flagForceName = fmt.Sprintf("%v.force", cmdPrefix)
	}

	var flagForceDefault bool

	_ = cmd.PersistentFlags().Bool(flagForceName, flagForceDefault, flagForceDescription)

	return nil
}

func registerOperationPluginPluginDeleteNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. The name of the plugin. The ` + "`" + `:latest` + "`" + ` tag is optional, and is the default if omitted.`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func retrieveOperationPluginPluginDeleteForceFlag(m *plugin.PluginDeleteParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("force") {

		var flagForceName string
		if cmdPrefix == "" {
			flagForceName = "force"
		} else {
			flagForceName = fmt.Sprintf("%v.force", cmdPrefix)
		}

		flagForceValue, err := cmd.Flags().GetBool(flagForceName)
		if err != nil {
			return err, false
		}
		m.Force = &flagForceValue

	}

	return nil, retAdded
}

func retrieveOperationPluginPluginDeleteNameFlag(m *plugin.PluginDeleteParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

// parseOperationPluginPluginDeleteResult parses request result and return the string content
func parseOperationPluginPluginDeleteResult(resp0 *plugin.PluginDeleteOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*plugin.PluginDeleteOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*plugin.PluginDeleteNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*plugin.PluginDeleteInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
