// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for PluginInterfaceType

// register flags to command
func registerModelPluginInterfaceTypeFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPluginInterfaceTypePropCapability(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPluginInterfaceTypePropPrefix(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPluginInterfaceTypePropVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPluginInterfaceTypePropCapability(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCapabilityDescription := `Required. `

	var flagCapabilityName string
	if cmdPrefix == "" {
		flagCapabilityName = "Capability"
	} else {
		flagCapabilityName = fmt.Sprintf("%v.Capability", cmdPrefix)
	}

	var flagCapabilityDefault string

	_ = cmd.PersistentFlags().String(flagCapabilityName, flagCapabilityDefault, flagCapabilityDescription)

	return nil
}

func registerPluginInterfaceTypePropPrefix(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPrefixDescription := `Required. `

	var flagPrefixName string
	if cmdPrefix == "" {
		flagPrefixName = "Prefix"
	} else {
		flagPrefixName = fmt.Sprintf("%v.Prefix", cmdPrefix)
	}

	var flagPrefixDefault string

	_ = cmd.PersistentFlags().String(flagPrefixName, flagPrefixDefault, flagPrefixDescription)

	return nil
}

func registerPluginInterfaceTypePropVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagVersionDescription := `Required. `

	var flagVersionName string
	if cmdPrefix == "" {
		flagVersionName = "Version"
	} else {
		flagVersionName = fmt.Sprintf("%v.Version", cmdPrefix)
	}

	var flagVersionDefault string

	_ = cmd.PersistentFlags().String(flagVersionName, flagVersionDefault, flagVersionDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPluginInterfaceTypeFlags(depth int, m *models.PluginInterfaceType, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CapabilityAdded := retrievePluginInterfaceTypePropCapabilityFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CapabilityAdded

	err, PrefixAdded := retrievePluginInterfaceTypePropPrefixFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PrefixAdded

	err, VersionAdded := retrievePluginInterfaceTypePropVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || VersionAdded

	return nil, retAdded
}

func retrievePluginInterfaceTypePropCapabilityFlags(depth int, m *models.PluginInterfaceType, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCapabilityName := fmt.Sprintf("%v.Capability", cmdPrefix)
	if cmd.Flags().Changed(flagCapabilityName) {

		var flagCapabilityName string
		if cmdPrefix == "" {
			flagCapabilityName = "Capability"
		} else {
			flagCapabilityName = fmt.Sprintf("%v.Capability", cmdPrefix)
		}

		flagCapabilityValue, err := cmd.Flags().GetString(flagCapabilityName)
		if err != nil {
			return err, false
		}
		m.Capability = flagCapabilityValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePluginInterfaceTypePropPrefixFlags(depth int, m *models.PluginInterfaceType, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPrefixName := fmt.Sprintf("%v.Prefix", cmdPrefix)
	if cmd.Flags().Changed(flagPrefixName) {

		var flagPrefixName string
		if cmdPrefix == "" {
			flagPrefixName = "Prefix"
		} else {
			flagPrefixName = fmt.Sprintf("%v.Prefix", cmdPrefix)
		}

		flagPrefixValue, err := cmd.Flags().GetString(flagPrefixName)
		if err != nil {
			return err, false
		}
		m.Prefix = flagPrefixValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePluginInterfaceTypePropVersionFlags(depth int, m *models.PluginInterfaceType, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagVersionName := fmt.Sprintf("%v.Version", cmdPrefix)
	if cmd.Flags().Changed(flagVersionName) {

		var flagVersionName string
		if cmdPrefix == "" {
			flagVersionName = "Version"
		} else {
			flagVersionName = fmt.Sprintf("%v.Version", cmdPrefix)
		}

		flagVersionValue, err := cmd.Flags().GetString(flagVersionName)
		if err != nil {
			return err, false
		}
		m.Version = flagVersionValue

		retAdded = true
	}

	return nil, retAdded
}
