// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/plugin"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationPluginPluginEnableCmd returns a command to handle operation pluginEnable
func makeOperationPluginPluginEnableCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PluginEnable",
		Short: ``,
		RunE:  runOperationPluginPluginEnable,
	}

	if err := registerOperationPluginPluginEnableParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPluginPluginEnable uses cmd flags to call endpoint api
func runOperationPluginPluginEnable(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := plugin.NewPluginEnableParams()
	if err, _ = retrieveOperationPluginPluginEnableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationPluginPluginEnableTimeoutFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPluginPluginEnableResult(appCli.Plugin.PluginEnable(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationPluginPluginEnableParamFlags registers all flags needed to fill params
func registerOperationPluginPluginEnableParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPluginPluginEnableNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPluginPluginEnableTimeoutParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPluginPluginEnableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagNameDescription := `Required. The name of the plugin. The ` + "`" + `:latest` + "`" + ` tag is optional, and is the default if omitted.`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerOperationPluginPluginEnableTimeoutParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagTimeoutDescription := `Set the HTTP client timeout (in seconds)`

	var flagTimeoutName string
	if cmdPrefix == "" {
		flagTimeoutName = "timeout"
	} else {
		flagTimeoutName = fmt.Sprintf("%v.timeout", cmdPrefix)
	}

	var flagTimeoutDefault int64

	_ = cmd.PersistentFlags().Int64(flagTimeoutName, flagTimeoutDefault, flagTimeoutDescription)

	return nil
}

func retrieveOperationPluginPluginEnableNameFlag(m *plugin.PluginEnableParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

	}

	return nil, retAdded
}

func retrieveOperationPluginPluginEnableTimeoutFlag(m *plugin.PluginEnableParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("timeout") {

		var flagTimeoutName string
		if cmdPrefix == "" {
			flagTimeoutName = "timeout"
		} else {
			flagTimeoutName = fmt.Sprintf("%v.timeout", cmdPrefix)
		}

		flagTimeoutValue, err := cmd.Flags().GetInt64(flagTimeoutName)
		if err != nil {
			return err, false
		}
		m.Timeout = &flagTimeoutValue

	}

	return nil, retAdded
}

// parseOperationPluginPluginEnableResult parses request result and return the string content
func parseOperationPluginPluginEnableResult(resp0 *plugin.PluginEnableOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning pluginEnableOK is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*plugin.PluginEnableNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*plugin.PluginEnableInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response pluginEnableOK is not supported by go-swagger cli yet.
	return "", nil
}
