// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for Port

// register flags to command
func registerModelPortFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPortPropIP(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPortPropPrivatePort(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPortPropPublicPort(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPortPropType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPortPropIP(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIPDescription := `Host IP address that the container's port is mapped to`

	var flagIPName string
	if cmdPrefix == "" {
		flagIPName = "IP"
	} else {
		flagIPName = fmt.Sprintf("%v.IP", cmdPrefix)
	}

	var flagIPDefault string

	_ = cmd.PersistentFlags().String(flagIPName, flagIPDefault, flagIPDescription)

	return nil
}

func registerPortPropPrivatePort(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive PrivatePort uint16 is not supported by go-swagger cli yet

	return nil
}

func registerPortPropPublicPort(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: primitive PublicPort uint16 is not supported by go-swagger cli yet

	return nil
}

func registerPortPropType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTypeDescription := `Enum: ["tcp","udp","sctp"]. Required. `

	var flagTypeName string
	if cmdPrefix == "" {
		flagTypeName = "Type"
	} else {
		flagTypeName = fmt.Sprintf("%v.Type", cmdPrefix)
	}

	var flagTypeDefault string

	_ = cmd.PersistentFlags().String(flagTypeName, flagTypeDefault, flagTypeDescription)

	if err := cmd.RegisterFlagCompletionFunc(flagTypeName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["tcp","udp","sctp"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPortFlags(depth int, m *models.Port, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IPAdded := retrievePortPropIPFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IPAdded

	err, PrivatePortAdded := retrievePortPropPrivatePortFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PrivatePortAdded

	err, PublicPortAdded := retrievePortPropPublicPortFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PublicPortAdded

	err, TypeAdded := retrievePortPropTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TypeAdded

	return nil, retAdded
}

func retrievePortPropIPFlags(depth int, m *models.Port, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIPName := fmt.Sprintf("%v.IP", cmdPrefix)
	if cmd.Flags().Changed(flagIPName) {

		var flagIPName string
		if cmdPrefix == "" {
			flagIPName = "IP"
		} else {
			flagIPName = fmt.Sprintf("%v.IP", cmdPrefix)
		}

		flagIPValue, err := cmd.Flags().GetString(flagIPName)
		if err != nil {
			return err, false
		}
		m.IP = flagIPValue

		retAdded = true
	}

	return nil, retAdded
}

func retrievePortPropPrivatePortFlags(depth int, m *models.Port, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPrivatePortName := fmt.Sprintf("%v.PrivatePort", cmdPrefix)
	if cmd.Flags().Changed(flagPrivatePortName) {

		// warning: primitive PrivatePort uint16 is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}

func retrievePortPropPublicPortFlags(depth int, m *models.Port, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPublicPortName := fmt.Sprintf("%v.PublicPort", cmdPrefix)
	if cmd.Flags().Changed(flagPublicPortName) {

		// warning: primitive PublicPort uint16 is not supported by go-swagger cli yet

		retAdded = true
	}

	return nil, retAdded
}

func retrievePortPropTypeFlags(depth int, m *models.Port, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTypeName := fmt.Sprintf("%v.Type", cmdPrefix)
	if cmd.Flags().Changed(flagTypeName) {

		var flagTypeName string
		if cmdPrefix == "" {
			flagTypeName = "Type"
		} else {
			flagTypeName = fmt.Sprintf("%v.Type", cmdPrefix)
		}

		flagTypeValue, err := cmd.Flags().GetString(flagTypeName)
		if err != nil {
			return err, false
		}
		m.Type = flagTypeValue

		retAdded = true
	}

	return nil, retAdded
}
