// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for RegistryServiceConfig

// register flags to command
func registerModelRegistryServiceConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerRegistryServiceConfigPropAllowNondistributableArtifactsCIDRs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerRegistryServiceConfigPropAllowNondistributableArtifactsHostnames(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerRegistryServiceConfigPropIndexConfigs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerRegistryServiceConfigPropInsecureRegistryCIDRs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerRegistryServiceConfigPropMirrors(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerRegistryServiceConfigPropAllowNondistributableArtifactsCIDRs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: AllowNondistributableArtifactsCIDRs []string array type is not supported by go-swagger cli yet

	return nil
}

func registerRegistryServiceConfigPropAllowNondistributableArtifactsHostnames(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: AllowNondistributableArtifactsHostnames []string array type is not supported by go-swagger cli yet

	return nil
}

func registerRegistryServiceConfigPropIndexConfigs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: IndexConfigs map[string]IndexInfo map type is not supported by go-swagger cli yet

	return nil
}

func registerRegistryServiceConfigPropInsecureRegistryCIDRs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: InsecureRegistryCIDRs []string array type is not supported by go-swagger cli yet

	return nil
}

func registerRegistryServiceConfigPropMirrors(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Mirrors []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelRegistryServiceConfigFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, AllowNondistributableArtifactsCIDRsAdded := retrieveRegistryServiceConfigPropAllowNondistributableArtifactsCIDRsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AllowNondistributableArtifactsCIDRsAdded

	err, AllowNondistributableArtifactsHostnamesAdded := retrieveRegistryServiceConfigPropAllowNondistributableArtifactsHostnamesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AllowNondistributableArtifactsHostnamesAdded

	err, IndexConfigsAdded := retrieveRegistryServiceConfigPropIndexConfigsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IndexConfigsAdded

	err, InsecureRegistryCIDRsAdded := retrieveRegistryServiceConfigPropInsecureRegistryCIDRsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || InsecureRegistryCIDRsAdded

	err, MirrorsAdded := retrieveRegistryServiceConfigPropMirrorsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MirrorsAdded

	return nil, retAdded
}

func retrieveRegistryServiceConfigPropAllowNondistributableArtifactsCIDRsFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAllowNondistributableArtifactsCIDRsName := fmt.Sprintf("%v.AllowNondistributableArtifactsCIDRs", cmdPrefix)
	if cmd.Flags().Changed(flagAllowNondistributableArtifactsCIDRsName) {
		// warning: AllowNondistributableArtifactsCIDRs array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveRegistryServiceConfigPropAllowNondistributableArtifactsHostnamesFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagAllowNondistributableArtifactsHostnamesName := fmt.Sprintf("%v.AllowNondistributableArtifactsHostnames", cmdPrefix)
	if cmd.Flags().Changed(flagAllowNondistributableArtifactsHostnamesName) {
		// warning: AllowNondistributableArtifactsHostnames array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveRegistryServiceConfigPropIndexConfigsFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIndexConfigsName := fmt.Sprintf("%v.IndexConfigs", cmdPrefix)
	if cmd.Flags().Changed(flagIndexConfigsName) {
		// warning: IndexConfigs map type map[string]IndexInfo is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveRegistryServiceConfigPropInsecureRegistryCIDRsFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagInsecureRegistryCIDRsName := fmt.Sprintf("%v.InsecureRegistryCIDRs", cmdPrefix)
	if cmd.Flags().Changed(flagInsecureRegistryCIDRsName) {
		// warning: InsecureRegistryCIDRs array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveRegistryServiceConfigPropMirrorsFlags(depth int, m *models.RegistryServiceConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMirrorsName := fmt.Sprintf("%v.Mirrors", cmdPrefix)
	if cmd.Flags().Changed(flagMirrorsName) {
		// warning: Mirrors array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
