// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for Resources

// register flags to command
func registerModelResourcesFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerResourcesPropBlkioDeviceReadBps(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropBlkioDeviceReadIOps(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropBlkioDeviceWriteBps(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropBlkioDeviceWriteIOps(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropBlkioWeight(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropBlkioWeightDevice(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCgroupParent(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPUCount(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPUPercent(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPUPeriod(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPUQuota(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPURealtimePeriod(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPURealtimeRuntime(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCPUShares(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCpusetCpus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropCpusetMems(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropDeviceCgroupRules(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropDeviceRequests(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropDevices(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropIOMaximumBandwidth(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropIOMaximumIOps(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropInit(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropKernelMemory(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropKernelMemoryTCP(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropMemory(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropMemoryReservation(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropMemorySwap(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropMemorySwappiness(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropNanoCPUs(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropOomKillDisable(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropPidsLimit(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesPropUlimits(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerResourcesPropBlkioDeviceReadBps(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BlkioDeviceReadBps []*ThrottleDevice array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropBlkioDeviceReadIOps(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BlkioDeviceReadIOps []*ThrottleDevice array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropBlkioDeviceWriteBps(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BlkioDeviceWriteBps []*ThrottleDevice array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropBlkioDeviceWriteIOps(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BlkioDeviceWriteIOps []*ThrottleDevice array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropBlkioWeight(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagBlkioWeightDescription := `Block IO weight (relative weight).`

	var flagBlkioWeightName string
	if cmdPrefix == "" {
		flagBlkioWeightName = "BlkioWeight"
	} else {
		flagBlkioWeightName = fmt.Sprintf("%v.BlkioWeight", cmdPrefix)
	}

	var flagBlkioWeightDefault int64

	_ = cmd.PersistentFlags().Int64(flagBlkioWeightName, flagBlkioWeightDefault, flagBlkioWeightDescription)

	return nil
}

func registerResourcesPropBlkioWeightDevice(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BlkioWeightDevice []*ResourcesBlkioWeightDeviceItems0 array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropCgroupParent(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCgroupParentDescription := `Path to ` + "`" + `cgroups` + "`" + ` under which the container's ` + "`" + `cgroup` + "`" + ` is created. If the path is not absolute, the path is considered to be relative to the ` + "`" + `cgroups` + "`" + ` path of the init process. Cgroups are created if they do not already exist.`

	var flagCgroupParentName string
	if cmdPrefix == "" {
		flagCgroupParentName = "CgroupParent"
	} else {
		flagCgroupParentName = fmt.Sprintf("%v.CgroupParent", cmdPrefix)
	}

	var flagCgroupParentDefault string

	_ = cmd.PersistentFlags().String(flagCgroupParentName, flagCgroupParentDefault, flagCgroupParentDescription)

	return nil
}

func registerResourcesPropCPUCount(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPUCountDescription := `The number of usable CPUs (Windows only).

On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is ` + "`" + `CPUCount` + "`" + ` first, then ` + "`" + `CPUShares` + "`" + `, and ` + "`" + `CPUPercent` + "`" + ` last.
`

	var flagCPUCountName string
	if cmdPrefix == "" {
		flagCPUCountName = "CpuCount"
	} else {
		flagCPUCountName = fmt.Sprintf("%v.CpuCount", cmdPrefix)
	}

	var flagCPUCountDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPUCountName, flagCPUCountDefault, flagCPUCountDescription)

	return nil
}

func registerResourcesPropCPUPercent(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPUPercentDescription := `The usable percentage of the available CPUs (Windows only).

On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is ` + "`" + `CPUCount` + "`" + ` first, then ` + "`" + `CPUShares` + "`" + `, and ` + "`" + `CPUPercent` + "`" + ` last.
`

	var flagCPUPercentName string
	if cmdPrefix == "" {
		flagCPUPercentName = "CpuPercent"
	} else {
		flagCPUPercentName = fmt.Sprintf("%v.CpuPercent", cmdPrefix)
	}

	var flagCPUPercentDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPUPercentName, flagCPUPercentDefault, flagCPUPercentDescription)

	return nil
}

func registerResourcesPropCPUPeriod(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPUPeriodDescription := `The length of a CPU period in microseconds.`

	var flagCPUPeriodName string
	if cmdPrefix == "" {
		flagCPUPeriodName = "CpuPeriod"
	} else {
		flagCPUPeriodName = fmt.Sprintf("%v.CpuPeriod", cmdPrefix)
	}

	var flagCPUPeriodDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPUPeriodName, flagCPUPeriodDefault, flagCPUPeriodDescription)

	return nil
}

func registerResourcesPropCPUQuota(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPUQuotaDescription := `Microseconds of CPU time that the container can get in a CPU period.`

	var flagCPUQuotaName string
	if cmdPrefix == "" {
		flagCPUQuotaName = "CpuQuota"
	} else {
		flagCPUQuotaName = fmt.Sprintf("%v.CpuQuota", cmdPrefix)
	}

	var flagCPUQuotaDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPUQuotaName, flagCPUQuotaDefault, flagCPUQuotaDescription)

	return nil
}

func registerResourcesPropCPURealtimePeriod(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPURealtimePeriodDescription := `The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.`

	var flagCPURealtimePeriodName string
	if cmdPrefix == "" {
		flagCPURealtimePeriodName = "CpuRealtimePeriod"
	} else {
		flagCPURealtimePeriodName = fmt.Sprintf("%v.CpuRealtimePeriod", cmdPrefix)
	}

	var flagCPURealtimePeriodDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPURealtimePeriodName, flagCPURealtimePeriodDefault, flagCPURealtimePeriodDescription)

	return nil
}

func registerResourcesPropCPURealtimeRuntime(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPURealtimeRuntimeDescription := `The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.`

	var flagCPURealtimeRuntimeName string
	if cmdPrefix == "" {
		flagCPURealtimeRuntimeName = "CpuRealtimeRuntime"
	} else {
		flagCPURealtimeRuntimeName = fmt.Sprintf("%v.CpuRealtimeRuntime", cmdPrefix)
	}

	var flagCPURealtimeRuntimeDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPURealtimeRuntimeName, flagCPURealtimeRuntimeDefault, flagCPURealtimeRuntimeDescription)

	return nil
}

func registerResourcesPropCPUShares(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCPUSharesDescription := `An integer value representing this container's relative CPU weight versus other containers.`

	var flagCPUSharesName string
	if cmdPrefix == "" {
		flagCPUSharesName = "CpuShares"
	} else {
		flagCPUSharesName = fmt.Sprintf("%v.CpuShares", cmdPrefix)
	}

	var flagCPUSharesDefault int64

	_ = cmd.PersistentFlags().Int64(flagCPUSharesName, flagCPUSharesDefault, flagCPUSharesDescription)

	return nil
}

func registerResourcesPropCpusetCpus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCpusetCpusDescription := `CPUs in which to allow execution (e.g., ` + "`" + `0-3` + "`" + `, ` + "`" + `0,1` + "`" + `)`

	var flagCpusetCpusName string
	if cmdPrefix == "" {
		flagCpusetCpusName = "CpusetCpus"
	} else {
		flagCpusetCpusName = fmt.Sprintf("%v.CpusetCpus", cmdPrefix)
	}

	var flagCpusetCpusDefault string

	_ = cmd.PersistentFlags().String(flagCpusetCpusName, flagCpusetCpusDefault, flagCpusetCpusDescription)

	return nil
}

func registerResourcesPropCpusetMems(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCpusetMemsDescription := `Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.`

	var flagCpusetMemsName string
	if cmdPrefix == "" {
		flagCpusetMemsName = "CpusetMems"
	} else {
		flagCpusetMemsName = fmt.Sprintf("%v.CpusetMems", cmdPrefix)
	}

	var flagCpusetMemsDefault string

	_ = cmd.PersistentFlags().String(flagCpusetMemsName, flagCpusetMemsDefault, flagCpusetMemsDescription)

	return nil
}

func registerResourcesPropDeviceCgroupRules(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: DeviceCgroupRules []string array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropDeviceRequests(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: DeviceRequests []*DeviceRequest array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropDevices(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Devices []*DeviceMapping array type is not supported by go-swagger cli yet

	return nil
}

func registerResourcesPropIOMaximumBandwidth(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIOMaximumBandwidthDescription := `Maximum IO in bytes per second for the container system drive (Windows only)`

	var flagIOMaximumBandwidthName string
	if cmdPrefix == "" {
		flagIOMaximumBandwidthName = "IOMaximumBandwidth"
	} else {
		flagIOMaximumBandwidthName = fmt.Sprintf("%v.IOMaximumBandwidth", cmdPrefix)
	}

	var flagIOMaximumBandwidthDefault int64

	_ = cmd.PersistentFlags().Int64(flagIOMaximumBandwidthName, flagIOMaximumBandwidthDefault, flagIOMaximumBandwidthDescription)

	return nil
}

func registerResourcesPropIOMaximumIOps(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIOMaximumIOpsDescription := `Maximum IOps for the container system drive (Windows only)`

	var flagIOMaximumIOpsName string
	if cmdPrefix == "" {
		flagIOMaximumIOpsName = "IOMaximumIOps"
	} else {
		flagIOMaximumIOpsName = fmt.Sprintf("%v.IOMaximumIOps", cmdPrefix)
	}

	var flagIOMaximumIOpsDefault int64

	_ = cmd.PersistentFlags().Int64(flagIOMaximumIOpsName, flagIOMaximumIOpsDefault, flagIOMaximumIOpsDescription)

	return nil
}

func registerResourcesPropInit(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagInitDescription := `Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.`

	var flagInitName string
	if cmdPrefix == "" {
		flagInitName = "Init"
	} else {
		flagInitName = fmt.Sprintf("%v.Init", cmdPrefix)
	}

	var flagInitDefault bool

	_ = cmd.PersistentFlags().Bool(flagInitName, flagInitDefault, flagInitDescription)

	return nil
}

func registerResourcesPropKernelMemory(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagKernelMemoryDescription := `Kernel memory limit in bytes.`

	var flagKernelMemoryName string
	if cmdPrefix == "" {
		flagKernelMemoryName = "KernelMemory"
	} else {
		flagKernelMemoryName = fmt.Sprintf("%v.KernelMemory", cmdPrefix)
	}

	var flagKernelMemoryDefault int64

	_ = cmd.PersistentFlags().Int64(flagKernelMemoryName, flagKernelMemoryDefault, flagKernelMemoryDescription)

	return nil
}

func registerResourcesPropKernelMemoryTCP(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagKernelMemoryTCPDescription := `Hard limit for kernel TCP buffer memory (in bytes).`

	var flagKernelMemoryTCPName string
	if cmdPrefix == "" {
		flagKernelMemoryTCPName = "KernelMemoryTCP"
	} else {
		flagKernelMemoryTCPName = fmt.Sprintf("%v.KernelMemoryTCP", cmdPrefix)
	}

	var flagKernelMemoryTCPDefault int64

	_ = cmd.PersistentFlags().Int64(flagKernelMemoryTCPName, flagKernelMemoryTCPDefault, flagKernelMemoryTCPDescription)

	return nil
}

func registerResourcesPropMemory(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMemoryDescription := `Memory limit in bytes.`

	var flagMemoryName string
	if cmdPrefix == "" {
		flagMemoryName = "Memory"
	} else {
		flagMemoryName = fmt.Sprintf("%v.Memory", cmdPrefix)
	}

	var flagMemoryDefault int64

	_ = cmd.PersistentFlags().Int64(flagMemoryName, flagMemoryDefault, flagMemoryDescription)

	return nil
}

func registerResourcesPropMemoryReservation(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMemoryReservationDescription := `Memory soft limit in bytes.`

	var flagMemoryReservationName string
	if cmdPrefix == "" {
		flagMemoryReservationName = "MemoryReservation"
	} else {
		flagMemoryReservationName = fmt.Sprintf("%v.MemoryReservation", cmdPrefix)
	}

	var flagMemoryReservationDefault int64

	_ = cmd.PersistentFlags().Int64(flagMemoryReservationName, flagMemoryReservationDefault, flagMemoryReservationDescription)

	return nil
}

func registerResourcesPropMemorySwap(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMemorySwapDescription := `Total memory limit (memory + swap). Set as ` + "`" + `-1` + "`" + ` to enable unlimited swap.`

	var flagMemorySwapName string
	if cmdPrefix == "" {
		flagMemorySwapName = "MemorySwap"
	} else {
		flagMemorySwapName = fmt.Sprintf("%v.MemorySwap", cmdPrefix)
	}

	var flagMemorySwapDefault int64

	_ = cmd.PersistentFlags().Int64(flagMemorySwapName, flagMemorySwapDefault, flagMemorySwapDescription)

	return nil
}

func registerResourcesPropMemorySwappiness(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMemorySwappinessDescription := `Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.`

	var flagMemorySwappinessName string
	if cmdPrefix == "" {
		flagMemorySwappinessName = "MemorySwappiness"
	} else {
		flagMemorySwappinessName = fmt.Sprintf("%v.MemorySwappiness", cmdPrefix)
	}

	var flagMemorySwappinessDefault int64

	_ = cmd.PersistentFlags().Int64(flagMemorySwappinessName, flagMemorySwappinessDefault, flagMemorySwappinessDescription)

	return nil
}

func registerResourcesPropNanoCPUs(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNanoCPUsDescription := `CPU quota in units of 10<sup>-9</sup> CPUs.`

	var flagNanoCPUsName string
	if cmdPrefix == "" {
		flagNanoCPUsName = "NanoCPUs"
	} else {
		flagNanoCPUsName = fmt.Sprintf("%v.NanoCPUs", cmdPrefix)
	}

	var flagNanoCPUsDefault int64

	_ = cmd.PersistentFlags().Int64(flagNanoCPUsName, flagNanoCPUsDefault, flagNanoCPUsDescription)

	return nil
}

func registerResourcesPropOomKillDisable(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagOomKillDisableDescription := `Disable OOM Killer for the container.`

	var flagOomKillDisableName string
	if cmdPrefix == "" {
		flagOomKillDisableName = "OomKillDisable"
	} else {
		flagOomKillDisableName = fmt.Sprintf("%v.OomKillDisable", cmdPrefix)
	}

	var flagOomKillDisableDefault bool

	_ = cmd.PersistentFlags().Bool(flagOomKillDisableName, flagOomKillDisableDefault, flagOomKillDisableDescription)

	return nil
}

func registerResourcesPropPidsLimit(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPidsLimitDescription := `Tune a container's PIDs limit. Set ` + "`" + `0` + "`" + ` or ` + "`" + `-1` + "`" + ` for unlimited, or ` + "`" + `null` + "`" + ` to not change.
`

	var flagPidsLimitName string
	if cmdPrefix == "" {
		flagPidsLimitName = "PidsLimit"
	} else {
		flagPidsLimitName = fmt.Sprintf("%v.PidsLimit", cmdPrefix)
	}

	var flagPidsLimitDefault int64

	_ = cmd.PersistentFlags().Int64(flagPidsLimitName, flagPidsLimitDefault, flagPidsLimitDescription)

	return nil
}

func registerResourcesPropUlimits(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Ulimits []*ResourcesUlimitsItems0 array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelResourcesFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, BlkioDeviceReadBpsAdded := retrieveResourcesPropBlkioDeviceReadBpsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioDeviceReadBpsAdded

	err, BlkioDeviceReadIOpsAdded := retrieveResourcesPropBlkioDeviceReadIOpsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioDeviceReadIOpsAdded

	err, BlkioDeviceWriteBpsAdded := retrieveResourcesPropBlkioDeviceWriteBpsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioDeviceWriteBpsAdded

	err, BlkioDeviceWriteIOpsAdded := retrieveResourcesPropBlkioDeviceWriteIOpsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioDeviceWriteIOpsAdded

	err, BlkioWeightAdded := retrieveResourcesPropBlkioWeightFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioWeightAdded

	err, BlkioWeightDeviceAdded := retrieveResourcesPropBlkioWeightDeviceFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || BlkioWeightDeviceAdded

	err, CgroupParentAdded := retrieveResourcesPropCgroupParentFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CgroupParentAdded

	err, CPUCountAdded := retrieveResourcesPropCPUCountFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPUCountAdded

	err, CPUPercentAdded := retrieveResourcesPropCPUPercentFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPUPercentAdded

	err, CPUPeriodAdded := retrieveResourcesPropCPUPeriodFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPUPeriodAdded

	err, CPUQuotaAdded := retrieveResourcesPropCPUQuotaFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPUQuotaAdded

	err, CPURealtimePeriodAdded := retrieveResourcesPropCPURealtimePeriodFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPURealtimePeriodAdded

	err, CPURealtimeRuntimeAdded := retrieveResourcesPropCPURealtimeRuntimeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPURealtimeRuntimeAdded

	err, CPUSharesAdded := retrieveResourcesPropCPUSharesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CPUSharesAdded

	err, CpusetCpusAdded := retrieveResourcesPropCpusetCpusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CpusetCpusAdded

	err, CpusetMemsAdded := retrieveResourcesPropCpusetMemsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CpusetMemsAdded

	err, DeviceCgroupRulesAdded := retrieveResourcesPropDeviceCgroupRulesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DeviceCgroupRulesAdded

	err, DeviceRequestsAdded := retrieveResourcesPropDeviceRequestsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DeviceRequestsAdded

	err, DevicesAdded := retrieveResourcesPropDevicesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DevicesAdded

	err, IOMaximumBandwidthAdded := retrieveResourcesPropIOMaximumBandwidthFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IOMaximumBandwidthAdded

	err, IOMaximumIOpsAdded := retrieveResourcesPropIOMaximumIOpsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IOMaximumIOpsAdded

	err, InitAdded := retrieveResourcesPropInitFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || InitAdded

	err, KernelMemoryAdded := retrieveResourcesPropKernelMemoryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || KernelMemoryAdded

	err, KernelMemoryTCPAdded := retrieveResourcesPropKernelMemoryTCPFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || KernelMemoryTCPAdded

	err, MemoryAdded := retrieveResourcesPropMemoryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MemoryAdded

	err, MemoryReservationAdded := retrieveResourcesPropMemoryReservationFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MemoryReservationAdded

	err, MemorySwapAdded := retrieveResourcesPropMemorySwapFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MemorySwapAdded

	err, MemorySwappinessAdded := retrieveResourcesPropMemorySwappinessFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MemorySwappinessAdded

	err, NanoCPUsAdded := retrieveResourcesPropNanoCPUsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NanoCPUsAdded

	err, OomKillDisableAdded := retrieveResourcesPropOomKillDisableFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || OomKillDisableAdded

	err, PidsLimitAdded := retrieveResourcesPropPidsLimitFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PidsLimitAdded

	err, UlimitsAdded := retrieveResourcesPropUlimitsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || UlimitsAdded

	return nil, retAdded
}

func retrieveResourcesPropBlkioDeviceReadBpsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioDeviceReadBpsName := fmt.Sprintf("%v.BlkioDeviceReadBps", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioDeviceReadBpsName) {
		// warning: BlkioDeviceReadBps array type []*ThrottleDevice is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropBlkioDeviceReadIOpsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioDeviceReadIOpsName := fmt.Sprintf("%v.BlkioDeviceReadIOps", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioDeviceReadIOpsName) {
		// warning: BlkioDeviceReadIOps array type []*ThrottleDevice is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropBlkioDeviceWriteBpsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioDeviceWriteBpsName := fmt.Sprintf("%v.BlkioDeviceWriteBps", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioDeviceWriteBpsName) {
		// warning: BlkioDeviceWriteBps array type []*ThrottleDevice is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropBlkioDeviceWriteIOpsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioDeviceWriteIOpsName := fmt.Sprintf("%v.BlkioDeviceWriteIOps", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioDeviceWriteIOpsName) {
		// warning: BlkioDeviceWriteIOps array type []*ThrottleDevice is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropBlkioWeightFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioWeightName := fmt.Sprintf("%v.BlkioWeight", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioWeightName) {

		var flagBlkioWeightName string
		if cmdPrefix == "" {
			flagBlkioWeightName = "BlkioWeight"
		} else {
			flagBlkioWeightName = fmt.Sprintf("%v.BlkioWeight", cmdPrefix)
		}

		flagBlkioWeightValue, err := cmd.Flags().GetInt64(flagBlkioWeightName)
		if err != nil {
			return err, false
		}
		m.BlkioWeight = &flagBlkioWeightValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropBlkioWeightDeviceFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagBlkioWeightDeviceName := fmt.Sprintf("%v.BlkioWeightDevice", cmdPrefix)
	if cmd.Flags().Changed(flagBlkioWeightDeviceName) {
		// warning: BlkioWeightDevice array type []*ResourcesBlkioWeightDeviceItems0 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropCgroupParentFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCgroupParentName := fmt.Sprintf("%v.CgroupParent", cmdPrefix)
	if cmd.Flags().Changed(flagCgroupParentName) {

		var flagCgroupParentName string
		if cmdPrefix == "" {
			flagCgroupParentName = "CgroupParent"
		} else {
			flagCgroupParentName = fmt.Sprintf("%v.CgroupParent", cmdPrefix)
		}

		flagCgroupParentValue, err := cmd.Flags().GetString(flagCgroupParentName)
		if err != nil {
			return err, false
		}
		m.CgroupParent = flagCgroupParentValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPUCountFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPUCountName := fmt.Sprintf("%v.CpuCount", cmdPrefix)
	if cmd.Flags().Changed(flagCPUCountName) {

		var flagCPUCountName string
		if cmdPrefix == "" {
			flagCPUCountName = "CpuCount"
		} else {
			flagCPUCountName = fmt.Sprintf("%v.CpuCount", cmdPrefix)
		}

		flagCPUCountValue, err := cmd.Flags().GetInt64(flagCPUCountName)
		if err != nil {
			return err, false
		}
		m.CPUCount = flagCPUCountValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPUPercentFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPUPercentName := fmt.Sprintf("%v.CpuPercent", cmdPrefix)
	if cmd.Flags().Changed(flagCPUPercentName) {

		var flagCPUPercentName string
		if cmdPrefix == "" {
			flagCPUPercentName = "CpuPercent"
		} else {
			flagCPUPercentName = fmt.Sprintf("%v.CpuPercent", cmdPrefix)
		}

		flagCPUPercentValue, err := cmd.Flags().GetInt64(flagCPUPercentName)
		if err != nil {
			return err, false
		}
		m.CPUPercent = flagCPUPercentValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPUPeriodFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPUPeriodName := fmt.Sprintf("%v.CpuPeriod", cmdPrefix)
	if cmd.Flags().Changed(flagCPUPeriodName) {

		var flagCPUPeriodName string
		if cmdPrefix == "" {
			flagCPUPeriodName = "CpuPeriod"
		} else {
			flagCPUPeriodName = fmt.Sprintf("%v.CpuPeriod", cmdPrefix)
		}

		flagCPUPeriodValue, err := cmd.Flags().GetInt64(flagCPUPeriodName)
		if err != nil {
			return err, false
		}
		m.CPUPeriod = flagCPUPeriodValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPUQuotaFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPUQuotaName := fmt.Sprintf("%v.CpuQuota", cmdPrefix)
	if cmd.Flags().Changed(flagCPUQuotaName) {

		var flagCPUQuotaName string
		if cmdPrefix == "" {
			flagCPUQuotaName = "CpuQuota"
		} else {
			flagCPUQuotaName = fmt.Sprintf("%v.CpuQuota", cmdPrefix)
		}

		flagCPUQuotaValue, err := cmd.Flags().GetInt64(flagCPUQuotaName)
		if err != nil {
			return err, false
		}
		m.CPUQuota = flagCPUQuotaValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPURealtimePeriodFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPURealtimePeriodName := fmt.Sprintf("%v.CpuRealtimePeriod", cmdPrefix)
	if cmd.Flags().Changed(flagCPURealtimePeriodName) {

		var flagCPURealtimePeriodName string
		if cmdPrefix == "" {
			flagCPURealtimePeriodName = "CpuRealtimePeriod"
		} else {
			flagCPURealtimePeriodName = fmt.Sprintf("%v.CpuRealtimePeriod", cmdPrefix)
		}

		flagCPURealtimePeriodValue, err := cmd.Flags().GetInt64(flagCPURealtimePeriodName)
		if err != nil {
			return err, false
		}
		m.CPURealtimePeriod = flagCPURealtimePeriodValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPURealtimeRuntimeFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPURealtimeRuntimeName := fmt.Sprintf("%v.CpuRealtimeRuntime", cmdPrefix)
	if cmd.Flags().Changed(flagCPURealtimeRuntimeName) {

		var flagCPURealtimeRuntimeName string
		if cmdPrefix == "" {
			flagCPURealtimeRuntimeName = "CpuRealtimeRuntime"
		} else {
			flagCPURealtimeRuntimeName = fmt.Sprintf("%v.CpuRealtimeRuntime", cmdPrefix)
		}

		flagCPURealtimeRuntimeValue, err := cmd.Flags().GetInt64(flagCPURealtimeRuntimeName)
		if err != nil {
			return err, false
		}
		m.CPURealtimeRuntime = flagCPURealtimeRuntimeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCPUSharesFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCPUSharesName := fmt.Sprintf("%v.CpuShares", cmdPrefix)
	if cmd.Flags().Changed(flagCPUSharesName) {

		var flagCPUSharesName string
		if cmdPrefix == "" {
			flagCPUSharesName = "CpuShares"
		} else {
			flagCPUSharesName = fmt.Sprintf("%v.CpuShares", cmdPrefix)
		}

		flagCPUSharesValue, err := cmd.Flags().GetInt64(flagCPUSharesName)
		if err != nil {
			return err, false
		}
		m.CPUShares = flagCPUSharesValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCpusetCpusFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCpusetCpusName := fmt.Sprintf("%v.CpusetCpus", cmdPrefix)
	if cmd.Flags().Changed(flagCpusetCpusName) {

		var flagCpusetCpusName string
		if cmdPrefix == "" {
			flagCpusetCpusName = "CpusetCpus"
		} else {
			flagCpusetCpusName = fmt.Sprintf("%v.CpusetCpus", cmdPrefix)
		}

		flagCpusetCpusValue, err := cmd.Flags().GetString(flagCpusetCpusName)
		if err != nil {
			return err, false
		}
		m.CpusetCpus = flagCpusetCpusValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropCpusetMemsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCpusetMemsName := fmt.Sprintf("%v.CpusetMems", cmdPrefix)
	if cmd.Flags().Changed(flagCpusetMemsName) {

		var flagCpusetMemsName string
		if cmdPrefix == "" {
			flagCpusetMemsName = "CpusetMems"
		} else {
			flagCpusetMemsName = fmt.Sprintf("%v.CpusetMems", cmdPrefix)
		}

		flagCpusetMemsValue, err := cmd.Flags().GetString(flagCpusetMemsName)
		if err != nil {
			return err, false
		}
		m.CpusetMems = flagCpusetMemsValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropDeviceCgroupRulesFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDeviceCgroupRulesName := fmt.Sprintf("%v.DeviceCgroupRules", cmdPrefix)
	if cmd.Flags().Changed(flagDeviceCgroupRulesName) {
		// warning: DeviceCgroupRules array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropDeviceRequestsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDeviceRequestsName := fmt.Sprintf("%v.DeviceRequests", cmdPrefix)
	if cmd.Flags().Changed(flagDeviceRequestsName) {
		// warning: DeviceRequests array type []*DeviceRequest is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropDevicesFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDevicesName := fmt.Sprintf("%v.Devices", cmdPrefix)
	if cmd.Flags().Changed(flagDevicesName) {
		// warning: Devices array type []*DeviceMapping is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveResourcesPropIOMaximumBandwidthFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIOMaximumBandwidthName := fmt.Sprintf("%v.IOMaximumBandwidth", cmdPrefix)
	if cmd.Flags().Changed(flagIOMaximumBandwidthName) {

		var flagIOMaximumBandwidthName string
		if cmdPrefix == "" {
			flagIOMaximumBandwidthName = "IOMaximumBandwidth"
		} else {
			flagIOMaximumBandwidthName = fmt.Sprintf("%v.IOMaximumBandwidth", cmdPrefix)
		}

		flagIOMaximumBandwidthValue, err := cmd.Flags().GetInt64(flagIOMaximumBandwidthName)
		if err != nil {
			return err, false
		}
		m.IOMaximumBandwidth = flagIOMaximumBandwidthValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropIOMaximumIOpsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIOMaximumIOpsName := fmt.Sprintf("%v.IOMaximumIOps", cmdPrefix)
	if cmd.Flags().Changed(flagIOMaximumIOpsName) {

		var flagIOMaximumIOpsName string
		if cmdPrefix == "" {
			flagIOMaximumIOpsName = "IOMaximumIOps"
		} else {
			flagIOMaximumIOpsName = fmt.Sprintf("%v.IOMaximumIOps", cmdPrefix)
		}

		flagIOMaximumIOpsValue, err := cmd.Flags().GetInt64(flagIOMaximumIOpsName)
		if err != nil {
			return err, false
		}
		m.IOMaximumIOps = flagIOMaximumIOpsValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropInitFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagInitName := fmt.Sprintf("%v.Init", cmdPrefix)
	if cmd.Flags().Changed(flagInitName) {

		var flagInitName string
		if cmdPrefix == "" {
			flagInitName = "Init"
		} else {
			flagInitName = fmt.Sprintf("%v.Init", cmdPrefix)
		}

		flagInitValue, err := cmd.Flags().GetBool(flagInitName)
		if err != nil {
			return err, false
		}
		m.Init = &flagInitValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropKernelMemoryFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagKernelMemoryName := fmt.Sprintf("%v.KernelMemory", cmdPrefix)
	if cmd.Flags().Changed(flagKernelMemoryName) {

		var flagKernelMemoryName string
		if cmdPrefix == "" {
			flagKernelMemoryName = "KernelMemory"
		} else {
			flagKernelMemoryName = fmt.Sprintf("%v.KernelMemory", cmdPrefix)
		}

		flagKernelMemoryValue, err := cmd.Flags().GetInt64(flagKernelMemoryName)
		if err != nil {
			return err, false
		}
		m.KernelMemory = flagKernelMemoryValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropKernelMemoryTCPFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagKernelMemoryTCPName := fmt.Sprintf("%v.KernelMemoryTCP", cmdPrefix)
	if cmd.Flags().Changed(flagKernelMemoryTCPName) {

		var flagKernelMemoryTCPName string
		if cmdPrefix == "" {
			flagKernelMemoryTCPName = "KernelMemoryTCP"
		} else {
			flagKernelMemoryTCPName = fmt.Sprintf("%v.KernelMemoryTCP", cmdPrefix)
		}

		flagKernelMemoryTCPValue, err := cmd.Flags().GetInt64(flagKernelMemoryTCPName)
		if err != nil {
			return err, false
		}
		m.KernelMemoryTCP = flagKernelMemoryTCPValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropMemoryFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMemoryName := fmt.Sprintf("%v.Memory", cmdPrefix)
	if cmd.Flags().Changed(flagMemoryName) {

		var flagMemoryName string
		if cmdPrefix == "" {
			flagMemoryName = "Memory"
		} else {
			flagMemoryName = fmt.Sprintf("%v.Memory", cmdPrefix)
		}

		flagMemoryValue, err := cmd.Flags().GetInt64(flagMemoryName)
		if err != nil {
			return err, false
		}
		m.Memory = flagMemoryValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropMemoryReservationFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMemoryReservationName := fmt.Sprintf("%v.MemoryReservation", cmdPrefix)
	if cmd.Flags().Changed(flagMemoryReservationName) {

		var flagMemoryReservationName string
		if cmdPrefix == "" {
			flagMemoryReservationName = "MemoryReservation"
		} else {
			flagMemoryReservationName = fmt.Sprintf("%v.MemoryReservation", cmdPrefix)
		}

		flagMemoryReservationValue, err := cmd.Flags().GetInt64(flagMemoryReservationName)
		if err != nil {
			return err, false
		}
		m.MemoryReservation = flagMemoryReservationValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropMemorySwapFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMemorySwapName := fmt.Sprintf("%v.MemorySwap", cmdPrefix)
	if cmd.Flags().Changed(flagMemorySwapName) {

		var flagMemorySwapName string
		if cmdPrefix == "" {
			flagMemorySwapName = "MemorySwap"
		} else {
			flagMemorySwapName = fmt.Sprintf("%v.MemorySwap", cmdPrefix)
		}

		flagMemorySwapValue, err := cmd.Flags().GetInt64(flagMemorySwapName)
		if err != nil {
			return err, false
		}
		m.MemorySwap = flagMemorySwapValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropMemorySwappinessFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMemorySwappinessName := fmt.Sprintf("%v.MemorySwappiness", cmdPrefix)
	if cmd.Flags().Changed(flagMemorySwappinessName) {

		var flagMemorySwappinessName string
		if cmdPrefix == "" {
			flagMemorySwappinessName = "MemorySwappiness"
		} else {
			flagMemorySwappinessName = fmt.Sprintf("%v.MemorySwappiness", cmdPrefix)
		}

		flagMemorySwappinessValue, err := cmd.Flags().GetInt64(flagMemorySwappinessName)
		if err != nil {
			return err, false
		}
		m.MemorySwappiness = &flagMemorySwappinessValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropNanoCPUsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNanoCPUsName := fmt.Sprintf("%v.NanoCPUs", cmdPrefix)
	if cmd.Flags().Changed(flagNanoCPUsName) {

		var flagNanoCPUsName string
		if cmdPrefix == "" {
			flagNanoCPUsName = "NanoCPUs"
		} else {
			flagNanoCPUsName = fmt.Sprintf("%v.NanoCPUs", cmdPrefix)
		}

		flagNanoCPUsValue, err := cmd.Flags().GetInt64(flagNanoCPUsName)
		if err != nil {
			return err, false
		}
		m.NanoCPUs = flagNanoCPUsValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropOomKillDisableFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagOomKillDisableName := fmt.Sprintf("%v.OomKillDisable", cmdPrefix)
	if cmd.Flags().Changed(flagOomKillDisableName) {

		var flagOomKillDisableName string
		if cmdPrefix == "" {
			flagOomKillDisableName = "OomKillDisable"
		} else {
			flagOomKillDisableName = fmt.Sprintf("%v.OomKillDisable", cmdPrefix)
		}

		flagOomKillDisableValue, err := cmd.Flags().GetBool(flagOomKillDisableName)
		if err != nil {
			return err, false
		}
		m.OomKillDisable = flagOomKillDisableValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropPidsLimitFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPidsLimitName := fmt.Sprintf("%v.PidsLimit", cmdPrefix)
	if cmd.Flags().Changed(flagPidsLimitName) {

		var flagPidsLimitName string
		if cmdPrefix == "" {
			flagPidsLimitName = "PidsLimit"
		} else {
			flagPidsLimitName = fmt.Sprintf("%v.PidsLimit", cmdPrefix)
		}

		flagPidsLimitValue, err := cmd.Flags().GetInt64(flagPidsLimitName)
		if err != nil {
			return err, false
		}
		m.PidsLimit = &flagPidsLimitValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesPropUlimitsFlags(depth int, m *models.Resources, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagUlimitsName := fmt.Sprintf("%v.Ulimits", cmdPrefix)
	if cmd.Flags().Changed(flagUlimitsName) {
		// warning: Ulimits array type []*ResourcesUlimitsItems0 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

// Extra schema cli for ResourcesBlkioWeightDeviceItems0

// register flags to command
func registerModelResourcesBlkioWeightDeviceItems0Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerResourcesBlkioWeightDeviceItems0PropPath(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesBlkioWeightDeviceItems0PropWeight(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerResourcesBlkioWeightDeviceItems0PropPath(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPathDescription := ``

	var flagPathName string
	if cmdPrefix == "" {
		flagPathName = "Path"
	} else {
		flagPathName = fmt.Sprintf("%v.Path", cmdPrefix)
	}

	var flagPathDefault string

	_ = cmd.PersistentFlags().String(flagPathName, flagPathDefault, flagPathDescription)

	return nil
}

func registerResourcesBlkioWeightDeviceItems0PropWeight(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagWeightDescription := ``

	var flagWeightName string
	if cmdPrefix == "" {
		flagWeightName = "Weight"
	} else {
		flagWeightName = fmt.Sprintf("%v.Weight", cmdPrefix)
	}

	var flagWeightDefault int64

	_ = cmd.PersistentFlags().Int64(flagWeightName, flagWeightDefault, flagWeightDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelResourcesBlkioWeightDeviceItems0Flags(depth int, m *models.ResourcesBlkioWeightDeviceItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, PathAdded := retrieveResourcesBlkioWeightDeviceItems0PropPathFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PathAdded

	err, WeightAdded := retrieveResourcesBlkioWeightDeviceItems0PropWeightFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || WeightAdded

	return nil, retAdded
}

func retrieveResourcesBlkioWeightDeviceItems0PropPathFlags(depth int, m *models.ResourcesBlkioWeightDeviceItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPathName := fmt.Sprintf("%v.Path", cmdPrefix)
	if cmd.Flags().Changed(flagPathName) {

		var flagPathName string
		if cmdPrefix == "" {
			flagPathName = "Path"
		} else {
			flagPathName = fmt.Sprintf("%v.Path", cmdPrefix)
		}

		flagPathValue, err := cmd.Flags().GetString(flagPathName)
		if err != nil {
			return err, false
		}
		m.Path = flagPathValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesBlkioWeightDeviceItems0PropWeightFlags(depth int, m *models.ResourcesBlkioWeightDeviceItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagWeightName := fmt.Sprintf("%v.Weight", cmdPrefix)
	if cmd.Flags().Changed(flagWeightName) {

		var flagWeightName string
		if cmdPrefix == "" {
			flagWeightName = "Weight"
		} else {
			flagWeightName = fmt.Sprintf("%v.Weight", cmdPrefix)
		}

		flagWeightValue, err := cmd.Flags().GetInt64(flagWeightName)
		if err != nil {
			return err, false
		}
		m.Weight = &flagWeightValue

		retAdded = true
	}

	return nil, retAdded
}

// Extra schema cli for ResourcesUlimitsItems0

// register flags to command
func registerModelResourcesUlimitsItems0Flags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerResourcesUlimitsItems0PropHard(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesUlimitsItems0PropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerResourcesUlimitsItems0PropSoft(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerResourcesUlimitsItems0PropHard(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagHardDescription := `Hard limit`

	var flagHardName string
	if cmdPrefix == "" {
		flagHardName = "Hard"
	} else {
		flagHardName = fmt.Sprintf("%v.Hard", cmdPrefix)
	}

	var flagHardDefault int64

	_ = cmd.PersistentFlags().Int64(flagHardName, flagHardDefault, flagHardDescription)

	return nil
}

func registerResourcesUlimitsItems0PropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := `Name of ulimit`

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "Name"
	} else {
		flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

func registerResourcesUlimitsItems0PropSoft(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSoftDescription := `Soft limit`

	var flagSoftName string
	if cmdPrefix == "" {
		flagSoftName = "Soft"
	} else {
		flagSoftName = fmt.Sprintf("%v.Soft", cmdPrefix)
	}

	var flagSoftDefault int64

	_ = cmd.PersistentFlags().Int64(flagSoftName, flagSoftDefault, flagSoftDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelResourcesUlimitsItems0Flags(depth int, m *models.ResourcesUlimitsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, HardAdded := retrieveResourcesUlimitsItems0PropHardFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || HardAdded

	err, NameAdded := retrieveResourcesUlimitsItems0PropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	err, SoftAdded := retrieveResourcesUlimitsItems0PropSoftFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SoftAdded

	return nil, retAdded
}

func retrieveResourcesUlimitsItems0PropHardFlags(depth int, m *models.ResourcesUlimitsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagHardName := fmt.Sprintf("%v.Hard", cmdPrefix)
	if cmd.Flags().Changed(flagHardName) {

		var flagHardName string
		if cmdPrefix == "" {
			flagHardName = "Hard"
		} else {
			flagHardName = fmt.Sprintf("%v.Hard", cmdPrefix)
		}

		flagHardValue, err := cmd.Flags().GetInt64(flagHardName)
		if err != nil {
			return err, false
		}
		m.Hard = flagHardValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesUlimitsItems0PropNameFlags(depth int, m *models.ResourcesUlimitsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.Name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "Name"
		} else {
			flagNameName = fmt.Sprintf("%v.Name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveResourcesUlimitsItems0PropSoftFlags(depth int, m *models.ResourcesUlimitsItems0, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSoftName := fmt.Sprintf("%v.Soft", cmdPrefix)
	if cmd.Flags().Changed(flagSoftName) {

		var flagSoftName string
		if cmdPrefix == "" {
			flagSoftName = "Soft"
		} else {
			flagSoftName = fmt.Sprintf("%v.Soft", cmdPrefix)
		}

		flagSoftValue, err := cmd.Flags().GetInt64(flagSoftName)
		if err != nil {
			return err, false
		}
		m.Soft = flagSoftValue

		retAdded = true
	}

	return nil, retAdded
}
