// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for Secret

// register flags to command
func registerModelSecretFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSecretPropCreatedAt(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSecretPropID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSecretPropSpec(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSecretPropUpdatedAt(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSecretPropVersion(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSecretPropCreatedAt(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCreatedAtDescription := ``

	var flagCreatedAtName string
	if cmdPrefix == "" {
		flagCreatedAtName = "CreatedAt"
	} else {
		flagCreatedAtName = fmt.Sprintf("%v.CreatedAt", cmdPrefix)
	}

	var flagCreatedAtDefault string

	_ = cmd.PersistentFlags().String(flagCreatedAtName, flagCreatedAtDefault, flagCreatedAtDescription)

	return nil
}

func registerSecretPropID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIDDescription := ``

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "ID"
	} else {
		flagIDName = fmt.Sprintf("%v.ID", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerSecretPropSpec(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagSpecName string
	if cmdPrefix == "" {
		flagSpecName = "Spec"
	} else {
		flagSpecName = fmt.Sprintf("%v.Spec", cmdPrefix)
	}

	if err := registerModelSecretSpecFlags(depth+1, flagSpecName, cmd); err != nil {
		return err
	}

	return nil
}

func registerSecretPropUpdatedAt(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagUpdatedAtDescription := ``

	var flagUpdatedAtName string
	if cmdPrefix == "" {
		flagUpdatedAtName = "UpdatedAt"
	} else {
		flagUpdatedAtName = fmt.Sprintf("%v.UpdatedAt", cmdPrefix)
	}

	var flagUpdatedAtDefault string

	_ = cmd.PersistentFlags().String(flagUpdatedAtName, flagUpdatedAtDefault, flagUpdatedAtDescription)

	return nil
}

func registerSecretPropVersion(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagVersionName string
	if cmdPrefix == "" {
		flagVersionName = "Version"
	} else {
		flagVersionName = fmt.Sprintf("%v.Version", cmdPrefix)
	}

	if err := registerModelObjectVersionFlags(depth+1, flagVersionName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSecretFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CreatedAtAdded := retrieveSecretPropCreatedAtFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CreatedAtAdded

	err, IDAdded := retrieveSecretPropIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IDAdded

	err, SpecAdded := retrieveSecretPropSpecFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SpecAdded

	err, UpdatedAtAdded := retrieveSecretPropUpdatedAtFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || UpdatedAtAdded

	err, VersionAdded := retrieveSecretPropVersionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || VersionAdded

	return nil, retAdded
}

func retrieveSecretPropCreatedAtFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCreatedAtName := fmt.Sprintf("%v.CreatedAt", cmdPrefix)
	if cmd.Flags().Changed(flagCreatedAtName) {

		var flagCreatedAtName string
		if cmdPrefix == "" {
			flagCreatedAtName = "CreatedAt"
		} else {
			flagCreatedAtName = fmt.Sprintf("%v.CreatedAt", cmdPrefix)
		}

		flagCreatedAtValue, err := cmd.Flags().GetString(flagCreatedAtName)
		if err != nil {
			return err, false
		}
		m.CreatedAt = flagCreatedAtValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSecretPropIDFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIDName := fmt.Sprintf("%v.ID", cmdPrefix)
	if cmd.Flags().Changed(flagIDName) {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "ID"
		} else {
			flagIDName = fmt.Sprintf("%v.ID", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSecretPropSpecFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSpecName := fmt.Sprintf("%v.Spec", cmdPrefix)
	if cmd.Flags().Changed(flagSpecName) {
		// info: complex object Spec SecretSpec is retrieved outside this Changed() block
	}
	flagSpecValue := m.Spec
	if swag.IsZero(flagSpecValue) {
		flagSpecValue = &models.SecretSpec{}
	}

	err, SpecAdded := retrieveModelSecretSpecFlags(depth+1, flagSpecValue, flagSpecName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SpecAdded
	if SpecAdded {
		m.Spec = flagSpecValue
	}

	return nil, retAdded
}

func retrieveSecretPropUpdatedAtFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagUpdatedAtName := fmt.Sprintf("%v.UpdatedAt", cmdPrefix)
	if cmd.Flags().Changed(flagUpdatedAtName) {

		var flagUpdatedAtName string
		if cmdPrefix == "" {
			flagUpdatedAtName = "UpdatedAt"
		} else {
			flagUpdatedAtName = fmt.Sprintf("%v.UpdatedAt", cmdPrefix)
		}

		flagUpdatedAtValue, err := cmd.Flags().GetString(flagUpdatedAtName)
		if err != nil {
			return err, false
		}
		m.UpdatedAt = flagUpdatedAtValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSecretPropVersionFlags(depth int, m *models.Secret, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagVersionName := fmt.Sprintf("%v.Version", cmdPrefix)
	if cmd.Flags().Changed(flagVersionName) {
		// info: complex object Version ObjectVersion is retrieved outside this Changed() block
	}
	flagVersionValue := m.Version
	if swag.IsZero(flagVersionValue) {
		flagVersionValue = &models.ObjectVersion{}
	}

	err, VersionAdded := retrieveModelObjectVersionFlags(depth+1, flagVersionValue, flagVersionName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || VersionAdded
	if VersionAdded {
		m.Version = flagVersionValue
	}

	return nil, retAdded
}
