// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/secret"
	"github.com/go-swagger/dockerctl/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationSecretSecretUpdateCmd returns a command to handle operation secretUpdate
func makeOperationSecretSecretUpdateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "SecretUpdate",
		Short: ``,
		RunE:  runOperationSecretSecretUpdate,
	}

	if err := registerOperationSecretSecretUpdateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSecretSecretUpdate uses cmd flags to call endpoint api
func runOperationSecretSecretUpdate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := secret.NewSecretUpdateParams()
	if err, _ = retrieveOperationSecretSecretUpdateBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSecretSecretUpdateIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSecretSecretUpdateVersionFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSecretSecretUpdateResult(appCli.Secret.SecretUpdate(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationSecretSecretUpdateParamFlags registers all flags needed to fill params
func registerOperationSecretSecretUpdateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSecretSecretUpdateBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSecretSecretUpdateIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSecretSecretUpdateVersionParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSecretSecretUpdateBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. The spec of the secret to update. Currently, only the Labels field can be updated. All other fields must remain unchanged from the [SecretInspect endpoint](#operation/SecretInspect) response values.`)

	// add flags for body
	if err := registerModelSecretSpecFlags(0, "secretSpec", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationSecretSecretUpdateIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIDDescription := `Required. The ID or name of the secret`

	var flagIDName string
	if cmdPrefix == "" {
		flagIDName = "id"
	} else {
		flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var flagIDDefault string

	_ = cmd.PersistentFlags().String(flagIDName, flagIDDefault, flagIDDescription)

	return nil
}

func registerOperationSecretSecretUpdateVersionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagVersionDescription := `Required. The version number of the secret object being updated. This is required to avoid conflicting writes.`

	var flagVersionName string
	if cmdPrefix == "" {
		flagVersionName = "version"
	} else {
		flagVersionName = fmt.Sprintf("%v.version", cmdPrefix)
	}

	var flagVersionDefault int64

	_ = cmd.PersistentFlags().Int64(flagVersionName, flagVersionDefault, flagVersionDescription)

	return nil
}

func retrieveOperationSecretSecretUpdateBodyFlag(m *secret.SecretUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.SecretSpec{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.SecretSpec: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.SecretSpec{}
	}
	err, added := retrieveModelSecretSpecFlags(0, flagBodyModel, "secretSpec", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationSecretSecretUpdateIDFlag(m *secret.SecretUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var flagIDName string
		if cmdPrefix == "" {
			flagIDName = "id"
		} else {
			flagIDName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		flagIDValue, err := cmd.Flags().GetString(flagIDName)
		if err != nil {
			return err, false
		}
		m.ID = flagIDValue

	}

	return nil, retAdded
}

func retrieveOperationSecretSecretUpdateVersionFlag(m *secret.SecretUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("version") {

		var flagVersionName string
		if cmdPrefix == "" {
			flagVersionName = "version"
		} else {
			flagVersionName = fmt.Sprintf("%v.version", cmdPrefix)
		}

		flagVersionValue, err := cmd.Flags().GetInt64(flagVersionName)
		if err != nil {
			return err, false
		}
		m.Version = flagVersionValue

	}

	return nil, retAdded
}

// parseOperationSecretSecretUpdateResult parses request result and return the string content
func parseOperationSecretSecretUpdateResult(resp0 *secret.SecretUpdateOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning secretUpdateOK is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*secret.SecretUpdateBadRequest)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*secret.SecretUpdateNotFound)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp3 any = respErr
		eresp3, ok := iResp3.(*secret.SecretUpdateInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp3) && !swag.IsZero(eresp3.Payload) {
				msgStr, err := json.Marshal(eresp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp4 any = respErr
		eresp4, ok := iResp4.(*secret.SecretUpdateServiceUnavailable)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp4) && !swag.IsZero(eresp4.Payload) {
				msgStr, err := json.Marshal(eresp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response secretUpdateOK is not supported by go-swagger cli yet.
	return "", nil
}
