// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/swarm"
	"github.com/go-swagger/dockerctl/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationSwarmSwarmUpdateCmd returns a command to handle operation swarmUpdate
func makeOperationSwarmSwarmUpdateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "SwarmUpdate",
		Short: ``,
		RunE:  runOperationSwarmSwarmUpdate,
	}

	if err := registerOperationSwarmSwarmUpdateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSwarmSwarmUpdate uses cmd flags to call endpoint api
func runOperationSwarmSwarmUpdate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := swarm.NewSwarmUpdateParams()
	if err, _ = retrieveOperationSwarmSwarmUpdateBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSwarmSwarmUpdateRotateManagerTokenFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSwarmSwarmUpdateRotateManagerUnlockKeyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSwarmSwarmUpdateRotateWorkerTokenFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ = retrieveOperationSwarmSwarmUpdateVersionFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSwarmSwarmUpdateResult(appCli.Swarm.SwarmUpdate(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationSwarmSwarmUpdateParamFlags registers all flags needed to fill params
func registerOperationSwarmSwarmUpdateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSwarmSwarmUpdateBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSwarmSwarmUpdateRotateManagerTokenParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSwarmSwarmUpdateRotateManagerUnlockKeyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSwarmSwarmUpdateRotateWorkerTokenParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSwarmSwarmUpdateVersionParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSwarmSwarmUpdateBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelSwarmSpecFlags(0, "swarmSpec", cmd); err != nil {
		return err
	}

	return nil
}

func registerOperationSwarmSwarmUpdateRotateManagerTokenParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagRotateManagerTokenDescription := `Rotate the manager join token.`

	var flagRotateManagerTokenName string
	if cmdPrefix == "" {
		flagRotateManagerTokenName = "rotateManagerToken"
	} else {
		flagRotateManagerTokenName = fmt.Sprintf("%v.rotateManagerToken", cmdPrefix)
	}

	var flagRotateManagerTokenDefault bool

	_ = cmd.PersistentFlags().Bool(flagRotateManagerTokenName, flagRotateManagerTokenDefault, flagRotateManagerTokenDescription)

	return nil
}

func registerOperationSwarmSwarmUpdateRotateManagerUnlockKeyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagRotateManagerUnlockKeyDescription := `Rotate the manager unlock key.`

	var flagRotateManagerUnlockKeyName string
	if cmdPrefix == "" {
		flagRotateManagerUnlockKeyName = "rotateManagerUnlockKey"
	} else {
		flagRotateManagerUnlockKeyName = fmt.Sprintf("%v.rotateManagerUnlockKey", cmdPrefix)
	}

	var flagRotateManagerUnlockKeyDefault bool

	_ = cmd.PersistentFlags().Bool(flagRotateManagerUnlockKeyName, flagRotateManagerUnlockKeyDefault, flagRotateManagerUnlockKeyDescription)

	return nil
}

func registerOperationSwarmSwarmUpdateRotateWorkerTokenParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagRotateWorkerTokenDescription := `Rotate the worker join token.`

	var flagRotateWorkerTokenName string
	if cmdPrefix == "" {
		flagRotateWorkerTokenName = "rotateWorkerToken"
	} else {
		flagRotateWorkerTokenName = fmt.Sprintf("%v.rotateWorkerToken", cmdPrefix)
	}

	var flagRotateWorkerTokenDefault bool

	_ = cmd.PersistentFlags().Bool(flagRotateWorkerTokenName, flagRotateWorkerTokenDefault, flagRotateWorkerTokenDescription)

	return nil
}

func registerOperationSwarmSwarmUpdateVersionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagVersionDescription := `Required. The version number of the swarm object being updated. This is required to avoid conflicting writes.`

	var flagVersionName string
	if cmdPrefix == "" {
		flagVersionName = "version"
	} else {
		flagVersionName = fmt.Sprintf("%v.version", cmdPrefix)
	}

	var flagVersionDefault int64

	_ = cmd.PersistentFlags().Int64(flagVersionName, flagVersionDefault, flagVersionDescription)

	return nil
}

func retrieveOperationSwarmSwarmUpdateBodyFlag(m *swarm.SwarmUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.SwarmSpec{}
		if err := json.Unmarshal([]byte(flagBodyValueStr), &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.SwarmSpec: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.SwarmSpec{}
	}
	err, added := retrieveModelSwarmSpecFlags(0, flagBodyModel, "swarmSpec", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func retrieveOperationSwarmSwarmUpdateRotateManagerTokenFlag(m *swarm.SwarmUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("rotateManagerToken") {

		var flagRotateManagerTokenName string
		if cmdPrefix == "" {
			flagRotateManagerTokenName = "rotateManagerToken"
		} else {
			flagRotateManagerTokenName = fmt.Sprintf("%v.rotateManagerToken", cmdPrefix)
		}

		flagRotateManagerTokenValue, err := cmd.Flags().GetBool(flagRotateManagerTokenName)
		if err != nil {
			return err, false
		}
		m.RotateManagerToken = &flagRotateManagerTokenValue

	}

	return nil, retAdded
}

func retrieveOperationSwarmSwarmUpdateRotateManagerUnlockKeyFlag(m *swarm.SwarmUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("rotateManagerUnlockKey") {

		var flagRotateManagerUnlockKeyName string
		if cmdPrefix == "" {
			flagRotateManagerUnlockKeyName = "rotateManagerUnlockKey"
		} else {
			flagRotateManagerUnlockKeyName = fmt.Sprintf("%v.rotateManagerUnlockKey", cmdPrefix)
		}

		flagRotateManagerUnlockKeyValue, err := cmd.Flags().GetBool(flagRotateManagerUnlockKeyName)
		if err != nil {
			return err, false
		}
		m.RotateManagerUnlockKey = &flagRotateManagerUnlockKeyValue

	}

	return nil, retAdded
}

func retrieveOperationSwarmSwarmUpdateRotateWorkerTokenFlag(m *swarm.SwarmUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("rotateWorkerToken") {

		var flagRotateWorkerTokenName string
		if cmdPrefix == "" {
			flagRotateWorkerTokenName = "rotateWorkerToken"
		} else {
			flagRotateWorkerTokenName = fmt.Sprintf("%v.rotateWorkerToken", cmdPrefix)
		}

		flagRotateWorkerTokenValue, err := cmd.Flags().GetBool(flagRotateWorkerTokenName)
		if err != nil {
			return err, false
		}
		m.RotateWorkerToken = &flagRotateWorkerTokenValue

	}

	return nil, retAdded
}

func retrieveOperationSwarmSwarmUpdateVersionFlag(m *swarm.SwarmUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("version") {

		var flagVersionName string
		if cmdPrefix == "" {
			flagVersionName = "version"
		} else {
			flagVersionName = fmt.Sprintf("%v.version", cmdPrefix)
		}

		flagVersionValue, err := cmd.Flags().GetInt64(flagVersionName)
		if err != nil {
			return err, false
		}
		m.Version = flagVersionValue

	}

	return nil, retAdded
}

// parseOperationSwarmSwarmUpdateResult parses request result and return the string content
func parseOperationSwarmSwarmUpdateResult(resp0 *swarm.SwarmUpdateOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		// Non schema case: warning swarmUpdateOK is not supported
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*swarm.SwarmUpdateBadRequest)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*swarm.SwarmUpdateInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp3 any = respErr
		eresp3, ok := iResp3.(*swarm.SwarmUpdateServiceUnavailable)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp3) && !swag.IsZero(eresp3.Payload) {
				msgStr, err := json.Marshal(eresp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	// warning: non schema response swarmUpdateOK is not supported by go-swagger cli yet.
	return "", nil
}
