// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
	"github.com/go-swagger/dockerctl/models"
)

// Schema cli for Swarm

// register flags to command
func registerModelSwarmFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded ClusterInfo flags

	if err := registerModelClusterInfoFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for AO1

	if err := registerSwarmPropAnonAO1JoinTokens(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name AO1, type

func registerSwarmPropAnonAO1JoinTokens(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagJoinTokensName string
	if cmdPrefix == "" {
		flagJoinTokensName = "JoinTokens"
	} else {
		flagJoinTokensName = fmt.Sprintf("%v.JoinTokens", cmdPrefix)
	}

	if err := registerModelJoinTokensFlags(depth+1, flagJoinTokensName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSwarmFlags(depth int, m *models.Swarm, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model ClusterInfo
	err, AO0Added := retrieveModelClusterInfoFlags(depth, &m.ClusterInfo, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || AO0Added

	// retrieve allOf AO1 fields

	err, JoinTokensAdded := retrieveSwarmPropAnonAO1JoinTokensFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || JoinTokensAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name AO1

func retrieveSwarmPropAnonAO1JoinTokensFlags(depth int, m *models.Swarm, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagJoinTokensName := fmt.Sprintf("%v.JoinTokens", cmdPrefix)
	if cmd.Flags().Changed(flagJoinTokensName) {
		// info: complex object JoinTokens JoinTokens is retrieved outside this Changed() block
	}
	flagJoinTokensValue := m.JoinTokens
	if swag.IsZero(flagJoinTokensValue) {
		flagJoinTokensValue = &models.JoinTokens{}
	}

	err, JoinTokensAdded := retrieveModelJoinTokensFlags(depth+1, flagJoinTokensValue, flagJoinTokensName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || JoinTokensAdded
	if JoinTokensAdded {
		m.JoinTokens = flagJoinTokensValue
	}

	return nil, retAdded
}
