// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/system"
	"github.com/go-swagger/dockerctl/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationSystemSystemAuthCmd returns a command to handle operation systemAuth
func makeOperationSystemSystemAuthCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "SystemAuth",
		Short: `Validate credentials for a registry and, if available, get an identity token for accessing the registry without password.`,
		RunE:  runOperationSystemSystemAuth,
	}

	if err := registerOperationSystemSystemAuthParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSystemSystemAuth uses cmd flags to call endpoint api
func runOperationSystemSystemAuth(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := system.NewSystemAuthParams()
	if err, _ = retrieveOperationSystemSystemAuthAuthConfigFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSystemSystemAuthResult(appCli.System.SystemAuth(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationSystemSystemAuthParamFlags registers all flags needed to fill params
func registerOperationSystemSystemAuthParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSystemSystemAuthAuthConfigParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSystemSystemAuthAuthConfigParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagAuthConfigName string
	if cmdPrefix == "" {
		flagAuthConfigName = "authConfig"
	} else {
		flagAuthConfigName = fmt.Sprintf("%v.authConfig", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagAuthConfigName, "", `Optional json string for [authConfig]. Authentication to check`)

	// add flags for body
	if err := registerModelAuthConfigFlags(0, "authConfig", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationSystemSystemAuthAuthConfigFlag(m *system.SystemAuthParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("authConfig") {
		// Read authConfig string from cmd and unmarshal
		flagAuthConfigValueStr, err := cmd.Flags().GetString("authConfig")
		if err != nil {
			return err, false
		}

		flagAuthConfigValue := models.AuthConfig{}
		if err := json.Unmarshal([]byte(flagAuthConfigValueStr), &flagAuthConfigValue); err != nil {
			return fmt.Errorf("cannot unmarshal authConfig string in models.AuthConfig: %w", err), false
		}
		m.AuthConfig = &flagAuthConfigValue
	}
	flagAuthConfigModel := m.AuthConfig
	if swag.IsZero(flagAuthConfigModel) {
		flagAuthConfigModel = &models.AuthConfig{}
	}
	err, added := retrieveModelAuthConfigFlags(0, flagAuthConfigModel, "authConfig", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.AuthConfig = flagAuthConfigModel
	}

	if dryRun && debug {
		flagAuthConfigValueDebugBytes, err := json.Marshal(m.AuthConfig)
		if err != nil {
			return err, false
		}
		logDebugf("AuthConfig dry-run payload: %v", string(flagAuthConfigValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationSystemSystemAuthResult parses request result and return the string content
func parseOperationSystemSystemAuthResult(resp0 *system.SystemAuthOK, resp1 *system.SystemAuthNoContent, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*system.SystemAuthOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		// Non schema case: warning systemAuthNoContent is not supported
		var iResp2 any = respErr
		eresp2, ok := iResp2.(*system.SystemAuthInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp2) && !swag.IsZero(eresp2.Payload) {
				msgStr, err := json.Marshal(eresp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	// warning: non schema response systemAuthNoContent is not supported by go-swagger cli yet.
	return "", nil
}

// register flags to command
func registerModelSystemAuthOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSystemAuthOKBodyPropIdentityToken(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSystemAuthOKBodyPropStatus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSystemAuthOKBodyPropIdentityToken(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagIdentityTokenDescription := `An opaque token used to authenticate a user after a successful login`

	var flagIdentityTokenName string
	if cmdPrefix == "" {
		flagIdentityTokenName = "IdentityToken"
	} else {
		flagIdentityTokenName = fmt.Sprintf("%v.IdentityToken", cmdPrefix)
	}

	var flagIdentityTokenDefault string

	_ = cmd.PersistentFlags().String(flagIdentityTokenName, flagIdentityTokenDefault, flagIdentityTokenDescription)

	return nil
}

func registerSystemAuthOKBodyPropStatus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagStatusDescription := `Required. The status of the authentication`

	var flagStatusName string
	if cmdPrefix == "" {
		flagStatusName = "Status"
	} else {
		flagStatusName = fmt.Sprintf("%v.Status", cmdPrefix)
	}

	var flagStatusDefault string

	_ = cmd.PersistentFlags().String(flagStatusName, flagStatusDefault, flagStatusDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSystemAuthOKBodyFlags(depth int, m *system.SystemAuthOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IdentityTokenAdded := retrieveSystemAuthOKBodyPropIdentityTokenFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IdentityTokenAdded

	err, StatusAdded := retrieveSystemAuthOKBodyPropStatusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StatusAdded

	return nil, retAdded
}

func retrieveSystemAuthOKBodyPropIdentityTokenFlags(depth int, m *system.SystemAuthOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagIdentityTokenName := fmt.Sprintf("%v.IdentityToken", cmdPrefix)
	if cmd.Flags().Changed(flagIdentityTokenName) {

		var flagIdentityTokenName string
		if cmdPrefix == "" {
			flagIdentityTokenName = "IdentityToken"
		} else {
			flagIdentityTokenName = fmt.Sprintf("%v.IdentityToken", cmdPrefix)
		}

		flagIdentityTokenValue, err := cmd.Flags().GetString(flagIdentityTokenName)
		if err != nil {
			return err, false
		}
		m.IdentityToken = flagIdentityTokenValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSystemAuthOKBodyPropStatusFlags(depth int, m *system.SystemAuthOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStatusName := fmt.Sprintf("%v.Status", cmdPrefix)
	if cmd.Flags().Changed(flagStatusName) {

		var flagStatusName string
		if cmdPrefix == "" {
			flagStatusName = "Status"
		} else {
			flagStatusName = fmt.Sprintf("%v.Status", cmdPrefix)
		}

		flagStatusValue, err := cmd.Flags().GetString(flagStatusName)
		if err != nil {
			return err, false
		}
		m.Status = flagStatusValue

		retAdded = true
	}

	return nil, retAdded
}
