// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/volume"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationVolumeVolumePruneCmd returns a command to handle operation volumePrune
func makeOperationVolumeVolumePruneCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "VolumePrune",
		Short: ``,
		RunE:  runOperationVolumeVolumePrune,
	}

	if err := registerOperationVolumeVolumePruneParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationVolumeVolumePrune uses cmd flags to call endpoint api
func runOperationVolumeVolumePrune(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := volume.NewVolumePruneParams()
	if err, _ = retrieveOperationVolumeVolumePruneFiltersFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationVolumeVolumePruneResult(appCli.Volume.VolumePrune(params))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationVolumeVolumePruneParamFlags registers all flags needed to fill params
func registerOperationVolumeVolumePruneParamFlags(cmd *cobra.Command) error {
	if err := registerOperationVolumeVolumePruneFiltersParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationVolumeVolumePruneFiltersParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagFiltersDescription := `Filters to process on the prune list, encoded as JSON (a ` + "`" + `map[string][]string` + "`" + `).

Available filters:
- ` + "`" + `label` + "`" + ` (` + "`" + `label=<key>` + "`" + `, ` + "`" + `label=<key>=<value>` + "`" + `, ` + "`" + `label!=<key>` + "`" + `, or ` + "`" + `label!=<key>=<value>` + "`" + `) Prune volumes with (or without, in case ` + "`" + `label!=...` + "`" + ` is used) the specified labels.
`

	var flagFiltersName string
	if cmdPrefix == "" {
		flagFiltersName = "filters"
	} else {
		flagFiltersName = fmt.Sprintf("%v.filters", cmdPrefix)
	}

	var flagFiltersDefault string

	_ = cmd.PersistentFlags().String(flagFiltersName, flagFiltersDefault, flagFiltersDescription)

	return nil
}

func retrieveOperationVolumeVolumePruneFiltersFlag(m *volume.VolumePruneParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("filters") {

		var flagFiltersName string
		if cmdPrefix == "" {
			flagFiltersName = "filters"
		} else {
			flagFiltersName = fmt.Sprintf("%v.filters", cmdPrefix)
		}

		flagFiltersValue, err := cmd.Flags().GetString(flagFiltersName)
		if err != nil {
			return err, false
		}
		m.Filters = &flagFiltersValue

	}

	return nil, retAdded
}

// parseOperationVolumeVolumePruneResult parses request result and return the string content
func parseOperationVolumeVolumePruneResult(resp0 *volume.VolumePruneOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*volume.VolumePruneOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		var iResp1 any = respErr
		eresp1, ok := iResp1.(*volume.VolumePruneInternalServerError)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp1) && !swag.IsZero(eresp1.Payload) {
				msgStr, err := json.Marshal(eresp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}

// register flags to command
func registerModelVolumePruneOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerVolumePruneOKBodyPropSpaceReclaimed(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerVolumePruneOKBodyPropVolumesDeleted(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerVolumePruneOKBodyPropSpaceReclaimed(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagSpaceReclaimedDescription := `Disk space reclaimed in bytes`

	var flagSpaceReclaimedName string
	if cmdPrefix == "" {
		flagSpaceReclaimedName = "SpaceReclaimed"
	} else {
		flagSpaceReclaimedName = fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
	}

	var flagSpaceReclaimedDefault int64

	_ = cmd.PersistentFlags().Int64(flagSpaceReclaimedName, flagSpaceReclaimedDefault, flagSpaceReclaimedDescription)

	return nil
}

func registerVolumePruneOKBodyPropVolumesDeleted(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: VolumesDeleted []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelVolumePruneOKBodyFlags(depth int, m *volume.VolumePruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, SpaceReclaimedAdded := retrieveVolumePruneOKBodyPropSpaceReclaimedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || SpaceReclaimedAdded

	err, VolumesDeletedAdded := retrieveVolumePruneOKBodyPropVolumesDeletedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || VolumesDeletedAdded

	return nil, retAdded
}

func retrieveVolumePruneOKBodyPropSpaceReclaimedFlags(depth int, m *volume.VolumePruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagSpaceReclaimedName := fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
	if cmd.Flags().Changed(flagSpaceReclaimedName) {

		var flagSpaceReclaimedName string
		if cmdPrefix == "" {
			flagSpaceReclaimedName = "SpaceReclaimed"
		} else {
			flagSpaceReclaimedName = fmt.Sprintf("%v.SpaceReclaimed", cmdPrefix)
		}

		flagSpaceReclaimedValue, err := cmd.Flags().GetInt64(flagSpaceReclaimedName)
		if err != nil {
			return err, false
		}
		m.SpaceReclaimed = flagSpaceReclaimedValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveVolumePruneOKBodyPropVolumesDeletedFlags(depth int, m *volume.VolumePruneOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagVolumesDeletedName := fmt.Sprintf("%v.VolumesDeleted", cmdPrefix)
	if cmd.Flags().Changed(flagVolumesDeletedName) {
		// warning: VolumesDeleted array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
