// Code generated by go-swagger; DO NOT EDIT.

package plugin

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/dockerctl/models"
)

// PluginPushReader is a Reader for the PluginPush structure.
type PluginPushReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginPushReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPluginPushOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPluginPushNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPluginPushInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /plugins/{name}/push] PluginPush", response, response.Code())
	}
}

// NewPluginPushOK creates a PluginPushOK with default headers values
func NewPluginPushOK() *PluginPushOK {
	return &PluginPushOK{}
}

/*
PluginPushOK describes a response with status code 200, with default header values.

no error
*/
type PluginPushOK struct {
}

// IsSuccess returns true when this plugin push o k response has a 2xx status code
func (o *PluginPushOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugin push o k response has a 3xx status code
func (o *PluginPushOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugin push o k response has a 4xx status code
func (o *PluginPushOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugin push o k response has a 5xx status code
func (o *PluginPushOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugin push o k response a status code equal to that given
func (o *PluginPushOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugin push o k response
func (o *PluginPushOK) Code() int {
	return 200
}

func (o *PluginPushOK) Error() string {
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushOK", 200)
}

func (o *PluginPushOK) String() string {
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushOK", 200)
}

func (o *PluginPushOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginPushNotFound creates a PluginPushNotFound with default headers values
func NewPluginPushNotFound() *PluginPushNotFound {
	return &PluginPushNotFound{}
}

/*
PluginPushNotFound describes a response with status code 404, with default header values.

plugin not installed
*/
type PluginPushNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this plugin push not found response has a 2xx status code
func (o *PluginPushNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this plugin push not found response has a 3xx status code
func (o *PluginPushNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugin push not found response has a 4xx status code
func (o *PluginPushNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this plugin push not found response has a 5xx status code
func (o *PluginPushNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this plugin push not found response a status code equal to that given
func (o *PluginPushNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the plugin push not found response
func (o *PluginPushNotFound) Code() int {
	return 404
}

func (o *PluginPushNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushNotFound %s", 404, payload)
}

func (o *PluginPushNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushNotFound %s", 404, payload)
}

func (o *PluginPushNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PluginPushNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPluginPushInternalServerError creates a PluginPushInternalServerError with default headers values
func NewPluginPushInternalServerError() *PluginPushInternalServerError {
	return &PluginPushInternalServerError{}
}

/*
PluginPushInternalServerError describes a response with status code 500, with default header values.

server error
*/
type PluginPushInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this plugin push internal server error response has a 2xx status code
func (o *PluginPushInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this plugin push internal server error response has a 3xx status code
func (o *PluginPushInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugin push internal server error response has a 4xx status code
func (o *PluginPushInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugin push internal server error response has a 5xx status code
func (o *PluginPushInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this plugin push internal server error response a status code equal to that given
func (o *PluginPushInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the plugin push internal server error response
func (o *PluginPushInternalServerError) Code() int {
	return 500
}

func (o *PluginPushInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushInternalServerError %s", 500, payload)
}

func (o *PluginPushInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /plugins/{name}/push][%d] pluginPushInternalServerError %s", 500, payload)
}

func (o *PluginPushInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PluginPushInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
