// Code generated by go-swagger; DO NOT EDIT.

package session

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/dockerctl/models"
)

// SessionReader is a Reader for the Session structure.
type SessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 101:
		result := NewSessionSwitchingProtocols()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewSessionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSessionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /session] Session", response, response.Code())
	}
}

// NewSessionSwitchingProtocols creates a SessionSwitchingProtocols with default headers values
func NewSessionSwitchingProtocols() *SessionSwitchingProtocols {
	return &SessionSwitchingProtocols{}
}

/*
SessionSwitchingProtocols describes a response with status code 101, with default header values.

no error, hijacking successful
*/
type SessionSwitchingProtocols struct {
}

// IsSuccess returns true when this session switching protocols response has a 2xx status code
func (o *SessionSwitchingProtocols) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session switching protocols response has a 3xx status code
func (o *SessionSwitchingProtocols) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session switching protocols response has a 4xx status code
func (o *SessionSwitchingProtocols) IsClientError() bool {
	return false
}

// IsServerError returns true when this session switching protocols response has a 5xx status code
func (o *SessionSwitchingProtocols) IsServerError() bool {
	return false
}

// IsCode returns true when this session switching protocols response a status code equal to that given
func (o *SessionSwitchingProtocols) IsCode(code int) bool {
	return code == 101
}

// Code gets the status code for the session switching protocols response
func (o *SessionSwitchingProtocols) Code() int {
	return 101
}

func (o *SessionSwitchingProtocols) Error() string {
	return fmt.Sprintf("[POST /session][%d] sessionSwitchingProtocols", 101)
}

func (o *SessionSwitchingProtocols) String() string {
	return fmt.Sprintf("[POST /session][%d] sessionSwitchingProtocols", 101)
}

func (o *SessionSwitchingProtocols) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSessionBadRequest creates a SessionBadRequest with default headers values
func NewSessionBadRequest() *SessionBadRequest {
	return &SessionBadRequest{}
}

/*
SessionBadRequest describes a response with status code 400, with default header values.

bad parameter
*/
type SessionBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this session bad request response has a 2xx status code
func (o *SessionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session bad request response has a 3xx status code
func (o *SessionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session bad request response has a 4xx status code
func (o *SessionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this session bad request response has a 5xx status code
func (o *SessionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this session bad request response a status code equal to that given
func (o *SessionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the session bad request response
func (o *SessionBadRequest) Code() int {
	return 400
}

func (o *SessionBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session][%d] sessionBadRequest %s", 400, payload)
}

func (o *SessionBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session][%d] sessionBadRequest %s", 400, payload)
}

func (o *SessionBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SessionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSessionInternalServerError creates a SessionInternalServerError with default headers values
func NewSessionInternalServerError() *SessionInternalServerError {
	return &SessionInternalServerError{}
}

/*
SessionInternalServerError describes a response with status code 500, with default header values.

server error
*/
type SessionInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this session internal server error response has a 2xx status code
func (o *SessionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this session internal server error response has a 3xx status code
func (o *SessionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session internal server error response has a 4xx status code
func (o *SessionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this session internal server error response has a 5xx status code
func (o *SessionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this session internal server error response a status code equal to that given
func (o *SessionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the session internal server error response
func (o *SessionInternalServerError) Code() int {
	return 500
}

func (o *SessionInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session][%d] sessionInternalServerError %s", 500, payload)
}

func (o *SessionInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /session][%d] sessionInternalServerError %s", 500, payload)
}

func (o *SessionInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SessionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
